### ISSUE TITLE
Sounds a bit like React-Easy-State

### ISSUE THREAD

**Issue by joshuaquek** [pmndrs/valtio#10]
I have been a long time user of https://github.com/RisingStack/react-easy-state 
How does this package differ?

**Comment by dai-shi** [comment]
I'm not familiar with react-easy-state, so this includes some assumptions.
- API to bind state is different. React-Easy-State is HoC. Valtio is a hook. There's pros/cons. A hook is composable but leaks proxies to child components. Hoc can keep proxies contained.
- Valtio takes snapshots every time React renders, which leads a bit of overhead. Maybe not for React-Easy-State (just guessing) or MobX/Overmind. The purpose of snapshots are for Concurrent Mode. Snapshots are also wrapped by proxies, which is another overhead.

They are major differences I can see. Hope it helps.

**Comment by radum** [comment]
On the same note, would be great if you can upgrade the description to say this is for React.

**Comment by dai-shi** [comment]
Yeah, we are discussing something better one.
btw, #8 will provide a bundle for vanilla JS.

**Comment by jherr** [comment]
From the API surface of `react-easy-state` it looks like `mobx` where you wrap the component in an HOC function, in this case called `view`, in the mobx case called `observer`. I've always found those approaches hard to test. I end up needing to expose both the observer component and the raw component or whatever. The valtio approach uses hooks to bind the store to the component instance.

**Comment by AjaxSolutions** [comment]
> Valtio takes snapshots every time React renders, which leads a bit of overhead.

@dai-shi What kind of overhead is this?  If a new snapshot object object is created on each render, would it cause garbage collection issues if the snapshot is large and frequently created?

**Comment by dai-shi** [comment]
Suppose we have a simple state: `{ count: 0 }`, and forget about proxy:

```js
const state = { count: 0 }

// can mutate state
state.count++

// snapshot is conceptually implemented like this
const snapshot = (state) => ({ ...state })

// so invoking it many times will create an object everytime
state.count++
snapshot(state)
state.count++
snapshot(state)
state.count++
snapshot(state)
state.count++
snapshot(state)
...
```

However, it will only create a new object if `count` is changed.

```js
const state = { count: 0 }
const snap1 = snapshot(state)
state.count++
const snap2 = snapshot(state)
const snap3 = snapshot(state)

snap1 !== snap2 // is true
snap2 === snap3 // is true
```

> would it cause garbage collection issues

I would think it's the same with the immutability state case, like Redux.

**Comment by AjaxSolutions** [comment]
> I would think it's the same with the immutability state case, like Redux.

_Note that sometimes people get confused about Redux and assume that on every action, the state tree has to be cloned deeply. This is absolutely not the case. Only the parts that changed need to change their references._

https://softwareengineering.stackexchange.com/questions/309452/redux-memory-consumption

I just wanted to make sure that the new Valtio snapshot is not cloned deeply.  Is assumption correct?

**Comment by dai-shi** [comment]
It will clone objects in the tree only if the property is changed.
This is a recursive process, so if a property far deep in the tree changes, the root object will always change.
It should be pretty much like Redux, ImmerJS, or ImmutableJS.
(Otherwise, it's an unexpected bug)

**Comment by drcmda** [comment]
these are just shallow clones, not deep clones. a shallow clone is just a pointer op. in redux if you change a deeply nested thing, reducers will create shallow clones all the way up to the root.

**Comment by dai-shi** [comment]
Thanks for the clarification. Yeah, I think I misused "deep" not only here but in the other lib. It means recursive shallow clones. 😓

**Comment by dai-shi** [comment]
> Valtio is a hook.

I just want make it clear. The advantage of being a hook is that hooks are composable.

```js
const useFoo = () => {
  const snap = useProxy(state)
  return snap.foo
}

const useBar = (bar) => {
  const snap = useProxy(state)
  return snap[bar]
}

const useWow = () => {
  const [attr, setAttr] = useState('wow')
  const snap = useProxy(state)
  return {
    attr,
    setAttr,
    value: snap[attr],
  }
}
```

**Comment by dai-shi** [comment]
This is pretty important discussions.
It would nice to add some descriptions somewhere. Would someone like to write a blog post?
Closing this as answered.
