### ISSUE TITLE
subscribeKey doesn't work on vanilla version

### ISSUE THREAD

**Issue by cinnamon-bun** [pmndrs/valtio#105]
When importing the vanilla version of valtio, subscribeKey doesn't work.  It always gives `Error('Please use proxy object')`.

```ts
import { proxy, subscribe, snapshot } from 'valtio/vanilla';
import { subscribeKey } from 'valtio/utils';

let state = proxy({
    name: 'Suzy',
});

subscribeKey(state, 'name', () => {});  // error
```

---

I was able to copy-paste the subscribeKey function into my file, instead of importing it, and then it worked.

I also added the `notifyInSync` variable which is missing from `subscribeKey`:

```ts
// this pasted into the above file, makes it work
export const subscribeKey = <T extends object>(
    proxyObject: T,
    key: keyof T,
    callback: (value: T[typeof key]) => void,
    notifyInSync?: boolean,
) => {
    let prevValue = proxyObject[key];
    return subscribe(proxyObject, () => {
        const nextValue = proxyObject[key];
        if (!Object.is(prevValue, nextValue)) {
            callback((prevValue = nextValue));
        }
    }, notifyInSync);
};
```

**Comment by dai-shi** [comment]
Thanks for reporting.
Actually, I realized all of `jotai/utils` doesn't work with `jotai/vanilla`.
It's a bundling issue. Let me think how to deal with it. (suggestions are welcome from anyone.)

For `notifyInSync`, nice catch. Would you like to open a PR?

**Comment by dai-shi** [comment]
In your environment, what would be the issue of using the default build? What kind of error would you get?
```js
import { proxy, subscribe, snapshot } from 'valtio';
import { subscribeKey } from 'valtio/utils';
```
