### ISSUE TITLE
No way to access resolved data of the async value from state

### ISSUE THREAD

**Issue by domlazic** [pmndrs/valtio#108]
looking at how async values are implemented it looks like it's not possible to access the resolved data of the async value directly from the state, which could be useful if for example you want to update the value based on the current value.

for non-async values you can do this:

```javascript
const state = proxy({ count: 0 })
state.count = state.count + 1
```

but if `count` is an async value there doesn't seem to be a way of doing the equivalent

I was expecting this to be possible by doing something like this:

```javascript
const state = proxy({ count: Promise.resolve(0) })
state.count = state.count.then((currentCount) => currentCount + 1)
```

but it turns out that the value with which the original promise resolves is not returned from the internal promise handler, so the `currentCount` from above ends up being `undefined`.

is there a specific reason why the value is not returned from the internal promise handler?

**Update:**
I opened a PR with a fix, basically just returning the resolved value from the internal promise handler. I don't know how useful of a change this is so please close the PR if this change doesn't make sense

**Comment by dai-shi** [comment]
Ah, nice catch. It's a use case I overlooked.
Oh, and you filed a PR, so nice.
