### ISSUE TITLE
How can I "get" current state?

### ISSUE THREAD

**Issue by IljaDaderko** [pmndrs/valtio#11]
Really enjoying this library! I came across an issue when I need to add extra data to a state (and persist previous one) object i.e.

```ts
assetState.textures = { ...assetState.textures, ...sheet.textures };
```

Doing something like this results in the following error

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at proxy (index.js:46)
    at Object.set (index.js:125)
    at index.js:137
    at Array.forEach (<anonymous>)
    at proxy (index.js:136)
    at Object.set (index.js:125)
    at index.js:137
    at Array.forEach (<anonymous>)
    at proxy (index.js:136)
    at Object.set (index.js:125)
```

Error points to this line of code

```ts
const emptyCopy = Array.isArray(initialObject) ? [] : Object.create(initialObject.constructor.prototype);
```

I log out `assetState` prior to that line that throws errors and it seems it is created correctly, I see things like `[[Handler]]` etc..

**Comment by dai-shi** [comment]
Thanks for reporting. You might hit a new bug, which is nice.

I can't repro this in codesandbox. Can you?
https://codesandbox.io/s/icy-moon-1isxp?file=/src/App.js

There must be something missing.

**Comment by IljaDaderko** [comment]
I might be doing something weird, but this is how I'm setting that state. Essentially inside a function that returns promise.
Here is full function, a lot of unnecessary stuff here, but might be important. I commented the place where state is set. If you don't see anything out of the ordinary here, let me know, I will try to recreate my full example in codesandbox as well 

```ts
export const assetState = proxy({
  textures: {},
  data: {}
});

async function loadAssets(
  name: string,
  image: unknown,
  json: object
) {
  return new Promise<void>(resolve => {
    const loader = new Loader();
    loader.add(name, image);
    loader.load((_, resources) => {
      const texture = resources[name]?.texture;
      if (texture) {
        const sprite = new Sprite(texture);
        const { width, height } = sprite;
        const renderTexture = RenderTexture.create({
          width,
          height
        });
        renderer.render(sprite, renderTexture);
        const sheet = new Spritesheet(renderTexture, json);
        sheet.parse(() => {

          // Setting state here
          assetState.textures = { ...assetState.textures, ...sheet.textures };
          assetState.data = { ...assetState.data, ...json.frames };

          texture.destroy();
          sprite.destroy();
          loader.destroy();
          resolve();
        });
      }
    });
  });
}
```

**Comment by dai-shi** [comment]
```js
const sheet = new Spritesheet(renderTexture, json);
```

This is probably creating some objects with constructor===undefined.

Yes, please try to create one in codesandbox.

**Comment by IljaDaderko** [comment]
You are right, closing this as issue is not related to the lib 👍

**Comment by dai-shi** [comment]
No, no. It is related as its use case seems valid. What is Spritesheet?

**Comment by IljaDaderko** [comment]
Alright, `Spritesheet` is a class from pixi.js library
http://pixijs.download/release/docs/PIXI.Spritesheet.html

**Comment by dai-shi** [comment]
Do you think you can reproduce it in codesandbox?
My initial trial failed: `Cannot read property 'baseTexture' of null`

https://codesandbox.io/s/blazing-https-hd5iw?file=/src/App.js

**Comment by IljaDaderko** [comment]
@dai-shi sure thing, here is codesandbox that's throwing that exact error that I'm getting
https://codesandbox.io/s/peaceful-voice-u7827?file=/src/App.js

**Comment by dai-shi** [comment]
It looks like `Texture._events` 's constructor is undefined.
