### ISSUE TITLE
React input cursor jumps to end of input

### ISSUE THREAD

**Issue by crobinson42** [pmndrs/valtio#132]
When using `useSnapshot(state)` value for a controlled input, the cursor jumps to the end. 

> Side note: the `react.js` file in this package is overly bloated and could use some efficiency improvements, also. Is the library author interested in working on this or accepting a PR to improve the codebase?

Here's a sandbox:

https://codesandbox.io/s/valtio-react-input-cursor-jumps-8m4bg

**Comment by dai-shi** [comment]
This is an unfortunate limitation in valtio. The workaround is the sync option.
https://codesandbox.io/s/valtio-react-input-cursor-jumps-forked-zl1yq

>  is overly bloated and could use some efficiency improvements

sorry, not quite sure what this is pointing to. suggestions are welcome, but most implementations are required for concurrent mode, hypothetically, and we don't have enough tests to cover it. So, I can't tell if PRs can be accepted now. Maybe, you want to start with discussing possible room for improvement in a new issue.

**Comment by crobinson42** [comment]
I just found the `sync` option and came back to close the issue, thanks!

Regarding the _efficiency_ comment on the code, 100% my opinion. Mobx does this observer pattern pretty efficiently. Also, Object `getter`/`setter` could possibly be a more performant strategy, but again, opinionated.

**Great lib @dai-shi**, thanks!
