### ISSUE TITLE
How to set value of state when the value was initialized asynchornously

### ISSUE THREAD

**Issue by DominicTobias** [pmndrs/valtio#142]
Hey, this is my fav global state manager thanks. Getting state async works great as per docs:

```js
import { get } from 'idb-keyval'

interface AppState {
  accountType: 'free' | 'paid'
  files: File[]
}

const storedAppState = get<AppState>('xx-appstate')

export const appStateProxy = proxy({
  accountType: storedAppState.then(s => s?.accountType),
  files: storedAppState.then(s => s?.files),
})
```

My intention is just to hydrate the store with values from IndexedDB, but it's unclear to me how to set these values e.g.

```js
// Error since accountType is a Promise
appStateProxy.accountType = 'free'
```

Thanks for any help

**Comment by DominicTobias** [comment]
Never mind I'll just set them after:

```ts
export const appStateProxy = proxy<AppState>({
  accountType: undefined,
  files: [],
})

storedAppState.then(s => {
  if (s) {
    appStateProxy.accountType = s.accountType
    appStateProxy.files = s.files
  }
})
```

**Comment by dai-shi** [comment]
It's typing issue, right? Please try this.

```ts
export const appStateProxy = proxy({
  accountType: storedAppState.then(s => s?.accountType) as Promise<AppState["accountType"] | undefined> | AppState["accountType"],
  files: storedAppState.then(s => s?.files) as Promise<AppState["files"] | undefined> | AppState["files"],
})
```

Your solution works too, but it will not suspend with `useSnapshot`.

**Comment by DominicTobias** [comment]
> It's typing issue, right? Please try this.
> 
> ```ts
> export const appStateProxy = proxy({
>   accountType: storedAppState.then(s => s?.accountType) as Promise<AppState["accountType"] | undefined> | AppState["accountType"],
>   files: storedAppState.then(s => s?.files) as Promise<AppState["files"] | undefined> | AppState["files"],
> })
> ```
> 
> Your solution works too, but it will not suspend with `useSnapshot`.

You're right that works thanks 👌

**Comment by DominicTobias** [comment]
For anyone reading this, you can make it less verbose:

```ts
type PV<V extends keyof AppState> = Promise<AppState[V] | undefined> | AppState[V]

export const appStateProxy = proxy({
  accountType: storedAppState.then(s => s?.accountType) as PV<'accountType'>,
  files: storedAppState.then(s => s?.files) as PV<'files'>,
  newFilePromptOpen: false,
})
```

**Comment by rubenapino** [comment]
Love this library as well, I've been using it and have a similar question trying to set initial store state as the resolved value from a promise. I'm not a typescript user, but I'm not getting suspense functionality and It seems like the return is just a promise object rather than the value itself. Is there a reason this doesn't work in Javacsript?

`export const appStateProxy = proxy({
  accountType: storedAppState.then(s => s?.accountType),
  files: storedAppState.then(s => s?.files),
})`

**Comment by dai-shi** [comment]
> I keep getting a 'Please use Proxy object' error

Maybe, there's a bug somewhere else in your code.

**Comment by rubenapino** [comment]
This is my valtio store

```javascript
import {proxy, subscribe, snapshot} from 'valtio'
import { queryWebSocket } from './websocket'

export const buildQuery = (type, value, subtype) => `{"action":"search", "value":{"type":"req_query", "data":{"type":"${type}", ${subtype? '"subtype":"' + subtype + '",': ''} "value":"${value}"}}}`

const initialState = {
    activeLayer:0,
    requirements: queryWebSocket(buildQuery('all_requirements', 'Part')).then(val=> val)
}

export let store = proxy(initialState)

```


The websocket request is 
```javascript
export const queryWebSocket = async (request) => {
    const socket = await websocket
    await waitForOpenSocket(socket)
   
    const response = await sendRequest(socket, request)
    return response
}

```

I'm getting the data back from the websocket ass expected, but I'm getting a promise with the response, and I'm not sure how to resolve it in the valtio store.

**Comment by dai-shi** [comment]
It doesn't seem anything wrong at a glance. You may want to create a reproduction as small as possible in codesandbox http://react.new, and open a [new discussion](https://github.com/pmndrs/valtio/discussions/new).

**Comment by rubenapino** [comment]
> It doesn't seem anything wrong at a glance. You may want to create a reproduction as small as possible in codesandbox http://react.new, and open a [new discussion](https://github.com/pmndrs/valtio/discussions/new).

I'll work on this tomorrow and follow up, thank you!

**Comment by rubenapino** [comment]
Just posted a new discussion in #536 with a codesandbox replication
