### ISSUE TITLE
`NonPromise` utility type breaks `React.Ref` type

### ISSUE THREAD

**Issue by italodeandra** [pmndrs/valtio#145]
### Context

I'm saving inside the proxy a ref of a button.

### Description

But when I use `useSnapshot`, which returns the type infered from the proxy but wrapped with the utility `NonPromise`, my ref, which type is `React.Ref` before the utility, becomes something else (I know this is a wrong assumption, and I understand that `React.Ref` is actually what the utility translates to, but it would be nice if it translated to the same thing so TypeScript understands that it is exactly what he is expecting).

### Example

Here's an example of why it's not nice (typing error):

https://codesandbox.io/s/valtio-ref-with-reactref-191rw?file=/src/App.tsx

### Workaround

For people with the same problem here's the workaround:

```tsx
useSnapshot(state) as typeof state;
```

https://codesandbox.io/s/valtio-ref-with-reactref-workaround-cmbkn?file=/src/App.tsx

**Comment by dai-shi** [comment]
I agree `NonPromise` is annoying in general.
Anyone has any suggestions?
I feel like majority of valtio users don't use async feature, so typing for promise resolving could be opt-in.
Also, `NonPromise` was bad choice of naming, as it does "unwrap-" or "resolve-" promise. ("non-" may imply `never`...)

**Comment by italodeandra** [comment]
For fixing the Ref type problem, my suggestion would be this:

```ts
export declare type NonPromise<T> = T extends Function
  ? T
  : T extends { current: unknown }
  ? T
  : T extends Promise<infer V>
  ? V
  : T extends object
  ? {
      [K in keyof T]: NonPromise<T[K]>
    }
  : T
```

Which already fixes the problem. But we're actually adding something specific to React inside the `vanilla`. But as you can see, I'm not using `React.Ref`, instead I'm checking just if it is an object with only `current` inside.

About the naming, if we take `ReturnType` as an inspiration, something like `DeepResolveType` is what comes to mind.

**Comment by dai-shi** [comment]
If this is only about `ref()`, we might be able to add some "tag" to the return type. But, I feel like there are still some other pitfalls.
