### ISSUE TITLE
Return value of useSnapshot is not plain(immutable) object

### ISSUE THREAD

**Issue by 1natsu172** [pmndrs/valtio#158]
I'm using `useSnapshot` and found what I think is a bug, so I'm reporting it.

When I console.log() the return value of `useSnapshot`, it is output as a Proxy object on the v8 engine (chrome). And look at the return value of the vanilla `snapshot`, that one is a plain object.

I think the latter output result is probably correct.

![image](https://user-images.githubusercontent.com/7282145/118449067-b4d1ed00-b72d-11eb-954d-ad1eae5a0846.png)

Here is an example of CodeSandbox, check the console of the developer tool.
https://codesandbox.io/s/fragrant-firefly-weslt?file=/src/App.tsx

**Comment by dai-shi** [comment]
This is totally correct, and it's rather documentation issue about internals.

`proxy()` creates a proxy object to detect modification/mutation.
`snapshot()` returns a plain (immutable) object from the proxy object.
`useSnapshot()` wraps the plain (immutable) object returned by `snapshot()` with a new (one-shot) proxy object to detect property access. And, this allows the automatic render optimization. Internally, it uses [proxy-compare](https://www.npmjs.com/package/proxy-compare).

Essentially, valtio = valtio/vanilla + proxy-compare. A diagram: https://twitter.com/dai_shi/status/1378250039043129353

Any idea how we should educate this? Changing the API names is not an option.

**Comment by 1natsu172** [comment]
@dai-shi 
Thanks for the response. I understood that it was intentional and not a bug. 

> valtio = valtio/vanilla + proxy-compare

This explanation and diagram helped me understand. So I think it is good for education that these are included in the documentation.

Also it might be helpful to mention console debugging of the proxy object. But this may not be strictly valtio's responsibility since it is about the proxy object.

**Comment by dai-shi** [comment]
I will add a short note in readme.
