### ISSUE TITLE
are there any performance benchmarks for valtio

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/valtio#160]
I've been thinking about using valtio (or jotai) as a basic primitive to drive animations that have some kind of a graph dependency between  a combination of many variables.

Would this be performant given how the two state management systems are designed and how would it compare to `rxjs` or the `Animated.Value` primitive in 

I'm not sure how they measured these benchmarks 
https://www.npmjs.com/package/@marvinh/fast-observables

and it's more for stream processing but the observable primitive is the same and I'd love to understand how valtio behaves with heavier loads.

**Comment by dai-shi** [comment]
For specific use cases, you would need to measure by yourself.

To compare across libraries, we use https://github.com/krausest/js-framework-benchmark. Note this is for specific/simple/artificial use case.
https://github.com/krausest/js-framework-benchmark/pull/841
https://github.com/krausest/js-framework-benchmark/pull/866

> the `Animated.Value` primitive in

This sounds totally different? It should be compared with react-spring, maybe?

> I'd love to understand how valtio behaves with heavier loads.

It's really hard to say, and measurement would be necessary. From implementation point of view, valtio can be faster for simple object, and slower for deep nested object.

**Comment by zcaudate** [comment]
Sweet. I've seen that framework before. I'm not sure what kind of tests to do yet (as I'm pretty new to this) but will have a think.

I don't think they are that different. It's basically a value that moves and a set of observers watching that value and updating properties

react-spring/react-native
```
<anim>.toValue(<physics>)
<out> = interpolate(<anim>, transform)
```

can be emulated in valtio with this approach:
```
<val> = proxy({current: 0})
<out> = proxy({current: <val>.current})
subscribeKey(<val>, current, (v) => <out>.current = <val>.current)
setInterval(() => {
  <val>.current = drivingFunction(1, Date.now()))
}, 1/60)

where drivingFunction has smarts about how to change the value and when to stop the Interval function

```

**Comment by dai-shi** [comment]
> I don't think they are that different. It's basically a value that moves and a set of observers watching that value and updating properties

I see. Makes sense now.

**Comment by dai-shi** [comment]
I'm not planning to do benchmarks other than js-framework-benchmark.
If anyone is interested, please feel free to try and share the results.

In general, valtio (and proxy-compare) is developed with performance in mind, and I think it's pretty optimal. Would love to hear if anyone has ideas for improvements.

That noted, let me close this issue.
