### ISSUE TITLE
Is it possible to pass valtio store/state top-down, if i have two same component instances which have independent store instance but share same store templates?

### ISSUE THREAD

**Issue by Kaijun** [pmndrs/valtio#162]
Hi all, i'm making some kind of realworld application, which has deep-nested components and need to pass the store/state top-down through the nested components.

3 typical cases as i describe below, and i'm not sure how could i solve these cases correctly with valtio.

### Case 1: Single component instance has own single store instance

it's the most simple scenario, we have a singleton Component instance and singleton store isntance. 
In this case, i think we could simply use `import state + useProxy` to pass store instance top-down  through components.

![Untitled Diagram](https://user-images.githubusercontent.com/1693027/120365816-7b120080-c341-11eb-859f-c018b2c698c8.png)

### Case 2: Multiple component instances share  same store instance

sometimes，we probably instantiate the component multiple times, but they still share the same store instance. 
it's just a simple advanced version of `Case 1`. we could also simply get it managed using `import state + useProxy`

![Untitled Diagram-Page-2](https://user-images.githubusercontent.com/1693027/120366575-64b87480-c342-11eb-8e85-0d8e93f92394.png)

### Case 3: Multiple component instances use own store instance which shares same store template

In this situation, i have totally no idea

**how could i instantiate the store instance? could i instantiate the store instance inside the react functional component lifecycle?  if yes, in which phase and how?** 

further more，

**how could the store instance be passed top-down through components**  like the way above or is there any other better practice?

![valtio-Page-3 (1)](https://user-images.githubusercontent.com/1693027/120369430-d6de8880-c345-11eb-8d92-9a772f43a0bd.png)

---

I'm also looking forward for the best practice of Case 1/2/3, any discussions are welcomed!

**Comment by Kaijun** [comment]
I'm also looking forward for the best practice of Case 1/2/3, any discussions are welcomed!

**Comment by dai-shi** [comment]
Hi, thanks for opening the discussion up.

> i'm make some kind of realworld application

That's nice!

> `import state + useProxy`

In v1, `useProxy` from `valtio` is renamed to `useSnapshot`.

> is it possible to provide an API like `useProxyState()` to simplify the `useRef` and proxy?

We used to have one, but removed afterward before v1. This is because a) it's not a very typical use case, meaning case 1&2 is a primary use case, and b) it's just possible if you understand how to use `useRef` correctly. I feel bad providing such an api that could hide how it's working. In other words, it's not the responsibility of the library.

> if i instantiate the store inside the component, is it possible to pass it top-down using Context?

Yes, that's totally fine.

That said, I think it's a doc issue. For documenting best practices, we have wiki pages instead of readme. You are welcome to contribute a new page for case 3.

The following is my idea.

```jsx
import { createContext, useContext, useRef } from 'react'
import { proxy } from 'valtio'

const ProxyContext = createContext()

const Provider = ({ children }) => {
  const proxyRef = useRef()
  if (!proxyRef.current) {
    // lazy initialization
    proxyRef.current = proxy(...)
  }
  return (
    <ProxyContext.Provider value={proxyRef.current}>
      {children}
    </ProxyContext.Provider>
  )
}

const useProxyContext = () => {
  return useContext(ProxyContext)
}
```

**Comment by dai-shi** [comment]
Closing as answered. Feel free to have further questions.

**Comment by sp94** [comment]
Thanks for your answer @dai-shi.  I hadn't used contexts until now, so I want to share a full code snippet

```typescript
import React, { createContext, useContext, useRef } from "react";
import { proxy, useSnapshot } from "valtio";

interface IState {
  count: number;
}

const ProxyContext = createContext<IState>({ count: 0 });

const Provider = ({ children }: { children: React.ReactNode }) => {
  const proxyRef = useRef<IState>();
  if (!proxyRef.current) {
    // lazy initialization
    proxyRef.current = proxy({ count: 0 });
  }
  return (
    <ProxyContext.Provider value={proxyRef.current}>
      {children}
    </ProxyContext.Provider>
  );
};

const useProxyContext = () => {
  return useContext(ProxyContext);
};

const ComponentWithState = () => {
  const state = useProxyContext();
  const snap = useSnapshot(state);
  return (
    <div>
      <button onClick={() => ++state.count}>{snap.count}</button>
    </div>
  );
};

function App() {
  return (
    <div>
      <Provider>
        <ComponentWithState />
      </Provider>
      <Provider>
        <ComponentWithState />
      </Provider>
    </div>
  );
}

export default App;
```
