### ISSUE TITLE
Improve error message when accidentally passing non proxies

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/valtio#17]
Currently, if one passes an non-proxy object to a public API like `subscribe` that expects a proxy object, it will raise an error like `Cannot read property Symbol() of undefined` or something of undefined. To improve developer experience, a more meaningful error message would be nice.

**Comment by Aslemammad** [comment]
I'm gonna work on it. I'm the one.

**Comment by Aslemammad** [comment]
closed #26
