### ISSUE TITLE
v1.0.7 not loading as es6 module

### ISSUE THREAD

**Issue by DynamicArray** [pmndrs/valtio#173]
For previous versions, this worked:

	<script type="module">
  		import valtio from 'https://cdn.skypack.dev/valtio';
	</script>

Since v1.0.7, that's failing.

**Comment by dai-shi** [comment]
Previously, it was using cjs even if type="module", now it's properly using esm.

So, does this fix?
```js
<script type="module">
	import * as valtio from 'https://cdn.skypack.dev/valtio';
</script>
```

**Comment by DynamicArray** [comment]
Perfect. Thank you!
