### ISSUE TITLE
question about how valtio subscribe works

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/valtio#175]
with the subscribe function, are the subscribe listener function synchronous or asynchromous and if it is async, is there a way to switch to synchronous?

**Comment by zcaudate** [comment]
okay, I think I found the option https://github.com/pmndrs/valtio/blob/master/src/vanilla.ts#L190

is that correct?

**Comment by dai-shi** [comment]
yes.

**Comment by zcaudate** [comment]
@dai-shi thanks. 

Looking a bit more closely at the code, it's really simple and beautifully designed.

I stopped using `jotai` in favor of this because of how flexible the proxies are.
