### ISSUE TITLE
adding a `derive` function

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/valtio#176]
I know there's addComputed but it'd be great to have a `derive` function based off of `subscribe` to create dependent proxies.

**Comment by dai-shi** [comment]
Adding a new function in `utils` is possible. What would it be used like?

**Comment by zcaudate** [comment]
something like:

```
a = proxy({value: 1})
b =proxy({value: 2})
c = derive([a,b], () => {value: a.value + b.value} ) 
```

**Comment by dai-shi** [comment]
okay, this is actually interesting. `addComputed`/`proxyWithComputed` comes with optimization (which comes with cost), while `derive` can be based on simple subscription like `watch`. We could use `get` too.

the function in `derive` only returns a non-proxy value, so one design choice would be if it return a single value or an object (and we shallow merge).

would you like to work on it? should I help you with some base code snippet?

**Comment by zcaudate** [comment]
I've implemented something similar with the watches being stored in a global registry. It'd still be good to unregister the watches but it depends on where you'd want to put it.

```
globalThis["js_react_store$$recordLu"] = new Map()
globalThis["js_react_store$$recordCache"] = {}

function lookupId(datom){
  return (js_react_store$$recordLu).get(datom);
}

// js.react.store/lookupRecord
function lookupRecord(datom){
  let id = (js_react_store$$recordLu).get(datom);
  return (js_react_store$$recordCache[id]);
}

function addWatch(observer,k,f,datoms,isAsync){
  let entry = lookupRecord(observer);
  let watches = entry.watches || {};
  let watchFn = function (){
    observer[k] = f(...datoms);
  };
  let unsubscribeFns = (datoms).map(function (datom){
    return Valtio.subscribe(datom,watchFn,!isAsync);
  });
  watches[k] = {
    "ids":(datoms).map(lookupId),
    "unsubscribe":function (){
        (unsubscribeFns).map(function (f){
          f();
        });
      }
  };
  entry["watches"] = watches;
  watchFn();
  return watches;
}
```

**Comment by zcaudate** [comment]
actually this has a little different of a use case as each key on the proxy corresponds to a different watched value but it's essentially the same

```
a = proxy({value: 1})
b = proxy({value: 2})
c = observer({add: [[a,b],(x,y) => {value: x.value + y.value},
                       times: [[a,b],(x,y) => {value: x.value * y.value} ]]}) 
```

**Comment by dai-shi** [comment]
Okay, here's one idea from me for a start.
```js
export const derive = (fn) => {
  const proxyObject = proxy({})
  const cleanups = new Set()
  const subscriptions = new Set()
  const get = (p) => {
    if (!subscriptions.has(p)) {
      subscription.add(p)
      cleanups.add(subscribe(p, evaluate))
    }
    return p
  }
  const evaluate = () => {
    proxyObject.value = fn(get)
  }
  evaluate()
  proxyObject.cleanup = () => {
    cleanups.forEach((c) => c())
    cleanups.clear()
    subscriptions.clear()
  }
  return proxyObject
}
```

Usage:

```js
a = proxy({ value: 1 })
b = proxy({ value: 2 })
c = derive((get) => get(a).value + get(b).value)
```

**Comment by zcaudate** [comment]
hmm. it's very close to how watch(https://github.com/pmndrs/valtio/blob/master/src/utils.ts#L295) is implemented. would you think it'd be more worthwhile to build the keyed watches on top of that?

```js
a = proxy({ value: 1 })
b = proxy({ value: 2 })
c = proxy({})

;; intermediate function 
addDerived(c, "key1", (get) => get(a).value + get(b).value)
addDerived(c, "key2", (get) => get(a).value + get(b).value)
listDerivedKeys(c) // ["key1", "key2"]
hasDerived(c, "key2") // true
removeDerived(c, "key2") // true
removeDerived(c, "key2") // false

;; constructor
d = derive({"key1",  (get) => get(a).value + get(b).value),
          "key2", (get) => get(a).value + get(b).value)})

```

**Comment by dai-shi** [comment]
How about this? Do you want to track dependencies separately?

```js
export const derive = (fns) => {
  const proxyObject = proxy({})
  const cleanups = new Set()
  const subscriptions = new Set()
  const get = (p) => {
    if (!subscriptions.has(p)) {
      subscription.add(p)
      cleanups.add(subscribe(p, evaluate))
    }
    return p
  }
  const evaluate = () => {
    Object.keys(fns).forEach((key) => {
      proxyObject[key] = ref(fn[key](get))
    })
  }
  evaluate()
  // NOTE there can be prop name conflict.
  proxyObject.cleanup = () => {
    cleanups.forEach((c) => c())
    cleanups.clear()
    subscriptions.clear()
  }
  return proxyObject
}
```
I added `ref()` which should make more sense.
addDerived, and so on seem a bit confusing, or too flexible and easy to misuse.

**Comment by dai-shi** [comment]
Just noticed `addComputed` doesn't provide a way to clean up... This should be addressed separately, but it might be the same approach we discuss in this issue. Also, `addComputed` doesn't use `ref()`. 🤔

**Comment by zcaudate** [comment]
@dai-shi: how is the new `derived` function used?

I just realised that my suggestion for `addDerived` is similar to `addComputed`.

I'm a big fan of clojure-style atoms with keyed watch functions (https://clojuredocs.org/clojure.core/add-watch) so that kind influences how I code. The `getter` function argument takes a bit of getting used to for me but I guess it's more conventional `react`. It'd be great to have a function to generate the dependency graph (and also to catch cyclic dependencies which probably shouldn't be allowed).

**Comment by zcaudate** [comment]
It'd be good to have one standard way of deriving a proxy from another and managing dependencies between the proxies. I get confused when there are too many options so the simpler (and the less changes to existing code the better).

**Comment by zcaudate** [comment]
Cyclic dependencies for state management gets really horrible and complicated really quickly and it's much easier to let the ui framework take care of it. I think it'd be good to be able to guard against that.

**Comment by zcaudate** [comment]
https://stackoverflow.com/questions/60904464/detect-cycle-in-directed-graph

**Comment by dai-shi** [comment]
> how is the new derived function used?

```js
a = proxy({ value: 1 })
b = proxy({ value: 2 })
c = derive((get) => ({
  add: get(a).value + get(b).value,
  sub: get(a).value - get(b).value,
}))
```

> It'd be good to have one standard way of deriving a proxy from another

My original hope was only to provide `addComputed`, but technically there's a benefit in `proxyWithComputed` and both are provided now.
Adding `derive` will increase the confusion, so unless you or somebody insist, it won't happen.
I kind of gave up providing a single standard way, because there are so many different demands, so utils are rather unopinionated. It's good to have a nice documentation to show a standard way though.

**Comment by zcaudate** [comment]
Actually, `proxyWithComputed` is the primitive that I'm looking for - though the name threw me. 

Thanks.

I think the base primitives are enough but it'll be great to have a more opinionated flow type solution built on top valtio -> @valtio/graph or @valtio/flow or a name like that. What do you think?

**Comment by dai-shi** [comment]
Cool.
Note that `addComputed`/`proxyWithComputed` use proxy-compare underneath, so my idea for `derive` still makes sense for lightweight solution.

You are more than welcome to work on 3rd-party packages. Naming convention would be like valtio-graphq or valtio-flow if they are available. If you mean official extensions in this repo, it will be `valtio/utils` or `valtio/*` if it depends on external libs.

**Comment by zcaudate** [comment]
what's the difference between `watch` and `addComputed`?

What I'm after would be a way to manage dependent proxies. It seems like the functionality is already there. Is there a way to expose it?

Another thing I'm after is to be able to tag the proxies with a name. Then it'd be possible to do:

```js
a = named("A", {})
b = named("B", {})
watch(b, ... change a...)
c = named("C", {})
watch(b, ... change c...)

deps(a) // "B", "C"
```

**Comment by zcaudate** [comment]
there's a really basic implementation here (with global registration):

https://gist.github.com/zcaudate/e8c9fe85da0982d372bc856f3b03fe2b

it's generated code so it's super ugly

-----

If an additional TAG property were to be added to each proxy then all that is needed is the deps methods.

**Comment by zcaudate** [comment]
and the current implementation would go down to about 20 lines of code.

**Comment by dai-shi** [comment]
> what's the difference between watch and addComputed?

watch is just like a syntax sugar for subscribe. it's primary for side effects.

addComputed is specific to create a new computed property in a proxy.

```js
const a = proxy({ count: 0 })
const b = proxy({ doubled: 0 })
watch((get) => {
  b.doubled = get(a).count * 2
})
```
I guess you mean something like this. (Yeah, `derived` is basically this.)
The difference between this and `addComputed` is when you do `a.newProp = 'foo'`.


> Another thing I'm after is to be able to tag the proxies with a name.

Well, it's just a JS object, so you can do as you like.
```js
// add a name property
const p1 = proxy({})
p1.name = "A"

// maybe use a symbol to avoid name collision.
const p2 = proxy({})
const NAME = Symbol()
p2[NAME] = "A"

// if you want to avoid adding such a property, use WeakMap
const proxyNames = new WeakMap()
const setName = (p, name) => { proxyNames.set(p, name) }
const getName = (p) => proxyNames.get(p)
const p3 = proxy({})
addName(p3, "A")
getName(p3)
```

(Exposing dependencies from watch is a different story.)

**Comment by zcaudate** [comment]
sweet. I get it. 

what's difficult about exposing the watches?

**Comment by dai-shi** [comment]
maybe the api design is difficult?

**Comment by zcaudate** [comment]
okay, so the subscribe function currently is 

https://github.com/pmndrs/valtio/blob/master/src/vanilla.ts#L212

---

what about if instead of 

````
<callback> = () => createListener()
p[LISTENERS].add(< callback >)
````

make `p[LISTENERS]` a Map

``` 
<id> = gen_rand_id() or key
<callback> = () => createListener()
LISTENERS[id] = {id: <id>, callback: < callback >, ...<additional options and flags>}
```
-----

**Comment by zcaudate** [comment]
and the signature for `subscribe` would be slightly change

```
subscribe(<state>, <callback>,  {
   id?: <optional>, notifySync: <boolean>, notifyDiffs: <boolean>, ... <more options>
})
```

**Comment by zcaudate** [comment]
this change to subscribe will also affect  #155 and #177

**Comment by dai-shi** [comment]
> maybe the api design is difficult?

sorry, I meant the api of `watch`...

> notifyDiffs: <boolean>, 

This woud technically not be possible anyway, because subscriptions are nested and reused for different parent objects.

**Comment by zcaudate** [comment]
okay, got it. yep that makes sense now.

**Comment by zcaudate** [comment]
I'll close this then because most of my questions about this library have been answered.

----

I think I'll stick to what I had (external deps tracking) and reimplement the code with `addCompute`. The new `subscribe` api is also super nice which adds a lot of possibilities. 

Great stuff.

**Comment by dai-shi** [comment]
I assume, `addComputed` is often misused, and `derive` is a better abstraction. For computeds, we still have `proxyWithComputed`.

**Comment by AjaxSolutions** [comment]
FYI This sounds very similar to SolidJS [createMemo](https://www.solidjs.com/guide#introducing-primitives) which caches derived values.

**Comment by zcaudate** [comment]
It also reminds me of `computed` from vuejs.

We’ve come up with the function signature, courtesy of @daishu:
const derived = derive({
  done: (get) => Object.values(get(status)).every((v) => v === 'done'),
}, {
  sync: true,
  proxy: pobj,
})

**Comment by dai-shi** [comment]
Note: `createMemo` and `computed` track property access, but `derive` does not.
