### ISSUE TITLE
Replace the readme with one that's actually readable

### ISSUE THREAD

**Issue by OmgImAlexis** [pmndrs/valtio#18]
Not sure why the README is an image.

1. It makes it a lot harder to read.
2. It's even worse on mobile.
3. None of the examples can be selected/copied.
4. It's a waste on bandwidth.

**Comment by dai-shi** [comment]
Thanks for the notes. Does "Alt. Description" mitigate it at least?

**Comment by OmgImAlexis** [comment]
Added numbers to the problems.

Not really since the whole thing needs to be loaded(2,4) and I need to visit the bottom of the page(2).

**Comment by Paratron** [comment]
Yeah, to be honest, the image is a bit... fancy but not helping.

**Comment by dai-shi** [comment]
It's now normal.
