### ISSUE TITLE
Performance issues with a large number of items/observations

### ISSUE THREAD

**Issue by itsMapleLeaf** [pmndrs/valtio#183]
I have a use case where I need to store a large amount of user objects in a dictionary. I need to perform derivations on sizable chunks of them, and I'm running into some performance issues.

Here's a code sandbox, which is a simplified version of what I'm going for: https://codesandbox.io/s/valtio-perf-issues-sicu8?file=/src/App.js

I set up a `console.time` to show the time that derivation takes. On my machine, the derivation can sometimes take around 350ms 😞

Admittedly, it's a very unscientific benchmark, but I feel like either I'm doing something wrong, or that the library's observation can be optimized somehow?

**Comment by dai-shi** [comment]
Thanks for reporting.

https://codesandbox.io/s/valtio-perf-issues-forked-1o5tp?file=/src/App.js
I added something for comparison, still not scientific though.
It seems `proxy-compare` for render optimization takes time.

I don't know if there's room for improvement left. Even if there were, it would require some effort to improve it.
A possible workaround is to compute some derived state outside React, which may or may not help.

```js
const store = proxy({
  users: {},
  presentUsers: [],
})

subscribe(store.users, () => {
  store.presentUsers = roomUsers
    .map((name) => store.users[name])
    .filter((user) => user.status === "online")
})
```

**Comment by itsMapleLeaf** [comment]
Well, thanks for the advice and for looking into it. I think Valtio is still a net positive for my codebase overall 😇 even if I have to work around this

**Comment by dai-shi** [comment]
With new `derive`, the workaround is a little easier and idiomatic.

```js
import { proxy } from 'valtio'
import { derive } from 'valtio/utils'

const state = proxy({
  users: {},
})

derive({
  presentUsers: (get) => roomUsers
    .map((name) => get(state).users[name])
    .filter((user) => user.status === "online"),
}, {
  proxy: state,
})
```

I'd claim this as a recommended technique for performance tuning, and close this issue.

**Comment by Noitidart** [comment]
Using the example above, I saw an average of difference of 125ms between the following approaches, is it fair to assume that this is a consistent pattern below? That setting whole object of `store.users` is more efficient then setting each object inside `store.users`?

After rendering with:

```
const store = proxy({
  users: Array.from({ length: 10000 }, () => ({
    name: String(Math.random()),
    status: Math.random() > 0.5 ? 'online' : 'offline'
  }))
});

const usersProxy = derive({
  onlineUsers: get => Object.values(get(store.users)).filter(user => user.status === 'online')
});

function App() {
  const users = useSnapshot(usersProxy);

  return Object.keys(users.onlineUsers).length;
}
```

### Setting keys inside object are more expensive (~250ms)

```
for (const user of store.users) {
  user.status = Math.random() > 0.5 ? "online" : "offline",
}
```

### Setting parent key with spread object is less expensive (~65ms)

```
const nextUsers = snapshot(store.users);
for (const nextUser of nextUsers) {
  nextUser.status = Math.random() > 0.5 ? "online" : "offline",
}
store.users = nextUsers;
```

**Comment by dai-shi** [comment]
snapshot is a frozen object. i wonder if the second one works as expected.
