### ISSUE TITLE
is there a way to control exactly when diffs are applied to the proxy

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/valtio#185]
is there a way to delay notification to subscribers? i.e something like this?

```js
p = proxy({a: 1, b: 2})
subscribe(p, console.log)

p.suspendNotify()
p.a = 2  
p.a = 1   // this is the same as before so should not result in notification

p.b = 1
p.resumeNotify()

// will only print out:
-> ["set" ["b"], 2, 1]

```

**Comment by dai-shi** [comment]
No, but you could convert `[["set", ["a"], 2, 1], ["set", ["a"], 1, 2]]` ---> `[]`. I did something like this in valtio-yjs.

That doesn't mean I recommend it. If your interest is what is changed and not how, you could try comparing snapshots, which seems a better approach to me.
```js
let prevSnap = snapshot(p)
subscribe(p, () => {
  const currSnap = snapshot(p)
  // compare prevSanp and currSnap to know diffs
  prevSnap = currSnap
})
```

You could also create a new util like:
```js
const suspendableSubscribe = (p, cb) => {
  let active = true
  const suspend = () => { active = false }
  const resume = () => { active = true }
  const unsubscribe = subscribe(p, () => {
    if (active) { cb() }
  })
  return { suspend, resume, unsubscribe }
}
```
You might want `notifyInSync=true` in this case. 🤔

**Comment by zcaudate** [comment]
I started thinking about this I wanted to do a bunch of edits to an object and have all the changes propagate at the same time.

```
p = proxy({a: 1, b: 2})
Object.assign(p, {c:3, d: 4})

// reset proxy
delete p.c
delete p.d
Object.assign(p, {a:1, b: 2})
```

I'd like to have the changes be group together as a single change.

**Comment by zcaudate** [comment]
closing this as the feature is builtin already.
