### ISSUE TITLE
how to check that an object is a proxy

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/valtio#187]
is there an `isProxy` method?

**Comment by dai-shi** [comment]
I would either suggest a user land solution,
```js
import { proxy as proxyOrig } from 'valtio'

const PROXY = Symbol()
const proxy = (initialObject) => {
  const p = proxyOrig(initialObject)
  p[PROXY] = true
  return p
}
const isProxy = (x) => x[PROXY]
```

Or, detecting an error:
```js
const isProxy = (x) => {
  try {
    snapshot(x)
    return true
  } catch (e) {
    return false
  }
}
```

We have a better alternative `getVersion` but it's not documented as of now.

---
That said, my gut feeling is that coding requiring `isProxy` is not a good practice, or it's very dynamic case. It's possible, but `isProxy` is not provided for such a reason.

**Comment by zcaudate** [comment]
`getVersion` works in my case. Thanks!

**Comment by matthew-dean** [comment]
>That said, my gut feeling is that coding requiring isProxy is not a good practice, or it's very dynamic case. It's possible, but isProxy is not provided for such a reason.

There are cases where we want to create a context using either an object _or_ an already created store, like:
```tsx
export function createStoreContext<T extends Record<string, any>>(obj: T) {
  const Context = createContext({})

  const Provider = ({ children }) => {
    // In the following line, we only should createStore if it is NOT a store
    const state = useRef(createStore(obj)).current
    return (
      <Context.Provider value={state}>{children}</Context.Provider>
    )
  }

  const useStore = () => {
    const state = useContext(Context)
    const snap = useSnapshot(state)
    return snap
  }
  return { Provider, useStore }
}
```

**Comment by dai-shi** [comment]
Can you make it a proxy when you make `obj`?
