### ISSUE TITLE
Adding an atomic applyPatch method

### ISSUE THREAD

**Issue by zcaudate** [pmndrs/valtio#188]
The new subscribe invokes a callback function with a array of diffs:

```js
[["set", ["path1"], old1, new1], 
 ["set", ["path2"], old2, new2]]
```

it would be great to have a function that takes a diff array and applies all the diffs in one atomic action:

```js
p = proxy({a: 1, b: 2})
applyPatch(p, [["set", ["a"], 10 ], 
              ["set", ["b"], 20 ]])
```
so in this case, listeners with `subscribe` would trigger with 

```js
[["set", ["a"], 10, 1 ], 
 ["set", ["b"], 20, 2]]
```

**Comment by zcaudate** [comment]
This would allow finer control setting historical state.

Alternatively, can a `cas` function be implemented ?

```
p = proxy({a: 1, b: 2})
f = function cas (p, f) {
  prev = snapshot(p)
  curr = f(p)
  replace(p, curr)   // replace will replace the contents of the proxy with `curr`
}
```

this should also trigger `subscribe` with all the changes.

**Comment by dai-shi** [comment]
As I wrote somewhere, I'd encourage you to develop a 3rd party package.

**Comment by zcaudate** [comment]
okay, I reread https://github.com/pmndrs/valtio/issues/185

The problem I have with this approach is that the original proxy has to be mutated in order to figure out what the diffs are. is there a way to do this before mutation?

**Comment by dai-shi** [comment]
I mean you can parse ops and apply them in an atomic way. I know it's a tough task.
Or, I may misunderstand what you are trying.

**Comment by zcaudate** [comment]
> I mean you can parse ops and apply them in an atomic way. I know it's a tough task.

that's actually what I want to do, but apply the ops to a proxy all at the same time. I know that operations like assign can add multiple keys but I want to capture changes on more complex operations:

ie. going from

```
{a: {b: 2}, c: 1} to {a: {b: 3}}
```
would be involve the following ops:

```
[["set", ["a", "b"], 3, 2],
 ["delete", ["c"], 3]]
```

I'd like for the diffs to be applied all at once to the proxy before the subscribers are notified so that it mimics a transaction in that either all changes go through or none will go through.

**Comment by dai-shi** [comment]
```js
[["set", ["a", "b"], 3, 2],
 ["delete", ["c"], 3]]
```
This is not an atomic operation. Notice proxies are nested.

As valtio batches notifications within a tick, so:
```js
const p = proxy({ a: {b: 2}, c: 1 })
subscribe(p, () => console.log('changed'))
p.a.b = 3
delete p.c
```
will notify once.

**Comment by zcaudate** [comment]
@dai-shi, oh thanks. That makes more sense now. 

> As valtio batches notifications within a tick

Can you point me to the code that does the batching?

**Comment by dai-shi** [comment]
https://github.com/pmndrs/valtio/blob/827f0a5ddc1b5cf60e9e5a73d17d1ca44d13cad7/src/vanilla.ts#L233-L238

We use Promise.resolve() for microtasks. https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

**Comment by zcaudate** [comment]
Got it. that link explains a lot.

So basically any changes made to a proxy object within a synchronous function call will be batched. Is that correct?

**Comment by dai-shi** [comment]
Correct.

**Comment by zcaudate** [comment]
Okay. So the functionality I was looking for is already built-in.  It's a really nice feature to have.

Thanks!
