### ISSUE TITLE
Bug with history?

### ISSUE THREAD

**Issue by nosferatu500** [pmndrs/valtio#194]
Bug with history or I just don't understand how it should work.

[sandbox link](https://codesandbox.io/s/react-typescript-forked-m0s2f?file=/src/App.tsx)

After a few clicks of undo, it just stops working.

Expected: 
initial value 0
add -> undo -> add -> add -> add -> undo -> undo -> undo -> add -> add -> undo -> undo -> 0

Actual: 
initial value 0
add -> undo -> add -> add -> add -> undo -> undo -> undo -> add -> add -> undo -> undo -> 3

**Comment by dai-shi** [comment]
😱

**Comment by dai-shi** [comment]
It was really a tricky bug, but finally fixed in #195.

Thanks so much for reporting this!
