### ISSUE TITLE
In a subscription handler, if state is touched (but not changed) it leads to an infinite loop.

### ISSUE THREAD

**Issue by wilcoschoneveld** [pmndrs/valtio#20]
Previous discussions: https://github.com/pmndrs/valtio/pull/13
Related test: https://github.com/pmndrs/valtio/blob/master/tests/subscribe.test.tsx#L53

I'm thinking about a similar kind of API like seen in [immer](https://github.com/immerjs/immer):

```
subscribe(state, draft => {
    // mutate draft here
})
```

you could check if the `draft` was modified after the handler execution and determine if (and which) listeners should be called.

(Another thought: a similar technique might be possible in React components with the `useProxy` hook, allowing the batching of `draft` updates by calling listeners _after_ rendering components (instead of waiting for the next eventloop tick with `Promise.resolve()`), but I don't yet see how this could be implemented)

**Comment by Aslemammad** [comment]
@wilcoschoneveld  Could you reproduce the problem in codesandbox?

**Comment by dai-shi** [comment]
I think it's nothing related with `subscribe`. (Besides, I'm a bit hesitant to change the api. It's basically from the useMutableSource spec.)

```js
const state = proxy({ count: 0, obj: {} })

state.count = 0 // this is expected not to trigger updates, correct?

state.obj = {} // can we trigger updates because it's a new object?
```

@wilcoschoneveld Do you get the idea? Let's check if it's updated with `Object.is`.

**Comment by wilcoschoneveld** [comment]
> I'm a bit hesitant to change the api. It's basically from the useMutableSource spec.

I understand!

> ```js
> const state = proxy({ count: 0, obj: {} })
> 
> state.count = 0 // this is expected not to trigger updates, correct?
> 
> state.obj = {} // can we trigger updates because it's a new object?
> ```

Yes that makes sense!
