### ISSUE TITLE
support preact

### ISSUE THREAD

**Issue by 3imed-jaberi** [pmndrs/valtio#206]
I think Preact ecosystem need a state management tool like Valtio.
So, is there any plan to add support ?

**Comment by dai-shi** [comment]
I assume it works with `preact/compat`. Do you mean support without it?

https://github.com/pmndrs/valtio/pull/140#issuecomment-814184343 says it works with `preact/hooks` without `preact/compat`.

**Comment by 3imed-jaberi** [comment]
Thank you @dai-shi, I tried it and it works fine 💯.

**Comment by nornagon** [comment]
Is this still true? It seems like Valtio now depends on use-sync-external-store/shim and the new `use` hook in React, neither of which seem to be present in preact/hooks.

**Comment by dai-shi** [comment]
uSES/shim depends on traditional hooks. Also, `use` has a fallback. So, it should still be true.

The plan for v2 #703 is to drop uSES/shim, so unless preact/compat provides uSES shim, it will be incompatible.

**Comment by Nicolab** [comment]
Actually, Valtio is it incompatible with Preact?

**Comment by dai-shi** [comment]
I think Preact now provides uSES shim. Please give it a try. Try both v1 and v2-beta.

**Comment by Nicolab** [comment]
I tested with v1, it's compatible. I will try to test v2 this week
