### ISSUE TITLE
Subscribe to a portion of state return an error.

### ISSUE THREAD

**Issue by nosferatu500** [pmndrs/valtio#207]
For some reason I cannot subscribe to a portion of state.

I cannot provide my original code with the error, but I made a sandbox [example](https://codesandbox.io/s/react-typescript-forked-m0s2f?file=/src/App.tsx)

In my original code I got next error:
https://github.com/pmndrs/valtio/blob/be088a46d3c2e55aeb0c8cdda4b43795dd0ea711/src/vanilla.ts#L243
`Cannot read property 'add' of undefined`

**Comment by dai-shi** [comment]
Your data is a string `''`, which can not be a proxy object.
```js
subscribe('', () => {
  console.log('here')
})
```
☝️ This is not possible.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/490574/128468307-62cad2b7-3e1d-404b-89bb-bdc9db8befa3.png">
☝️ This is the error shown in DEV.

For convenience, we have `subscribeKey` for this use case. 👇 
```js
import { subscribeKey } from 'valtio/utils'

subscribeKey(state, 'data', () => {
  console.log('here')
})
```

---
Also, please note that `subscribe` shouldn't be used in render which can be invoked many times. Instead, use `useEffect` and return unsubscribe function.
```jsx
const Component = () => {
  useEffect(() => {
    const unsubscribe = subscribe(state, () => {
      console.log('here')
    }
    return unsubscribe
  }, [])
  return <div>foo</div>
}
```

**Comment by nosferatu500** [comment]
@dai-shi Thanks for explanation! My bad, I will close the issue.

**Comment by dai-shi** [comment]
No problem!
