### ISSUE TITLE
Doc typo?

### ISSUE THREAD

**Issue by AjaxSolutions** [pmndrs/valtio#21]
`const state = create({ post: fetch(url).then((res) => res.json()) })
`

Should the state object be wrapped in `proxy` instead of `create`?

**Comment by Aslemammad** [comment]
Yes, You're right.

**Comment by AjaxSolutions** [comment]
Here is  a direct link:

https://github.com/pmndrs/valtio#suspense-out-of-the-box

**Comment by dai-shi** [comment]
Nice catch! It's fixed.
