### ISSUE TITLE
Error while building valtio within Next.js

### ISSUE THREAD

**Issue by PabloSzx** [pmndrs/valtio#210]
```
(node:9173) UnhandledPromiseRejectionWarning: file:///Users/pablosz/Repositories/___/node_modules/.pnpm/valtio@1.2.0_react@17.0.2/node_modules/valtio/esm/vanilla.js:1
import { getUntracked, markToTrack } from 'proxy-compare';
                       ^^^^^^^^^^^
SyntaxError: Named export 'markToTrack' not found. The requested module 'proxy-compare' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'proxy-compare';
const { getUntracked, markToTrack } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:121:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> Build error occurred
```

~~I will add a reproduction repo soon~~

Very quick reproduction repo: https://github.com/PabloSzx/valtio-esm-build-error

Node.js version: v14.17.4

**Comment by PabloSzx** [comment]
@dai-shi Sorry for pinging, but I feel like this issue should be fixed asap

**Comment by dai-shi** [comment]
Thanks for reporting.
Do you know from which nextjs version this occurs?

**Comment by dai-shi** [comment]
@PabloSzx 
https://ci.codesandbox.io/status/pmndrs/valtio/pr/211
Would you try this? See "Local Install Instructions"

**Comment by PabloSzx** [comment]
> @PabloSzx
> https://ci.codesandbox.io/status/pmndrs/valtio/pr/211
> Would you try this? See "Local Install Instructions"

same issue @dai-shi

**Comment by PabloSzx** [comment]
> Thanks for reporting.
> Do you know from which nextjs version this occurs?

v11.1.0

**Comment by PabloSzx** [comment]
doing what the suggestion in the error says should be the good enough solution, all this is because in the index.umd.js it's not doing explicit named exports, that is, it can be analyzed statically and doesn't need runtime

import proxyCompare from "proxy-compare";

or something like that should be enough

**Comment by dai-shi** [comment]
> > Thanks for reporting.
> > Do you know from which nextjs version this occurs?
> 
> v11.1.0

Just confirm: Is there any issue with v11.0.0?

**Comment by PabloSzx** [comment]
> > > Thanks for reporting.
> > > Do you know from which nextjs version this occurs?
> > 
> > 
> > v11.1.0
> 
> Just confirm: Is there any issue with v11.0.0?

the previous version 11.0.1 didn't have this issue, but this issue is not with Next.js itself, this error is just showing the actual error behind the ESM/CommonJS Interoperability

**Comment by dai-shi** [comment]
I assumed it worked before because it picked cjs version of valtio. I wonder which change made this issue occurs.

Anyway, if we can use esm, we prefer it. I just don't know how yet, if #211 doesn't fix...

**Comment by PabloSzx** [comment]
@dai-shi https://github.com/PabloSzx/test-why-mjs check this small repo that I just made to show you why if you want to support ESM for Node.js you need to specify .mjs

you only need to do "node hello.cjs" or "npm start"

![image](https://user-images.githubusercontent.com/8672915/129124637-0537f5a6-899e-4c01-9f15-5e991cde2445.png)

**Comment by dai-shi** [comment]
Yeah, but how would you fix it? renaming to `hello.mjs` still complains.

Let me do another trial.

**Comment by dai-shi** [comment]
Would you try it again? https://ci.codesandbox.io/status/pmndrs/valtio/pr/211

**Comment by PabloSzx** [comment]
> Would you try it again? https://ci.codesandbox.io/status/pmndrs/valtio/pr/211

sorry for the late response, yeah, that fixes it

**Comment by dai-shi** [comment]
yay!!! 🎉

**Comment by PabloSzx** [comment]
> Yeah, but how would you fix it? renaming to `hello.mjs` still complains.
> 
> Let me do another trial.

about the example I gave, the solution is fixing the package itself:

![image](https://user-images.githubusercontent.com/8672915/129136807-b31ba332-4b8d-4e63-abf0-c97a5462d527.png)

**Comment by dai-shi** [comment]
Yeah, it's basically the same.

fwiw, valtio itself solves this issue with putting a small package.json file in `./esm` folder.
(would it be easier/safer to copy `./esm/*.js` files to `./esm/*.mjs` files? cc @barelyhuman I think you said that before.)

**Comment by PabloSzx** [comment]
Mmm, to give context, in the [The Guild](https://the-guild.dev/) to give first class support for ESM we use rollup and rollup + esbuild, we have tooling like https://github.com/PabloSzx/bob-esbuild and https://github.com/kamilkisiela/bob that does all this easier

**Comment by PabloSzx** [comment]
and you can even do a quick test for esm with a small script like this: https://github.com/dotansimha/graphql-code-generator/blob/master/scripts/test-esm.mjs

**Comment by barelyhuman** [comment]
> (would it be easier/safer to copy ./esm/*.js files to ./esm/*.mjs files?

@dai-shi 
Nah, makes no diff, though if both files are in the same folder, you are better off specifying cjs and mjs because of compilers , even better compat would be with cjs files being `.js` and esm being `.mjs` to maintain backward support with as many compilers as possible because most esm compilers will read the `exports` and `.mjs` just fine. 

@PabloSzx Just add in an esm folder for the same with a `package.json` specifying the entire folder as `type: module` something that we are doing in most of our libs right now, seems to be working fine for now.

**Comment by dai-shi** [comment]
> though if both files are in the same folder

Yeah, that was the case in proxy-compare.



> because most esm compilers will read the `exports` and `.mjs` just fine

right, but `valtio/dist/esm/*.js` was for some edge case bundlers who don't understand ".mjs" like webpack 4?

If we could make all esm files `.mjs`, we could remove esm/package.json.

**Comment by barelyhuman** [comment]
> right, but valtio/dist/esm/*.js was for some edge case bundlers who don't understand ".mjs" like webpack 4?

Yeah, cause then webpack would need to add that `.mjs` files are just `js files with import syntax` to work and that'd mean extra documentation which we didn't want to add hence the `.js` with the `package.json` in another `esm` folder.


> If we could make all esm files .mjs, we could remove esm/package.json. 

yes, though it still helps to keep the package.json for cases where someone force imports the package as `valtio/esm` and then can import any file inside because there's no specific exports from that folder, so you have a few types of possible imports 

`import {} from 'valtio'` -> cjs bundlers | esm bundlers automatically pick `valitio/esm/index`
`import {} from 'valtio/esm/index.js'` -> use esm module with cjs bundlers

**Comment by dai-shi** [comment]
Thanks for the clarification.

> `import {} from 'valtio/esm/index.js'` -> use esm module with cjs bundlers

Interesting. I wasn't aware this use case. Then, we need the glob pattern.

**Comment by barelyhuman** [comment]
> Interesting. I wasn't aware this use case. Then, we need the glob pattern.

Typescript and Parcel sandboxes are where I tested that. 
Yeah, will update the PR post work for the glob pattern on zustand

**Comment by MD2990** [comment]
Same issue here 
next v- 11.1.0
valtio: 1.2.0

**Comment by dai-shi** [comment]
As a workaround, please use this for now:
```bash
yarn add https://pkg.csb.dev/pmndrs/valtio/commit/ecc61a06/valtio
npm i https://pkg.csb.dev/pmndrs/valtio/commit/ecc61a06/valtio
```

We will make releases once figuring out best configs.

**Comment by MD2990** [comment]
Thanks for your response , it's working now as expected  !!!

**Comment by dai-shi** [comment]
https://github.com/pmndrs/valtio/releases/tag/v1.2.1

@PabloSzx Thanks for reporting this so quickly!

**Comment by QuirkWebDevelopment** [comment]
Was having same issue, and yarn add https://pkg.csb.dev/pmndrs/valtio/commit/ecc61a06/valtio fixed it for me, thank you!

**Comment by dai-shi** [comment]
The latest version should be fine too.
