### ISSUE TITLE
proxyWithComputed does not recognize computed type if derived from another computed in typescript

### ISSUE THREAD

**Issue by danosaur98** [pmndrs/valtio#217]
Hello,

When using `proxyWithComputed` in typescript, the type is not recognized when one computed value is derived from another computed value. Here is the example I was using: 
```
// if you want a computed value to derive from another computed, you must declare the dependency first:
const state = proxyWithComputed({
  count: 1,
}, {
  doubled: snap => snap.count * 2,
  quadrupled: snap => snap.doubled * 2
})
```
Here is the example code sandbox https://codesandbox.io/s/sharp-driscoll-ddnzs?file=/src/App.tsx. It does not recognize the type for `snap.doubled`. 

I see that the docs recommend react users to use `derive`, but I was not sure how to create a computed value that was derived from another computed value using derive. Please let me know what the proper way to do this for react and typescript. 

Thanks!

**Comment by dai-shi** [comment]
> When using `proxyWithComputed` in typescript, the type is not recognized when one computed value is derived from another computed value.

Please see #192. I will add a note in readme.



> I was not sure how to create a computed value that was derived from another computed value using derive.

You can do something like this.
https://codesandbox.io/s/dawn-snow-zyk8t?file=/src/App.tsx

```ts
const state1 = proxy({ count: 0 });
const state2 = derive(
  {
    doubled: (get) => get(state1).count * 2
  },
  { proxy: state1 }
);
const state3 = derive(
  {
    quadrupled: (get) => get(state2).doubled * 2
  },
  { proxy: state2 }
);
// state1, state2 and state3 are all same object
console.log(state1 === state2);
console.log(state1 === state3);
```

Having separate `state1`, `state2`, and `state3` are just for types.

In JavaScript, it can be just `state`.

```js
const state = proxy({ count: 0 })
derive({ doubled: (get) => get(state).count * 2 }, { proxy: state })
derive({ quadrupled: (get) => get(state).doubled * 2 }, { proxy: state })
```

It may make sense not to override the existing proxy. In this case, types just work.

```ts
const state = proxy({ count: 0 })
const derived1 = derive({ doubled: (get) => get(state).count * 2 })
const derived2 = derive({ quadrupled: (get) => get(derived1).doubled * 2 })
```

**Comment by danosaur98** [comment]
Ah I see, thanks so much!

**Comment by naivefun** [comment]
a workaround could be:
```typescript
import { proxy } from 'valtio'
import { derive } from 'valtio/utils'

const state1 = proxy({ count: 1 })
const state2 = derive(
  {
    doubled: (get) => get(state1).count * 2,
  },
  { proxy: state1 }
)
const state3 = derive(
  {
    quadrupled: (get) => get(state2).doubled * 2,
  },
  { proxy: state2 }
)
// merge types manually but works
type x = typeof state1 & typeof state2 & typeof state3
export const state = state1 as x
```
