### ISSUE TITLE
Support for "Platform Objects"

### ISSUE THREAD

**Issue by wuharvey** [pmndrs/valtio#220]
When we try to store a object containing [platform objects](https://stackoverflow.com/questions/49783889/javascript-typeerror-illegal-invocation-but-im-not-calling-any-function), the `proxy` function leads to an illegal invocation error as below. 

A simple way to reproduce this is adding a MouseEvent to a Valtio store. Personally I encountered this when trying to do something like this in r3f:

`<mesh onClick={e => state.mouseEvent = e}>`

```
Uncaught (in promise) TypeError: Illegal invocation
    at vanilla.js:63
    at Array.forEach (<anonymous>)
    at createSnapshot (vanilla.js:62)
    at Object.get (vanilla.js:102)
    at vanilla.js:84
    at Array.forEach (<anonymous>)
    at createSnapshot (vanilla.js:62)
    at Object.get (vanilla.js:102)
    at vanilla.js:84
    at Array.forEach (<anonymous>)
```

**Comment by dai-shi** [comment]
Please use `ref()` to store non plain objects.
