### ISSUE TITLE
Reset states

### ISSUE THREAD

**Issue by alexandreagostinho** [pmndrs/valtio#225]
Reset state (default values) is possible with Valtio?

**Comment by alexandreagostinho** [comment]
Tks

**Comment by rvirani1** [comment]
I've been using a utility function like this to accomplish this task. I'm sure there are some edge cases, but I haven't hit them yet.

```typescript
export function resetProxy (initialObj: any, proxy: any): void {
  Object.keys(initialObj).forEach((key) => {
    if (typeof proxy[key] === 'object' && !Array.isArray(proxy[key]) && proxy[key] !== null) {
      resetProxy(initialObj[key], proxy[key])
    } else {
      proxy[key] = initialObj[key]
    }
  })
}
```

**Comment by dai-shi** [comment]
Do you need recursion?

An edge case is the proxy references.
```js
const obj = {}
const p = proxy({ o: obj })
const o1 = p.o
p.o = obj
const o2 = p.o
o1 !== o2
```
The simple one is this:
```js
const obj = {}
proxy(obj) !== proxy(obj)
```

**Comment by rvirani1** [comment]
I'm not sure I fully follow. I found that if I don't use recursion and the value for a key is an object, then the `reset` function seems to have no effect. For example, if the `initialObj` in your example looked different:

```
const initialObj = {
  text: 'hello',
  arr: [1, 2, 3],
  obj: { a: 'b' }
}
```

Then the reset function wouldn't reset properly without the recursion. Is it an antipattern to have a nested object as a value?

**Comment by dai-shi** [comment]
Oh, wow, you are absolutely right...
https://codesandbox.io/s/hopeful-water-w710w?file=/src/App.js

It's my misunderstanding of the behavior. Hm, ok, it's because of proxy cache.
So, either the recursion or deep clone is necessary.
Sorry for the confusion! It was my bad. Your understanding is correct.

> Is it an antipattern to have a nested object as a value?

Definitely not. valtio is created to support nested objects. (otherwise, the plain `new Proxy()` almost does the job.)

**Comment by rvirani1** [comment]
Ah, got it. If there is a way to remedy this in a future version of Valtio, that would be amazing. Otherwise, I'll keep using the recursive `reset` for now. 

Also thanks again for your work on this library. Valtio is absolutely my favorite React state management library. Much appreciated!

**Comment by gersondinis** [comment]
This issue should be reopened, no?

**Comment by dai-shi** [comment]
@rvirani1 's solution is valid.

If I write it again:
```js
const initialObj = {
  text: 'hello',
  arr: [1, 2, 3],
  obj: { a: 'b' },
}

const state = proxy(initialObj)

const reset = () => {
  const walk = (p, o) => {
    Object.keys(o).forEach((key) => {
      if (typeof o[key] === 'object' && o[key] !== null) {
        if (typeof p[key] === 'object' && p[key] !== null) {
          walk(p[key], o[key])
        } else {
          p[key] = o[key]
        }
      } else {
        p[key] = o[key]
      }
    })
  }
  walk(state, initialObj)
}
```

Another solution:
```js
const initialObj = {
  text: 'hello',
  arr: [1, 2, 3],
  obj: { a: 'b' },
}

const state = proxy(initialObj)

const reset = () => {
  const resetObj = _.cloneDeep(initialObj)
  Object.keys(resetObj).forEach((key) => {
    state[key] = resetObj[key]
  })
}
```

Let's reopen or create a new discussion/issue, if they don't work.

**Comment by dai-shi** [comment]
Alternatively, if reset is your requirement, you should consider wrapping with an object.


```js
const initialObj = …

const state = proxy({ obj: initialObj })

const reset = () => {
  state.obj = _.cloneDeep(initialObj)
}
```
This looks clean.

**Comment by rvirani1** [comment]
Will give these a shot. Thanks!

**Comment by dai-shi** [comment]
@rvirani1 If you confirm those, would you like to create a wiki page? Like https://github.com/pmndrs/valtio/wiki/How-to-reset-states

So, let me reopen this as a documentation issue.

**Comment by rvirani1** [comment]
Currently, I'm finding that doing a deep clone via `lodash` is the only reliable solution that seems to work in all cases. I tried the custom solution (and even mine) and they don't seem to work if setting to an an empty object. I'm happy to write a wiki page recommending that approach if that works for you.

**Comment by dai-shi** [comment]
@rvirani1 thanks for working on it. yes, please go ahead for a wiki page.

**Comment by rvirani1** [comment]
Created!

https://github.com/pmndrs/valtio/wiki/How-to-reset-state%3F

Feel free to tweak it as you see fit

**Comment by dai-shi** [comment]
Thanks. I removed the `?` https://github.com/pmndrs/valtio/wiki/How-to-reset-state and add the alternative approach.

Closing this. Thanks for your contribution.

**Comment by waynebloss** [comment]
I switched to the following method so I don't have to use any recursive cloning. Any problems with this?

```ts
function defaultState(): MyState {
  return {
    item: {},
    itemCount: 0,
    itemIds: [],
  };
}

export const myState = proxy<MyState>(defaultState());

function resetState() {
  Object.assign(myState, defaultState());
}
```

**Comment by dai-shi** [comment]
It looks good.
> since we're creating a brand new default state object each time.

yes!
