### ISSUE TITLE
Use action names in redux devtools if action methods are defined in state

### ISSUE THREAD

**Issue by geocine** [pmndrs/valtio#229]
If I am right, it is close to impossible to use action names on redux devtools if actions are defined in a module, since valtio wouldn't have an idea what these method names are.

However, would it be possible to show action names on redux devtools if they are defined in state, instead of using the generic `Update ...` message? It would atleast help for debugging purposes.

![Screenshot 2021-08-29 at 6 33 13 PM](https://user-images.githubusercontent.com/507464/131247406-99e30eb3-7888-4fb9-8f99-6107b190aa9e.png)

**Comment by dai-shi** [comment]
As we have #177 now, it might be possible to show more info (not action names but updated paths). Let me try something naively.

**Comment by geocine** [comment]
That would be cool and much more explicit , I did not thought about that . My only concern about that is we can modify exactly the same paths on any location. It would still be hard for debugging if we would want to find which triggered the changed among all those methods/actions/statements that would seem to change the exact same paths.

I don't have an answer, but that is the problem that I would probably run into in the long term.

**Comment by dai-shi** [comment]
From proxy point of view, we can't know how it's changed, only the result of the change.

Please try #230.
https://ci.codesandbox.io/status/pmndrs/valtio/pr/230
See "Local Install Instructions" in ☝️ .
I didn't test it, and I'm not sure if it works.

**Comment by geocine** [comment]
It works, thank you!
![Screenshot 2021-08-29 at 7 05 31 PM](https://user-images.githubusercontent.com/507464/131248249-a1b64e0c-44a5-4007-84d9-2d4ad912f760.png)

**Comment by dai-shi** [comment]
Great to hear that.
Isn't it too long? Do we need the datetime?
I wonder if we make the action an object, it would make it better.

**Comment by geocine** [comment]
Yes it is long but not sure how we could improve that. I also noticed some additional information showing app when skip is clicked. I don't really know if these information needs to go to the devtools

![Screenshot 2021-08-29 at 7 47 47 PM](https://user-images.githubusercontent.com/507464/131249327-27e1454d-0802-46a3-bc80-2f5e69abe2f0.png)

**Comment by dai-shi** [comment]
Oh, that doesn't look nice. Did it happen before this PR?

---
I can take a deeper look some time later, but not soon.
If there's anyone who would like to contribute on it, I'm happy to discuss.

**Comment by geocine** [comment]
Not exactly but yes. 

![Screenshot 2021-08-30 at 1 02 59 AM](https://user-images.githubusercontent.com/507464/131258889-9840b3f2-9e9b-4ff5-946c-80a9f27d5b9f.png)

Thank you for looking into this, I appreciate it .

**Comment by dai-shi** [comment]
They shouldn't appear there, right?
I wonder if zustand's devtools have the same issue or not.
This will require some effort.

**Comment by geocine** [comment]
In my opinion yes it should not as it pollutes the actual state declared by the user. I haven't tried zustand , will give a try once I have time .
