### ISSUE TITLE
Is there are anything to scope the state for react?

### ISSUE THREAD

**Issue by wong813** [pmndrs/valtio#235]
Sorry for my bad English.

Just wonder is there are anything like `<Provider></Provider>`in Jotai?

It is because if I have 2 subtree in react, the state will be mess up.

Example:
`<div>`
  `<ValtioComponent/>`
  `<ValtioComponent/>`
`</div>`

**Comment by dai-shi** [comment]
Valtio state is a stable reference and it can just be passed by React Context.

```jsx
const MyContext = createContext()

const MyProvider = ({ children }) => {
  const stateRef = useRef()
  if (!stateRef.current) {
    stateRef.current = proxy({ count: 0 })
  }
  return (
    <MyContext value={stateRef.current}>{children}</MyContext>
  )
}

const MyCounter = () => {
  const state = useContext(MyContext)
  const snap = useSnapshot(state)
  return (
     {snap.count} <button onClick={() => ++state.count}>+1</button>
  )
}
```

I think this should be added in the recipes section.

**Comment by wong813** [comment]
Many thanks
Is it possible to add it as a built-in provider?

**Comment by dai-shi** [comment]
I don't think it's a good idea. For a) valtio api is minimalistic / straightforward, b) there are various use cases and covering everything and documenting them will make it just harder than using the native approach.
We have added something for local state once and removed.

The useRef lazy init part is just a little tricky. `use-constant` will also help, but assuming the provider won't re-render often and `proxy()` is lightweight anyway, let's guide people to this usage.

```jsx
const MyProvider = ({ children }) => {
  const state = useRef(proxy({ count: 0 })).current
  return (
    <MyContext value={state}>{children}</MyContext>
  )
}
```

I will write it in a wiki page.

**Comment by dai-shi** [comment]
Here we go: https://github.com/pmndrs/valtio/wiki/How-to-use-with-context

**Comment by rmcarias** [comment]
> Here we go: https://github.com/pmndrs/valtio/wiki/How-to-use-with-context

I was just going to ask about this.

**Comment by dai-shi** [comment]
Cool. Let me close this issue with adding an entry to the wiki page.
