### ISSUE TITLE
Devtools - middleware | combine proxies

### ISSUE THREAD

**Issue by rmcarias** [pmndrs/valtio#237]
@dai-shi 
I am using the devtools for Redux, but it seems it can only take one proxy object
devtools(proxyobj,'name');

Now that is a pain because I want to export several proxy objects, but have them show up in the DevTools under a single Name. For example,
`devtools([proxy1,proxy2],'My GlobalStore')`
Without this, the Redux Dev Tools shows puts each proxy under a different tab.

I tried doing this but devtools errors out saying it needs to be a proxy object (which they are inside the object mystore)
```
const mystore = {
    tripsProxyStore,
    appHostProxyStore
};

// This is so we can use REDUX_DEV_TOOLS
devtools(catalogStore, 'Catalog Store');
```

this means I have to do this:
devtools(tripsProxyStore, 'Catalog Store1');
devtools(appHostProxyStore, 'Catalog Store2');
...etc

Part2: 

It would be great also if devtools allowed for some middleware function

**Comment by rmcarias** [comment]
I think this might work?
```
devtools(proxy({ tripsProxyStore, appHostProxyStore }),'My Store') 
// it should still tack correctly on Chrome REdux Tools
```

**Comment by dai-shi** [comment]
> I think this might work?
> 
> ```
> devtools(proxy({ tripsProxyStore, appHostProxyStore }),'My Store') 
> // it should still tack correctly on Chrome REdux Tools
> ```

Yes! This should work and this is how we combine proxies in valtio. This is the way that works not only for devtools, but in general.

**Comment by dai-shi** [comment]
> It would be great also if devtools allowed for some middleware function

Would you be able to explain what is middleware for devtools?

https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md
I can't find anything extensible in the api...

**Comment by rmcarias** [comment]
@dai-shi  I apologize, I meant when creating the proxies (sort of how when you create store with Redux, pass in a middleware (or set of middlewares).

**Comment by dai-shi** [comment]
Ah, I see. proxy is a self-aware object, and it fits well with composition rather than middlewares. Middleware is too tough to type correctly in general, so we prefer composition.

So, what you found is the **right** solution in valtio:
```js
devtools(proxy([proxy1, proxy2]), 'My GlobalStore')
```

This is a doc issue. But, it's not only for devtools. There should be some description about the general concept, and then some real use cases. I think I'd start creating a wiki page for the general one.

**Comment by dai-shi** [comment]
https://github.com/pmndrs/valtio/wiki/How-to-split-and-compose-states
With this I will close this issue, but feel free to share some further concerns and questions.
