### ISSUE TITLE
[devtools] Time travelling support

### ISSUE THREAD

**Issue by Aslemammad** [pmndrs/valtio#238]
Redux supports time travelling in the redux devtools! I think valtio and other libraries also have the potential to support that feature.

**Comment by italodeandra** [comment]
@dai-shi Implemented something similar on code (not on devtools).

```js
const proxyWithHistory = (initialValue) => {
  const p = proxy({})
  const history = []
  let index = -1
  let wip
  const undo = () => {
    if (index > 0) {
      p.value = wip = history[--index]
    }
  }
  const redo = () => {
    if (index < history.length - 1) {
      p.value = wip = history[++index]
    }
  }
  subscribe(p, (ops) => {
    if (ops.some((op) => op[1][0] === 'value' && (op[0] !== 'set' || op[2] !== wip))) {
      history.splice(index + 1)
      history.push(snapshot(p).value)
      ++index
    }
  }
  p.undo = undo
  p.redo = redo
  p.value = initialValue
  return p
}
```

https://github.com/pmndrs/valtio/issues/89#issuecomment-881799275

It is very simple and straight forward. But as for adding it to the devtools I have to idea lol.

**Comment by dai-shi** [comment]
I think this issue is about https://github.com/zalmoxisus/redux-devtools-extension 's time travelling feature.

**Comment by dai-shi** [comment]
Now, we have a better understanding with the work in jotai, @Aslemammad can start working on this.

**Comment by Aslemammad** [comment]
This is supported, let's close it!
