### ISSUE TITLE
Update README.md documentation

### ISSUE THREAD

**Issue by Sylvenas** [pmndrs/valtio#242]
From the source code, the third parameter of `subscribe` is `notifyInSync?: boolean`, but the [documentation](https://github.com/pmndrs/valtio#subscribe-from-anywhere) looks like it's not passed as a `boolean`

**Comment by dai-shi** [comment]
Hi, nice catch. It actually works without passing a boolean.
It's internally provided for `{ sync: true }`, so it's intentionally not documented in the `subscribe` doc.

That said, I remember someone wanted to use `notifyInSync` in `subscribe`.
Is it the case with you too? If so, how would you explain the feature briefly? Or, what is your use case?

**Comment by Sylvenas** [comment]
I don't have a scenario where I have to use `sync`, I just found this parameter while debugging the source code. I would like to ask, what is the purpose of adding this design?

**Comment by dai-shi** [comment]
The `sync` option is necessary, if you use your state for `<input>` value.
There might be other cases, but that's only the kind I'm aware of.
`notifyInSync` is an internal api to implement it.
Does that answer your question?

**Comment by Sylvenas** [comment]
Thanks for your answer, I think I have no more doubts, this issues can be closed.

**Comment by dai-shi** [comment]
Okay, let's close this.
Thanks for your interest and suggestion anyway!
