### ISSUE TITLE
Subscribe to a portion of the state is not working on React Native

### ISSUE THREAD

**Issue by soflass** [pmndrs/valtio#250]
Hello,
Thanks for this great library.

I wanted to subscribe to a portion in the state but it is not firing in React Native.

I have a state as a proxy object
`const state = proxy({
  obj: {},
});`

_This does not fire (portion)_
`subscribe(state.obj, () => console.log('Fired'));` 

_This does fire (complete object)_
`subscribe(state, () => console.log('Fired'));` 

I reproduced the same code in a React JS application and it works fine both with the complete state and the portion one, but it is not working on React Native.

I tried Valtio for Vanilla JS in React Native but it is what I really want to achieve.

> Tested on an Android emulator in a Windows 10 Pro machine
> React Native 0.64.1 with Node v16.8.0

Thank you.

**Comment by soflass** [comment]
Hello,
I tried the code you gave me on both Chrome and React Native on Android and it worked on both.
Also I a code that I wrote
```
import React from 'react';
import { Button } from 'react-native';
let x = new Proxy(
  {},
  {
    set: (t, p, v) => {
      alert(JSON.stringify(t, p, v));
      t[p] = v;
    },
  },
);
const handleUpdate = async () => {
  if (x.num) {
    x.num = x.num + 1;
  } else {
    x.num = 1;
  }
};
const Cmp = () => {
  return <Button title="Update" onPress={handleUpdate} />;
};
export default Cmp;
```
And each time I press the button the value increments, please view the image below
![image](https://user-images.githubusercontent.com/84907233/136710792-7f58ced8-c9fd-4e88-9573-196e7091773b.png)

**Comment by dai-shi** [comment]
Thanks for the confirmation. Now, I'm lost...

> This sounds like Proxy is not fully supported in your env.

My assumption wasn't correct.

**Comment by dai-shi** [comment]
https://snack.expo.dev/mG5w-plIf
Tested for your original issue. It works with my iPhone.
Can you test this with your Android?
