### ISSUE TITLE
Conditionally react to state updates

### ISSUE THREAD

**Issue by rcoopr** [pmndrs/valtio#258]
State can be read transiently or subscribed to, but is it possible to, for example, only react to state updates while the component is on-screen?

**Comment by dai-shi** [comment]
Should be doable with custom subscription. How do you know if it's on-screen? It is in a ref?

**Comment by BeezBeez** [comment]
Hi ! Can we have a detailled explanation of why this happen ?
Thanks !

**Comment by Froskk** [comment]
I believe it was because proxies aren't created for primitive values, but it has been a while since I have used valtio and ultimately went with another solution for the issue I ran into
