### ISSUE TITLE
Is it possible to update Valtio state from redux devtools?

### ISSUE THREAD

**Issue by AshConnolly** [pmndrs/valtio#260]
Hi there! 👋 😄

I'm using Valtio with redux devtools so I can view my app state. Is there is a way to update state from the dev tools? 
With redux you would dispatch an action to update state. Is something like this possible with Valtio?

Thanks again for all the amazing state tools! 🚀

Edit:
I found this repo - https://github.com/oslabs-beta/deValtio . I tried it but it didn't work for me, presumably it's in development. A Valtio chrome extension would be amazing! 

Additionally I often wonder if people are hesitant to use state libraries that don't clearly show state in devtools. Like with context you can see and modify context state in the react devtools, which is nice.

I know valtio and zustand avoid any need for context which is great, but perhaps there could be an optional way of wrapping your app in some sort of valtio state-helper. So we could see and modify valtio state from the react devtools? 🤔 
I've not cracked open the valtio src so no idea if this is possible, just a thought! 😄

**Comment by dai-shi** [comment]
Thanks for opening the issue. AFAIK, "Jump" should work at least. Have you tried it?
Can you dispatch an arbitrary action with redux?
