### ISSUE TITLE
Question: Avoid rerenders when assigning the same data

### ISSUE THREAD

**Issue by somebody32** [pmndrs/valtio#263]
Is there a way to not trigger a state update when assigning the same data?

Use case: I have an array of objects/instances which is immutable, but I need to sync it with a valtio store on a regular basis. Now store gets updated on every sync even if there are no updates in reality.
So, basically, that code would trigger 2 updates:

```js
const dataObjects = [{ field: "a" }, { field: "b" }];
const state = proxy({ data: [] });

state.data = dataObjects
state.data = dataObjects
```

Here is a Codesandbox with a stripped-down example: https://codesandbox.io/s/little-surf-dlpxn

I can check for equality outside of valtio and do a conditional assigning to the store, but curious if there is a backed-in solution for this?

**Comment by dai-shi** [comment]
Closing as nothing is actionable as of now.
