### ISSUE TITLE
Problem with RTCPeerConnection

### ISSUE THREAD

**Issue by hypo-thesis** [pmndrs/valtio#265]
```
 pc = new RTCPeerConnection()
 pc.dcm = pc.createDataChannel("channel")

```
`Valtio `does not accept `dataChannel `as value and gives me `proxy{}` instead of the `channel`.

Why?

**Comment by dai-shi** [comment]
I'm not exactly sure how you use `proxy()`, but it basically deep-copies an initial object. PeerCoonection/DataChannel is probably not copy-able.
`ref()` is a solution for such cases.

**Comment by dai-shi** [comment]
Closing as answered. Feel free to add some comments.
