### ISSUE TITLE
Possible issue with Set support

### ISSUE THREAD

**Issue by pedroteixeira** [pmndrs/valtio#266]
Hello there, I was trying the following simple test case 

```
describe('valtio', () => {
    it('check valtio tracks Set', async () => {
        const obj = proxy({
            items: new Set()
        })

        let calls = 0

        subscribe(obj, () => {
            calls += 1
        })

        obj.items.add(1)

        await Promise.resolve()

        expect(calls).toBe(1)
    })
})
```

with:
valtio v1.2.5
node v14.17.3
jest v26.2.1

and it's current failing:
![image](https://user-images.githubusercontent.com/14740/139709333-225b2094-1021-4edb-8d8b-1ab303552c23.png)

Any hint what might be going on here?

thanks!

**Comment by dai-shi** [comment]
valtio doesn't proxify unsupported objects. basically, it only supports plain objects (= what Proxy API supports.)
Please use an array instead.

We can't throw errors for unsupported objects, for some other use cases.
The best I can think of is to add some docs, maybe in https://github.com/pmndrs/valtio/wiki/Some-gotchas.

**Comment by pedroteixeira** [comment]
ah, ok. From https://github.com/pmndrs/valtio/blob/main/tests/mapset.test.tsx I was under the impression Map and Sets were expected to be supported.

**Comment by AjaxSolutions** [comment]
fyi MobX supports Map and Set, but _valtio_ is a nice and light-weight alternative.

**Comment by dai-shi** [comment]
Oh, sorry for the confusion. That test is to ensure that Map/Set are "unsupported".
(btw, looking at the test again, I'm not sure if the "expect" is working as expected. Maybe not.)

**Comment by dai-shi** [comment]
> fyi MobX supports Map and Set, but _valtio_ is a nice and light-weight alternative.

And, immer does too.
fyi*2, here's my recent tweet: https://twitter.com/dai_shi/status/1454796295848087552

**Comment by pedroteixeira** [comment]
alright, thanks for the replies :)

**Comment by dai-shi** [comment]
We now have `proxySet` and `proxyMap` utils!
They emulate `Set` and `Map` behaviors, which should work for typical use cases.
Related discussion: https://github.com/pmndrs/valtio/discussions/114#discussioncomment-1982749
