### ISSUE TITLE
Valtio devtools in production

### ISSUE THREAD

**Issue by zouterover** [pmndrs/valtio#269]
Do I need to use an environment config condition to prevent valtio devtools to run in production or something?

**Comment by dai-shi** [comment]
Yeah, currently, it's developers' responsibility to conditionally enable devtools.

**Comment by zouterover** [comment]
Ok, cool. Thanks for great library!!

**Comment by zouterover** [comment]
By the way, this works it seems:
```
if (config.environment === 'dev') {
    import('valtio/utils')
        .then(utils => {
            const {devtools} = utils;
            devtools(state, 'state of my web-app')
        })
}
```
