### ISSUE TITLE
Warning: Rendering <Context.Consumer.Provider> is not supported

### ISSUE THREAD

**Issue by gitcatrat** [pmndrs/valtio#271]
```
Warning: Rendering <Context.Consumer.Provider> is not supported and will be removed
in a future major release. Did you mean to render <Context.Provider> instead?
```

Getting that warning here:

```js
const { layers } = (0,valtio__WEBPACK_IMPORTED_MODULE_3__.useSnapshot)<HERE>(_data_global_js__WEBPACK_IMPORTED_MODULE_1__.state);
```

Is it something I do or a bug? Warning disappears when I remove `layers.register(elRef.current);`.

```js
function Layer (props) {
  const {layers} = useSnapshot(state);
  const elRef =  useRef(null);
  
  useEffect(() => {
    layers.register(elRef.current);
     
    return () => {
      layers.deregister(elRef.current);
    };
  }, []);

  return <div ref={elRef} />;
}
```

```js
const state = proxy({
  layers: {
    list: [],
    register: (el) => {
      state.layers.list.push(el);
    },
    deregister: (el) => {
      // ...
    }
  }
});
```

**Comment by dai-shi** [comment]
I suppose you would need to use `ref()` somewhere. Maybe `ref(el)`, but not sure. Would you create a minimal codesandbox reproduction?

**Comment by dai-shi** [comment]
Well, valtio supports basically only plain objects and arrays.
The `el` is a DOM element, which is not supported. So, you need to use `ref()` to tell that it shouldn't be tracked. It's hard to distinguish if an object is supported, so we let developers opt-out explicitly.
https://github.com/pmndrs/valtio#holding-objects-in-state-without-tracking-them
