### ISSUE TITLE
ReferenceError: Cannot access 'state' before initialization (nextjs only)

### ISSUE THREAD

**Issue by thecherrie** [pmndrs/valtio#277]
No idea why this is happening but I have copied the code from this page: https://github.com/pmndrs/valtio/wiki/How-to-persist-states and have tried to implement it in my page function

```
import { state } from '../state/state'
import { useSnapshot } from 'valtio'
  const snap = useSnapshot(state)
  return (
    <>
      <h1>{snap.text}</h1>
      <button onClick={() => state.text="changed"}>click</button>
   </>)
```

Just receive the error of `ReferenceError: Cannot access 'state' before initialization`, doesn't happen when I hardcode the values in, only happens when I try to use `JSON.parse()` and retrieve values from a localStorage item.

**Comment by dai-shi** [comment]
Hi, I made a codesandbox. can you try with this?
https://codesandbox.io/s/quirky-architecture-ds3ji?file=/src/App.js

**Comment by thecherrie** [comment]
Doesn't appear to have fixed it, pretty much what I've been trying all this time. Might it be because I'm using NextJS?

**Comment by dai-shi** [comment]
Do you mean it works with codesandbox/cra, but not with nextjs?

**Comment by thecherrie** [comment]
> Do you mean it works with codesandbox/cra, but not with nextjs?

Yes

**Comment by dai-shi** [comment]
```js
import { proxy, subscribe } from 'valtio';

const getInitialState = () => {
  try {
    const s = JSON.parse(localStorage.getItem('foo'));
    if (s) return s;
  } catch (e) {}
  return { count: 0, text: 'hello' };
};

export const state = proxy(getInitialState());

subscribe(state, () => {
  localStorage.setItem('foo', JSON.stringify(state));
});
```
This seems working. (it shows hydration warning.)

https://stackblitz.com/edit/nextjs-afekbi?file=state.js

What's weird is I didn't see any Reference Errors.

**Comment by rvirani1** [comment]
I had the same error, but it turned out that somehow compilation was failing inside the function for a derived property and that wasn't bubbling up correctly as the error.

**Comment by dai-shi** [comment]
I think we need a repro for this. Will keep this open for a while.

**Comment by dai-shi** [comment]
Is #294 and this somehow related? Just curious.

**Comment by hee10k** [comment]
@thecherrie Hello, I experienced the same problem on nextjs. 
So I'm using the custom hook as below.
I hope it helps you.

```ts
// store.ts
import { useEffect } from "react";
import { proxy, subscribe, useSnapshot } from "valtio";

const initialConfig = {
  config1: "1970-01-01",
  config2: 1,
  config3: false,
  config4: 50,
};

export const config = proxy(initialConfig);

export const useInitializeConfig = () => {
  useEffect(() => {
    const lsConfig = JSON.parse(globalThis.localStorage.getItem("config"));

    for (const key of Object.keys(config)) {
      config[key] = lsConfig[key] || initialConfig[key];
    }
  }, []);

  useEffect(() => {
    return subscribe(config, () => {
      localStorage.setItem("config", JSON.stringify(config));
    });
  }, []);
};
```
It is used as below.
```ts
// _app.tsx
import { useInitializeConfig } from "store";

function MyApp({ Component, pageProps }) {
  useInitializeConfig();

  return <Component {...pageProps} />;
}
export default MyApp;
```
```ts
// App.tsx
import { config } from "store";
import { useSnapshot } from "valtio";

export const App = () => {
  const { config2 } = useSnapshot(config);

  return (
    <>
      {config2}
      <button onClick={() => (config.config2 += 1)}>+</button>
    </>
  );
};
```

**Comment by arkhamRejek** [comment]
what worked for me was waiting for the dom to be ready because I was trying to access local storage

```javascript
const [appReady, setAppReady] = useState(false)

useEffect(() => {
    setAppReady(true)
    state.foo = "bar"
}, [])
```

**Comment by dai-shi** [comment]
Closing as stale. Please feel free to open a new "discussion".

**Comment by irisHanb** [comment]
I have same error in vite project... 
I just want to give default value using import keyword from another file. ( that file is default value's group )
<img width="1634" alt="image" src="https://github.com/pmndrs/valtio/assets/5442673/639ef8be-1d1e-4d07-82fa-276bed4c978d">

**Comment by irisHanb** [comment]
> I have same error in vite ( react, typescript ) project... I just want to give default value using import keyword from another file. ( that file is default value's group ) <img alt="image" width="1634" src="https://private-user-images.githubusercontent.com/5442673/289788799-639ef8be-1d1e-4d07-82fa-276bed4c978d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzAzNDEsIm5iZiI6MTcwMjM3MDA0MSwicGF0aCI6Ii81NDQyNjczLzI4OTc4ODc5OS02MzllZjhiZS0xZDFlLTRkMDctODJmYS0yNzZiZWQ0Yzk3OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDgzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JiNDJjOWRiMmUzMzBhZjVkOWU3NmJhNmJlZTNhNjMyYzYxNWNjYWIxNDMwODg5M2MyYzlmZjVhZjMyZjA1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-WChUlj0UHzVxU8GfDJWdhmZOpOsPpkZpV0OjdEb0p4">

I solved... 
set appReady state to App( root app )  and subscribe that... ( ^^; )>
