### ISSUE TITLE
Should there be a useSubscribe?

### ISSUE THREAD

**Issue by Wombat42** [pmndrs/valtio#28]
I ran into a problem where I was doubling the number of subscriptions for a state. I naively subscribed like this:
```javascript
import React from "react";
import { proxy, useProxy, subscribe } from "valtio";

const state = proxy({ counter: 0, });

function BadSubscribeExample({value, onClick=()=>{} }) {
  console.log("rendering",value);
  subscribe(state, () => {
    console.log("State changed", state);
  });
  return (
    <>
      <button onClick={onClick}>
        Counter: {value}
      </button>
      <div>{value}</div>
    </>
  );
}

export default function App() {
  const snapshot = useProxy(state);
  return (
    <div className="App">
        <BadSubscribeExample value={snapshot.counter} onClick={() => ++state.counter}/>
        <BadSubscribeExample value={5}/>
    </div>
  );
}
```
This adds one subscription per render. 

It would round out the library if it came with a useSubscribe hook to avoid the basic mistake I made. I would be happy to write it if you think it would help.

Thanks!

**Comment by Aslemammad** [comment]
@Wombat42 Can you create a codesandbox? and why you don't use subscribe outside( because useProxy watches the changes inside the component)?

**Comment by Wombat42** [comment]
Here's a [link to codesandbox](https://codesandbox.io/s/valtio-test-8kzti?file=/src/App.js)
The example is contrived to demonstrate the goof. 

There's nothing to keep a person from writing code this way and there is no guidance saying not to subscribe from within a component.

**Comment by Aslemammad** [comment]
@Wombat42 Thanks for your codesandbox, I'll check it. @dai-shi What's your opinion?

**Comment by AjaxSolutions** [comment]
> Here's a [link to codesandbox](https://codesandbox.io/s/valtio-test-8kzti?file=/src/App.js)
> The example is contrived to demonstrate the goof.
> 
> There's nothing to keep a person from writing code this way and there is no guidance saying not to subscribe from within a component.

Other than for debugging, how else would it be useful using `observe` from within a component?

**Comment by Wombat42** [comment]
Say you have three separate controls for managing newsfeeds:

- The first assigns news sources
- The second assigns topics
- The third lists the news items returned by a query.

The first two components update a state. The third component subscribes to the snapshot changes and reruns a news list query on an interval or as a result of the configuration change. The newsfeed list component _could_ subscribe to the snapshot and listen for changes and then rerun the news list query. 

Note, the newsfeed configuration could change as a result of something other than user interaction, like it may be getting refreshed via an API through some other component at intervals. Those state changes should get announced through the subscribe too.

While the approach is debatable, a widely used library will be applied to many scenarios in unexpected ways. Those "unexpected" ways may not be preferred, but they still work.

**Comment by dai-shi** [comment]
Hi,
subscription in react lifecycle is a valid use case for a certain purpose, and `subscribe` is designed for it.

```js
useEffect(() => {
  const unsubscribe = subscribe(state, () => ...)
  return unsubscribe
}, [state])
```

This should be a documentation issue. I don't think the lib needs to export a new function, given that one of the lib goals is to provide small API surface.

I think it's time for us to create `docs` folder for tips like this.

**Comment by drcmda** [comment]
it can be a one liner even:

```jsx
useEffect(() => subscribe(state, () => ...), [state])
```

**Comment by Wombat42** [comment]
Yep, no worries. Documentation is the best place to start. Thanks!
