### ISSUE TITLE
Support websockets/listeners/subscriptions in `derive`

### ISSUE THREAD

**Issue by gustavopch** [pmndrs/valtio#282]
I'm using Firebase to listen to some data in real-time. First, I have a listener for auth state. When the auth state changes, I need to subscribe to or unsubscribe from user profile. A contrived example with `useEffect` would be like this:

```js
const App = () => {
  // Main state
  const [authState, setAuthState] = React.useState(null)

  React.useEffect(() => {
    return firebase
      .auth()
      .onAuthStateChanged(authState => setAuthState(authState))
  }, [])

  // Derived state
  const [profile, setProfile] = React.useState(null)

  React.useEffect(() => {
    if (!authState) {
      setProfile(null)
      return
    }

    return firebase
      .firestore()
      .collection('profiles')
      .doc(authState.uid)
      .onSnapshot(snap => setProfile(snap.data()))
  }, [authState])

  // ...
}
```

I know I can currently use `subscribe` to achieve the same result, but it's not very ergonomic. That way, instead of just returning the unsubscribe function, I have to handle the removal of old listeners by myself.

I wonder if `derive` can be adapted to allow the behavior of the second `useEffect` seen above:

```js
derive({
  profile: (get, set) => {
    const authState = get(authState)

    if (!authState) {
      set(null)
      return
    }

    return firebase
      .firestore()
      .collection('profiles')
      .doc(authState.uid)
      .onSnapshot(snap => set(snap.data()))
  }
}, { proxy: store })
```

Or maybe there's already some way to accomplish that and I'm not seeing.

**Comment by dai-shi** [comment]
I'd say it's beyond the scope of `derive`. And, in such a case, `subscribe` is the right solution.

```js
const attachReactiveProperty = (baseObject, fn, targetObject, propertyName) => {
  let cleanup
  const unsub = subscribe(baseObject, () => {
    cleanup?.()
    cleanup = fn(snapshot(baseObject), (value) => {
      targetObject[propertyName] = value
    })
  })
  return () => {
    cleanup?.()
    unsub()
  }
}

attachReactiveProperty(authState, (stateSnap, set) => {
  if (!stateSnap) {
    set(null)
    return
  }

  return firebase
    .firestore()
    .collection('profiles')
    .doc(stateSnap.uid)
    .onSnapshot(snap => set(snap.data()))
}, store, 'profile')
```

**Comment by gustavopch** [comment]
Hey @dai-shi, that's a good solution, thanks.

Other than that, I just realized Svelte's `derived` seems to work like what I proposed, look: https://svelte.dev/docs#derived

```js
import { derived } from 'svelte/store';

const tick = derived(frequency, ($frequency, set) => {
	const interval = setInterval(() => {
	  set(Date.now());
	}, 1000 / $frequency);

	return () => {
		clearInterval(interval);
	};
}, 'one moment...');
```

Maybe that inspires you to bring the same behavior to Valtio as it shares a lot of concepts with Svelte. So I'm closing the issue for now based on your last comment. If you change your mind, then you can reopen it.

**Comment by dai-shi** [comment]
We prefer small API surfaces. Our `derive` implementation is already pretty complicated.
It happened Svelte's `derived` sounds similar, but my perspective is it's a different util.

At this point, we don't to plan to add such a util, but I might change my mind in the future, if people shows more various use cases. Until then, I feel like this is an opportunity for third-party libraries.

Please also check `watch` util, if you haven't.
