### ISSUE TITLE
10x slower when dev console is open

### ISSUE THREAD

**Issue by pedroteixeira** [pmndrs/valtio#284]
I'm investigating why there's some extra overhead when the console (in Chrome) is open.
That's even when not using `devtools( )` to connect to the redux extension.

I see the issue in a real application with a few watchers and an use case where there are thousand of updates at once (trying out to use valtio in place of a custom store). 

Here's an attempt to create a reproducible case: https://jsfiddle.net/pedroteixeira/62c1xbnd/15/

Just run with the console closed and then run with it open (you'll be able to see the previous run log in the console). 

What I observe:

- When console is not open: it takes less than 20ms 
- When console is open, it takes 10x more than that to complete (~200ms)
- Changing test to run 350k updates (instead of 35k) keeps ~10x difference 

Any hints what might be causing this overhead? Not sure if there exists debug-related settings for proxies (for ex). Researching here. Any help is appreciated. Thanks in advance.

**Comment by pedroteixeira** [comment]
While debugging, I see the `ops` array with many thousands in the `subscribe` (in `vanilla.ts`) for the same property.  
Do listeners need receive the list of all operations? Perhaps there's some optimization that can be done here.

**Comment by dai-shi** [comment]
Thanks for reporting. Great to see you did dig into it.
It looks like the batching is slow.

```js
subscribe(state, () => {})
```
shows 10x difference, but

```js
subscribe(state, () => {}, true)
```
doesn't.

I will create a PR to support `{ sync: true }` option in `watch`, as well as trying to improve batching.

**Comment by dai-shi** [comment]
Can you try #286? I don't know how to try it with jsfiddle...

**Comment by pedroteixeira** [comment]
great, it worked! didn't see that overhead anymore

was able to import the branch in codesandbox:
https://codesandbox.io/s/react-typescript-forked-lhh89?file=/src/index.tsx
