### ISSUE TITLE
hot reloading crashes

### ISSUE THREAD

**Issue by mapsgeek** [pmndrs/valtio#294]
I've a basic valtio/Nextjs setup but i don't initialize any stores until the app is loaded and only client side operations
so i don't think it's an issue of SSR but HMR crashes the tab on chrome and firefox very frequently while working and it stops
when i remove the components which use valtio.

i honestly didn't try to make a reproducing sandbox since codesandbox has its own issues with hot reloading itself or not ideal
to show that in my opinion.
Have anyone came across this issue or have a fix for it?
i tried to disable redux devtools, reduce the amount of data loaded to proxy.. nothing really worked.

**Comment by dai-shi** [comment]
maybe a github repo for reproduction? is it nextjs specific or can CRA repro the issue?

**Comment by dsacramone** [comment]
> I've a basic valtio/Nextjs setup but i don't initialize any stores until the app is loaded and only client side operations so i don't think it's an issue of SSR but HMR crashes the tab on chrome and firefox very frequently while working and it stops when i remove the components which use valtio.
> 
> i honestly didn't try to make a reproducing sandbox since codesandbox has its own issues with hot reloading itself or not ideal to show that in my opinion. Have anyone came across this issue or have a fix for it? i tried to disable redux devtools, reduce the amount of data loaded to proxy.. nothing really worked.

Did you solve this?

**Comment by mapsgeek** [comment]
@dai-shi No, making changes to a root or parent component makes the chrome tab to go in an infinite loop and i have to close it and reopen the tab which is tedious for rapid development.
I have no idea why but as i said this doesn't happen when i don't import components which use valtio so eventually i went with another state manager

**Comment by dai-shi** [comment]
Closing as stale.

**Comment by raptoria** [comment]
I had the same problem, using vite and React, HMR would randomly crash. I tried to "split the state" into different files but saving a file would cause the Valtio state to reset.
