### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by nc** [pmndrs/valtio#297]
Has anyone built anything to validate data written to a valtio store? I am wondering if a `validate` function passed to `proxy` would be helpful if called on any `set` operations. If data is invalid call either reject it or call a `onInvalid` callback.

**Comment by dai-shi** [comment]
Let's assume a proxy object is a normal object. How would you do with a normal object? Maybe create a custom set function, or wrap with another proxy.
```js
const state = { positiveNumber: 1 }
const stateWithValidation = new Proxy(state, {
  set(target, prop, value) {
    if (prop === 'positiveNumber' && value <= 0) {
      throw new Error('invalid')
    }
    target[prop] = value
  }
})
```

**Comment by nc** [comment]
passing a custom set function to proxy() would be nice, then you can decide if you want to do a validation or transformation with it.

**Comment by dai-shi** [comment]
I think it has been raised at least once in some issues. It's understandable, but we prefer composition than extending the core. In general, adding a feature requires adding a doc, which users have to read and learn. I may think exposing custom equality function instead of Object.is which allows some hacks, hmm but not sure it's worth it. I wonder if there's a fancy solution with `receiver`. 🤔 (which may not solve the doc issue, though)

**Comment by nc** [comment]
the problem i'm trying to solve is preventing bad data from entering the store, as once it's there it's likely to cause issues within react components

a composition based approach to solving this would be great

**Comment by dai-shi** [comment]
i'm learning the proxy api again and reflect api.

meanwhile, would you try if this approach works?
```js
const baseState = proxy({ positiveNumber: 1 })
export const state = new Proxy(baseState, {
  set(target, prop, value) {
    if (prop === 'positiveNumber' && value <= 0) {
      throw new Error('invalid')
    }
    target[prop] = value
  }
})
```

It's really JS and how proxies work. Only minor concern might be double proxies, but I don't think the overhead is noticeable.

**Comment by dai-shi** [comment]
@nc Would you like to experiment with #298?

**Comment by dai-shi** [comment]
Closing as stale. #298 is merged. So, please open a new discussion for usage, or a new issue for bugs.

**Comment by overthemike** [comment]
Just released this: https://github.com/valtiojs/valtio-zod/

**Comment by dai-shi** [comment]
To follow-up, #298 is replaced by #528, which is replaced by #931.
