### ISSUE TITLE
How does this differ from useState?

### ISSUE THREAD

**Issue by aesign** [pmndrs/valtio#3]

**Comment by dai-shi** [comment]
Hey, would you elaborate the question? It's hard to tell which level of answer is expected.

**Comment by AjaxSolutions** [comment]
@dai-shi I wish there was an example showing how to use it with promises.

Also, I found this interesting:

https://twitter.com/0xca0a/status/1328977410432397313

**Comment by aesign** [comment]
@dai-shi Well, that's actually the question. Ehm, why should I use your solution instead of React's useState? Which are the advantages?

**Comment by jherr** [comment]
The example code is shown in a single file to make it easier to communicate and reason about. But in reality the `globalState` would be in a separate file and parts and pieces of that global state would be used by components in different sections of the React tree.

There are two ways you could do this with `useState`. You could prop-drill the state and the setters from a root component to the components that need them. But prop-drilling at scale is not awesome. Or you could couple your `useState` with `useContext`. Which avoids the prop-drilling, but whenever the state referenced in the context changes the entire React tree from that point down gets re-rendered.

Libraries like this one, or Zustand, Recoil, Jotai, (or even Redux/Mobx), mean that you can have global state that the components subscribe to and when it changes only those components are re-rendered. So you don't need prop-drilling, you don't need context, and your tree re-renders are faster because they are limited to updating only when the data they subscribe to changes.

**Comment by a-eid** [comment]
@dai-shi does it optimize rendering ?

**Comment by drcmda** [comment]
that's what snapshot is there for. it detects it by listening to the props you call, hence it know that component is only ganna react to count1 and the other to count2.

**Comment by jeremy-coleman** [comment]
To my knowledge, this is the first reactive state management lib that doesn't require a root provider or require you to wrap components to highjack the render (like mobx). It's so beautiful. This issue just makes me lol.

**Comment by cannikin** [comment]
> this is the first reactive state management lib that doesn't require a root provider or require you to wrap components to highjack the render

Recoil?

**Comment by jherr** [comment]
@cannikin Recoil needs a RecoilRoot tag. Jotai needs a Provider. MobX needs observers. This one uses hooks, which is definitely more React circa 2020.

**Comment by cannikin** [comment]
Ahhhh forgot about `<RecoilRoot>`, you're right!

**Comment by jherr** [comment]
> Ahhhh forgot about `<RecoilRoot>`, you're right!

Easy to forget. You drop it in once and you're good.

**Comment by dai-shi** [comment]
> @dai-shi I wish there was an example showing how to use it with promises.

Does https://twitter.com/0xca0a/status/1329023210768265216 help?

> Also, I found this interesting:
> https://twitter.com/0xca0a/status/1328977410432397313

Yeah, having actions separately doesn't harm at all.

----
I haven't tried, but this might work.
```js
const state = proxy({
  count: 0,
  inc: () => ++state.count,
})
```

This might be better in performance.
```js
const state = proxy({
  count: 0,
  actions: {
    inc: () => ++state.count,
  },
})
```

This is best in terms of performance.
```js
const state = proxy({
  count: 0,
})
const actions = {
  inc: () => ++state.count,
}
```

The peformance mentioned is theoretical. We can't say for sure about practical performance without measuring.

**Comment by dai-shi** [comment]
> @dai-shi Well, that's actually the question. Ehm, why should I use your solution instead of React's useState? Which are the advantages?

If useState works in your use case, that's preferable.
Like @jherr said, useState + prop drilling is the first option.
Only for the cases it doesn't work, we consider global state.

There's many options and valtio is one of them.

**Comment by dai-shi** [comment]
> somehow it detects that which is just magic to me.

Yeah, it's like magic. I've been pushing this for two years now...

I started with react redux binding and then react-tracked... https://twitter.com/dai_shi/status/1328994044765081600

**Comment by dai-shi** [comment]
> To my knowledge, this is the first reactive state management lib that doesn't require a root provider

What I built and involved in this type of libs are:
- react-hooks-global-state
- zustand
- and voltio

But, one could make it pretty easily with use-subscription, and once React finalizes useMutableSoure, this pattern will be more popular.

**Comment by AjaxSolutions** [comment]
I recommend watching this video by Jack Herrington.

"Introducing Valtio - Short Subject"

https://www.youtube.com/watch?v=XnlECbwcJZ0&t=141s

**Comment by dai-shi** [comment]
That's a wonderful video. Nice work! 👏  @jherr 

----
I just want to make a small clarification.
Having a function in a proxy is totally fine.
```js
const state = proxy({
  counts: [1, 2, 3],
  sum: () => state.counts.reduce((p, c) => p + c),
})
```
You could even do object getters (TIL).
```js
const state = proxy({
  counts: [1, 2, 3],
  get sum() { return state.counts.reduce((p, c) => p + c) },
})
```
However, this essentially means like this.
```js
const state = proxy({
  counts: [1, 2, 3],
})
const sum = () => state.counts.reduce((p, c) => p + c)
```
So, two notes:
1. It will re-compute the function every time `sum()` is called.
2. This is not reading a snapshot, so even if `sum()` is called in a React component, it's not reactive.

As long as this is understood, the use case is totally valid.

Having that said, the alternative way is something like this.
```js
const state = proxy({
  counts: [1, 2, 3],
  sum: 6,
})
subscribe(state.counts, () => {
  state.sum = state.counts.reduce((p, c) => p + c)
})
```
Note we can't subscribe to `state` itself, as it causes an infinite loop. (a new discussion in #13.)

We need more docs around these kinds of patterns, once after we figured out various use cases.
Until then, please try and come up with ideas!

**Comment by dai-shi** [comment]
https://twitter.com/dai_shi/status/1331904815396311043
v0.4.2 is released and things are changed a bit from my previous comment.

Now, we can use `this` to access a snapshot.
```js
const state = proxy({
  counts: [1, 2, 3],
  text: 'hello',
  sum() { return this.counts.reduce((p, c) => p + c) },
})
```
This will work pretty nicely. Using `snapshot.sum()` is reactive and render optimized.
Note this is not computed, if you call `sum()`, it will re-evaluate. But as it's render-optimized, only when required, `sum()` is called.

You could use class syntax to use getters. Object getters work too, but not reactive.
Oh, I just noticed object getters are computed. So, both have good use cases. (This is very hard to explain. We might change the behavior based on feedbacks.)

For more discussion, refer #27 and #29.

**Comment by AjaxSolutions** [comment]
This is a very interesting article especially the two sandboxes comparing valtio and MobX.

[Valtio — The Most Minimal Proxy State Possible in React](https://medium.com/better-programming/valtio-the-most-minimal-proxy-state-possible-in-react-764a67ba4833)

**Comment by tomByrer** [comment]
> https://www.youtube.com/watch?v=XnlECbwcJZ0&t=141s

Has the best summery IMHO
![image](https://user-images.githubusercontent.com/1308419/102205112-565bc680-3e90-11eb-9a71-637b973955dc.png)

**Comment by Kaijun** [comment]
> @cannikin Recoil needs a RecoilRoot tag. Jotai needs a Provider. MobX needs observers. This one uses hooks, which is definitely more React circa 2020.

since `observer` component in mobx can't take advantage of suspense, is valtio compatible with react suspence?

**Comment by Aslemammad** [comment]
@Kaijun It's pretty great with react suspense, @dai-shi tweeted a codesandbox about that, [here](https://codesandbox.io/s/valtio-async-demo-r4y2l?file=/src/App.js).

**Comment by dai-shi** [comment]
Hope the original questions is already answered. If someone has a question, please open a new issue or a discussion.
