### ISSUE TITLE
State is not reset after transition in next/link

### ISSUE THREAD

**Issue by locona** [pmndrs/valtio#306]
**Summary**
State is not reset after transition in next/link.

**Example**

An example with the following state.

1. In page A, change open=true.
2. Then, with Link(next/link), it moves to PageB.

The open state of the state after the transition remains true.
Is there any way to do that?
thanks.

```
// pages:
// * page A
// * page B

export const state = proxy({
  open: false,
  handleOpen: () => state.open = true,
  handleClose: () => state.open = false,
})
```

**Environment**
* nextjs: v12.0.7
* valtio: 1.2.7

**Comment by locona** [comment]
In jotai, you can do the following

https://jotai.org/docs/guides/nextjs#sync-with-router

**Comment by dai-shi** [comment]
It is how module state works, which applies to valtio and zustand.
As a workaround, you want to use context and create state in a component (per page in nextjs): https://github.com/pmndrs/valtio/wiki/How-to-use-with-context

**Comment by locona** [comment]
Thank you.

It's resolved.

**Comment by dsacramone** [comment]
> Thank you.
> 
> It's resolved.

How did you solve it? With the "context" solution or another?

**Comment by bernatfortet** [comment]
@locona @dai-shi It would be amazing to document an example for nextjs 🙏
