### ISSUE TITLE
[FeatureRequest] Support Transaction

### ISSUE THREAD

**Issue by xialvjun** [pmndrs/valtio#328]
Hope for api like this:

```js
import { proxy, transaction } from 'valtio';

const state = proxy({ count: 0, list: [] });

// sorry for such a stupid example
transaction(async () => {
  state.count = 0;
  state.list = await apis.getList();
  state.count = state.list.length;
});
// when the transaction function throws, nothing change
```

**Comment by dai-shi** [comment]
I first thought about batching, but this is more about rollback, right?

I mean:
> when the transaction function throws, nothing change

is something you really want.

Hm, I guess rollback is extremely difficult, and impossible in an ideal way.
I think what's possible and fairly predictable is to work on a copy.

```js
const transaction = (state, callback) => {
  const draft = Object.assign({}, draft) // no array support
  Promise.resolve(callback(draft)).then(() => {
    Object.assign(state, draft)
  })
}

// usage
transaction(state, async (draft) => {
  draft.count = 0;
  draft.list = await apis.getList();
  draft.count = draft.list.length;
});
```

Something like that? This doesn't work for nested proxy objects. Full support will require more effort.

**Comment by xialvjun** [comment]
Yeah, I like this way.  Besides, I'm worried about concurrent transaction.

```js
transaction(state, async draft => {
  await apis.one();
  xxx(draft);
});

transaction(state, async draft => {
  await apis.two();
  xxx(draft);
});
```

The two draft are all the old state. But I thought it's OK for front-end. We use transaction in error-prone functions rather than concurrent logic, we take the order ourselves. Besides, transaction should return a Promise.

**Comment by dai-shi** [comment]
Do you want flow control to run transaction one by one?
Would you like to reject a promise when a transaction throws?
Do you want to support nested proxies even if it's costly?

At this point, I feel like solving everything is too much for the official library utils,
so they would be good for recipes in docs.
Alternatively, someone is welcome to work on a third-party library.

**Comment by xialvjun** [comment]
I just think simple override in concurrent transaction is enough (no matter which transaction begins first).
And I think transaction return Promise is enough two (complex flow control is not needed. Returning a promise is just giving a possibility to the user to achieve their own flow control).
Nothing else.

**Comment by dai-shi** [comment]
Okay, so that bring us to this:
```js
const transaction = (state, callback) => {
  const draft = Object.assign({}, draft) // this only supports shallow object (non-array)
  return Promise.resolve(callback(draft)).then(() => {
    Object.assign(state, draft)
  })
}
```
---
I have been thinking about how to deal with deep nested objects. We could deep copy, but it's not efficient. We could wrap extra proxies and track mutation on draft, but then it's probably re-inventing immer. So, if one really needs it, they can try using immer in the `transaction` impl.

All that said, it would be easier for most valtio users to, instead of using `transaction`, prepare all data, await them, and apply them to the valtio state at once (not async).
