### ISSUE TITLE
derive: Type error for `null` in get function

### ISSUE THREAD

**Issue by hung-yueh** [pmndrs/valtio#329]
Here is my use case with Typescript:

```typescript
interface MyData {
    data1: null | MyData1;
    data2: null | MyData2;
}
const initialState: MyData = {
    data1: null,
    data2: null,
}
const store = proxy<MyData>(initialState)
const derivedStore = derive({
    derivedData1: (get) => get<null | MyData1>(store.data1)
                               ^^^^^^^^^^^^
                               Error: Type 'null' is not assignable to type 'object'
})
```

Should Valtio support `null` in the `get` function? or there are better ways/practices to this use case?

Thanks!

**Comment by dai-shi** [comment]
`get` has to take a proxy object, and `null` is not a valid object for proxy. (It doesn't work in JS).

If you can't make `data1` non-null, the solution is this:
```js
const derivedStore = derive({
  derivedData1: (get) => get(store).data1
})
```

**Comment by hung-yueh** [comment]
I see, thanks for the explanation. 
```javascript
const derivedStore = derive({
  derivedData1: (get) => get(store).data1
})
```
In this case, the `derivedStore` will re-compute when there is any change in the `store` right?

**Comment by dai-shi** [comment]
Yeah, that's right. So, I'd recommend to make `data1` non-null, if possible.

Like wrapping with extra objects:
```ts
interface MyData {
  data1: { value?: MyData1 }
  data2: { value?: MyData2 }
}
```

**Comment by hung-yueh** [comment]
Thanks for the info. Close the issue.

**Comment by dai-shi** [comment]
> How about if we only want derive to compute if a nested value changes? Is the reactivity fine grained?

No. It's out of the scope of `derive` util.

You could use other utils such as proxy-memoize, but in general you would only require it if there were a real performance problem:
https://github.com/pmndrs/valtio/blob/4f4404d32907e0c62c23738e8fb21c86d3743f16/docs/guides/computed-properties.mdx#L170-L190
