### ISSUE TITLE
[devtools] Trace support

### ISSUE THREAD

**Issue by BrianHung** [pmndrs/valtio#331]
One useful feature of redux devtools is [tracing](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/Features/Trace.md): it essentially gives you the stack trace of an action / mutation.

https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/Features/Trace.md

Note that the following does _not_ work. I naively tried modifying [`utils/devtools`](https://github.com/pmndrs/valtio/blob/main/src/utils/devtools.ts) and adding

```js
  const devtools = extension.connect({ name, trace: true })
```

but this does not work as it results in a trace in the same file of 

```
      devtools.send(
        {
          type: action,
          updatedAt: new Date().toLocaleString(),
        },
        snapWithoutDevtools
      )
```

**Comment by dai-shi** [comment]
Let's reopen once https://github.com/reduxjs/redux-devtools/pull/1369 is published.
