### ISSUE TITLE
[devtools]: only part of the state is showing

### ISSUE THREAD

**Issue by cubocicloide** [pmndrs/valtio#332]
Dear colleagues,
I am experimenting your libraries to understand if we can use it in my next projects. It looks promising. However, there seems to be an issue with the devtools.
First and foremost, this is my proxy:

```
import { proxy } from "valtio";
import { devtools } from "valtio/utils";
import { _getTodos } from "../utils/api";

const todos = proxy({
  items: [],
  count: 0,
  loading: false,
  filters: {
    page: 1,
    page_size: 10,
  },
  get: async () => {
    todos.loading = true;
    const data = await _getTodos({params: todos.filters});
    todos.items = data.results;
    todos.count = data.count;
    todos.loading = false;
  },
});

devtools(todos, "Todos");

export default todos;
```

And this is an pseudocode of a component which is using the above proxy:

```
...
import { useSnapshot } from "valtio";
import todos from "../../proxies";

const Todos = () => {
  const { items, count, loading, filters } = useSnapshot(todos);

  useEffect(() => {
    todos.get();
  }, [filters]);

  const handleChange = (pagination, controls, sorter) => {
    todos.filters = pagination;
  };

  return (
    <Table data={items} onChange={handleChange} loading={loading}, count={count} />
  )

}
```

Now, I have registered the todos proxy with devtools, however, instead of getting all of its properties, I am able to see only its items (i.e., count, loading, filters are not shown). Following a screenshot:

![Screenshot 2022-01-20 at 17 34 59](https://user-images.githubusercontent.com/20613071/150381815-dce4d206-ed31-4149-b423-13a0edbebd9c.png)

Can you please tell me how can I get the entire state in the devtools.

**Comment by dai-shi** [comment]
@Aslemammad Can you look into this?

@cubocicloide Thanks for reporting. If you can provide us a minimal reproduction with codesandbox, that will help us.

**Comment by cubocicloide** [comment]
@dai-shi @Aslemammad I was able to fix the issue after removing the action from the proxy definition.
