### ISSUE TITLE
[Umbrella] Improve tests

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/valtio#34]
I'd admit the current `tests` might not cover all use cases.
To make the library more stable for the future, adding tests would be great.
That would also clarify what is supported, and what is not supported but works for now.

**Comment by Aslemammad** [comment]
Can you highlight the files that need to get improved?

**Comment by dai-shi** [comment]
@Aslemammad I would say, basic.test.tsx, async.test.tsx, class.test.tsx and mapset.test.tsx. 😓 
You can create a new file or files, with totally new test design.

**Comment by Aslemammad** [comment]
@dai-shi I'll take a look, thanks for the issue.

**Comment by dai-shi** [comment]
@Aslemammad you are not working on this issue for now, are you? just confirming.

**Comment by Aslemammad** [comment]
I improved some tests and sent some PRs before, and they got merged too. But for now, no, I'm not working on them.

**Comment by Aslemammad** [comment]
No, actually, I'm not working.

**Comment by dai-shi** [comment]
There's still room for improvement, but this umbrella issue is not very easy to contribute.
We may need to create smaller issues so that new comers can work on them more easily.
