### ISSUE TITLE
Clean up ref object in refSet

### ISSUE THREAD

**Issue by namnm** [pmndrs/valtio#353]
Hi, as I view in the code from https://github.com/pmndrs/valtio/blob/main/src/vanilla.ts
I dont see anywhere that we clean up the ref object in the refSet
For eg:
```js
const state = proxy({
  node: ref(document.querySelector('.class1')),
})
// does it clean up .class1 dom node before assigning this new value?
state.node = ref(document.querySelector('.class2'))
```
Is this considered as a memory leak?

**Comment by dai-shi** [comment]
refSet is WeakMap, so it should be fine.

Thanks for reading the code!

**Comment by namnm** [comment]
@dai-shi Thanks for answering, just one more question on this specific case:
I understand that the purpose of ref is not tracking the nested properties of that object. But I wonder if the above `node` property trigger update event if I change it as above:
```js
state.node = ref(document.querySelector('.class2'))
```

**Comment by dai-shi** [comment]
Yeah, I think it does. Please give it a try.
