### ISSUE TITLE
Can proxy be durable to a hot reload?

### ISSUE THREAD

**Issue by Wombat42** [pmndrs/valtio#36]
Hi,

Several of the examples, like [Valtio Tic Tac](https://codesandbox.io/s/valtio-tic-tac-j0nut?file=/src/index.js), work fine until you make an edit to the file that makes the call to `proxy`. The state is lost and everything resets.

Try going to the above link and clicking a couple of times on the board. Then change any of the strings in the game's source. The game reloads and all the state information is lost. Obviously calling proxy again will cause everything to be reset, which is what will happen when hot reloading reloads the file.

I worked around the issue in my own project by just moving the state and call to proxy to a different file. [Valtio drag-and-drop](https://codesandbox.io/s/valtio-drag-and-drap-o025t?file=/src/globalcontext.js)

You can drag around some objects and see their state updates. You can modify any of the sources except `globalcontext.js` and you won't lose state information. But just like in the other example, if you modify `globalcontext.js` then all your state information is lost.

Regular states produced by useState, useReducer, and createContext/useContext, are all able to retain their state information after a hot reload. Is there a way to do it with Valtio?

Thanks

**Comment by Aslemammad** [comment]
@Wombat42 Thanks for your reporting, we discussed this in discord I think( in jotai part). The reason why everything lost is that we use object reference and hot-reload can't keep the same object reference after every change.

**Comment by dai-shi** [comment]
We had some discussions in zustand too. Valtio as well as zustand is module state which lays outside react, and it's limited in terms of fast-refresh support. I'm not sure if there's any workaround other than splitting state files.

**Comment by thelinuxlich** [comment]
Isn't Vue model a bit similar?

**Comment by thelinuxlich** [comment]
I'm using Valtio with Vite bundler and not even HMR works

**Comment by dai-shi** [comment]
Never used vite bundler. Would you be able to create a small repro that we can try on our end?

**Comment by thelinuxlich** [comment]
FYI Vite works well with Valtio now

**Comment by dai-shi** [comment]
Let me close this issue. Basically, hot reload works as expected if state is defined in a different file.
Suggestions are welcome.
