### ISSUE TITLE
`Maximum call stack size exceeded` error when using valtio with classes and propery getters

### ISSUE THREAD

**Issue by la55u** [pmndrs/valtio#375]
Below is a reproduction of the error. Sorry I could not make it more minimal. To me it seems like valtio triggers a rerender of the components which uses the getters and that also triggers a rerender.. But maybe I'm missing something and it's completely unrelated? I'm not familiar with the valtio internals.

**Expected behaviour:**
Adding a new window actually ads the window without crashing.

**Actual behaviour:**
Adding a new window crashes the app.

**Reproduction:**
https://codesandbox.io/s/shy-mountain-ppow30?file=/src/models/index.ts

Any help would be appreciated. Thank you!

**Comment by dai-shi** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/490574/154822877-c01e389b-a984-4323-9c9c-84a909b8880b.png">
Hmm, I got this error before trying the reproduction... Maybe temporarily?

---

> `Maximum call stack size exceeded` error

@DennisSmolek Can you instantly guess what's going??

**Comment by la55u** [comment]
> Hmm, I got this error before trying the reproduction... 

That's probably just an issue with the CDN, you can uncomment the `<Environment/>` in App tsx and it should work.

**Comment by dai-shi** [comment]
> I simplified the reproduction example and removed Three, now it's plain react and valtio.

That's nice. Where can I find it?

**Comment by la55u** [comment]
> Where can I find it?
I updated the link in the original issue.

**Comment by dai-shi** [comment]
three seems gone, but there are still many files. Are garage, wall, and scene all required for reproduction?

**Comment by la55u** [comment]
> Are garage, wall, and scene all required for reproduction?

OK I managed to further cut down the example complexity by removing some unnecessary classes and components. It seems that the issue is not related to getters after all, the app still crashes without any. Could you check the link again?

**Comment by dai-shi** [comment]
Cool, thanks. It's still complex, but I managed to reproduce the bug in tests.
This looks like a DEV-only issue. (Off topic:  I found CRAv5 doesn't work for production build.)

I'll open a PR.

**Comment by dai-shi** [comment]
Released: https://github.com/pmndrs/valtio/releases/tag/v1.3.1
