### ISSUE TITLE
infinite loop with watch in sync mode

### ISSUE THREAD

**Issue by RikuVan** [pmndrs/valtio#382]
The example below works but might get surprising behaviour in that, I suppose because of batching, you get `Anonymous's session is expired" logged twice

```js
import {proxy} from 'valtio/vanilla'
import {watch} from 'valtio/utils'

const userState = proxy({ user: { name: 'Juuso' } })
const sessionState = proxy({expired: false})

watch((get) => {
  const expired = get(sessionState).expired
  const name = snapshot(get(userState)).user.name
  console.log(`${name}'s session is ${expired ? 'expired' : 'valid'}`)
})

sessionState.expired = true
userState.user.name = "Anonymous"
```

However, if you add {sync: true} as an option to watch, it seems to get stuck in an infinite loop.

**Comment by dai-shi** [comment]
Nice catch.
I hope we can fix this, given that I solved it for `derive` similarly.
Anyone wants to give it a try??

**Comment by dai-shi** [comment]
(Ah, it's a different problem from what I expected.)
