### ISSUE TITLE
Subscribing to portion of state throws error "Please use proxy object"

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/valtio#39]
The README states "You can access state outside of your components and subscribe to changes" and shows how you can subscribe to a portion of state:
```js
// Subscribe to a portion of state
subscribe(state.obj, () => console.log(`state.obj has changed to ${state.obj}`))
```

However, doing so throws an error, "Please use proxy object".

See a simple example of this here:
https://codesandbox.io/s/valtio-partial-subscribe-error-plkf3?file=/src/App.js

**Comment by dai-shi** [comment]
Hi, we can only subscribe to a proxy, which has to be an object. So, subscribing to a number property is not supported.
https://codesandbox.io/s/valtio-partial-subscribe-error-forked-bbq3m?file=/src/App.js
This works.

I will update the description in readme slightly.

**Comment by lightrow** [comment]
missing this feature (reaction/autorun equivalent) prevents this otherwise nice lib from becoming a viable MobX alternative. Why can useSnapshot track which properties are accessed, but subscribe/watch can only subscribe to entire objects? Could something be done about this?
