### ISSUE TITLE
'hasOwnProperty' on proxy object doesn't trigger a field access

### ISSUE THREAD

**Issue by jluxenberg** [pmndrs/valtio#392]
It seems that 'hasOwnProperty' called on a proxy object does not trigger a field access subscription.

Here's an example:
[valtio-test01.zip](https://github.com/pmndrs/valtio/files/8235551/valtio-test01.zip)

To run:
```
valtio-test01 $ yarn && yarn start
```

Here's a live demo of the issue:
https://valtio-has-own-property-subscription-issue.jaredluxenberg.repl.co

and a Replit if that's easier for you to access:
https://replit.com/@JaredLuxenberg/valtio-has-own-property-subscription-issue#index.jsx

**Comment by DennisSmolek** [comment]
Here is a running CSB for your code, a Codesandbox account is free and much easier to share around,
Plus I dont have to get all panicky with opening a random persons zip file..

https://codesandbox.io/s/valtio-issue-392-xild4d?file=/src/index.js

**Comment by dai-shi** [comment]
> https://codesandbox.io/s/valtio-issue-392-xild4d?file=/src/index.js

@DennisSmolek Thanks for the minimal repro.

@jluxenberg This is nice catch.

I didn't know [ownKeys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/ownKeys) handler doesn't trap `hasOwnProperty`.

According to https://stackoverflow.com/questions/40451694/use-es6-proxy-to-trap-object-hasownproperty, we need [getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/getOwnPropertyDescriptor) to trap it.
