### ISSUE TITLE
Expose an external subscribe

### ISSUE THREAD

**Issue by jherr** [pmndrs/valtio#4]
Can we add a way to expose the subscribe method so that non-React code can watch the state as well. E.g.:

```
const globalState = create({
  count: 0,
});

setInterval(() => {
  ++globalState.count;
}, 1000);

globalState.subscribe(({ count}) => {
  console.log(`Called when the count changes: ${count}`);
});
```

**Comment by drcmda** [comment]
it exists

```jsx
const state = proxy(...)
subscribe(state, () => console.log("state changed"))
subscribe(state.foo, () => console.log("state.foo changed"))
```

just needs to be added to the "docs" :-)

**Comment by jherr** [comment]
Ah, ok. This package is moving pretty fast. ;) I yarn'ed it last night at 0.0.1 and it looks like it's already at 0.2.1 and the API has changed a little.

Having looked at 0.2.1 from npm it looks like `subscribe` is `subscribeProxy`. So that's one thing for the docs.

And then a second thing is that `subscribeProxy(state, ...)` works but `subscribeProxy(state.count, ...)` doesn't. That's fine by me, but it's just good to know for the docs as well.

**Comment by jherr** [comment]
Nice job on this, BTW. Sorry I didn't say that from the outset. It's great to see all these new state managers coming out to fill the gap between useState and monolithic state.

**Comment by dai-shi** [comment]
@jherr 
> `but subscribeProxy(state.count, ...)` doesn't.

`subscribe(state.count, ...)` doesn't work, if `state.count` is a number. We can only deal with proxies (objects). PRs are welcome to improve the readme. 😉
