### ISSUE TITLE
valtio 1.5.0 unable to subscribe to portion of state in a React Component

### ISSUE THREAD

**Issue by LefanTan** [pmndrs/valtio#413]
Hi, I'm running nextjs and in a custom hook, I'm trying to subscribe to a global proxy state like follow:
```
export const queryState = proxy({
  quantity: 0,
  variant: {
    variantId: "01231asdf1",
    collections: [{ collectionId: "12" }, { collectionId: "45123" }],
  },
});
```
I could subscribe with `subscribe(queryState.variant, () => console.log('subscribe'))` just fine outside of a react component, but when the same code is ran in a react component, the follow error shows:
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'add')
> 32 | subscribe(queryState.variant, () => console.log("nice"));
                ^
``` 

No problem whatsoever when subscribing to the whole state

**Comment by dai-shi** [comment]
That sounds weird. Is it nextjs only issue? It would be nice if you can create a reproduction with codesandbox without nextjs.

**Comment by LefanTan** [comment]
Mistake on my part, my apologies
