### ISSUE TITLE
Compilation erros NextJS after forking issue #411 fix

### ISSUE THREAD

**Issue by sivadinesh1** [pmndrs/valtio#415]
Create new compile errors.
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
at Object.useSyncExternalStore (/Users/sivadinesh/Documents/products/2022/greenpot/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5051:11)
at useSyncExternalStore (/Users/sivadinesh/Documents/products/2022/greenpot/node_modules/react/cjs/react.development.js:1671:21)
at useSnapshot (file:///Users/sivadinesh/Documents/products/2022/greenpot/node_modules/valtio/esm/index.mjs:19:24)

**Comment by dai-shi** [comment]
Hi!
Can you try this?
https://ci.codesandbox.io/status/pmndrs/valtio/pr/416

**Comment by sivadinesh1** [comment]
> Hi! Can you try this? https://ci.codesandbox.io/status/pmndrs/valtio/pr/416

Yes it works.  Hope this fix reaches the main build soon. thanks.

**Comment by dai-shi** [comment]
Thanks for confirming. Reopening so that others can notice.

**Comment by neosa** [comment]
next 12.1.4
react 18.0.0
react-dom 18.0.0
valtio: ^1.5.1

Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.

Hello, I notice the same problem

**Comment by dai-shi** [comment]
Hi, I was preparing a new release.
Please try: https://www.npmjs.com/package/valtio/v/1.5.2

**Comment by neosa** [comment]
> Hi, I was preparing a new release. Please try: https://www.npmjs.com/package/valtio/v/1.5.2

Its OK now! Great job!

**Comment by neosa** [comment]
> Hi, I was preparing a new release. Please try: https://www.npmjs.com/package/valtio/v/1.5.2

The build is going, but now a new error

Unhandled Runtime Error
TypeError: destroy is not a function
