### ISSUE TITLE
subscribeKey with proxyMap?

### ISSUE THREAD

**Issue by mysterybear** [pmndrs/valtio#418]
Hi,

Just as in the title really... I'm trying out `proxyMap` and it'd be nice to have something like the `subscribeKey` utility that we have for regular proxy objects. Is there something I'm missing already? How would one subscribe to a particular key in a `proxyMap` currently?

**Comment by dai-shi** [comment]
You can do something like this on your end.

```js
const subscribeMapKey = (proxyMapObject, key, callback) => {
  let prev
  return subscribe(proxyMapObject, () => {
    const nextValue = proxyMapObject.get(key)
    if (!prev || prev.value !== nextValue) {
      prev = { value: nextValue }
      callback(nextValue)
    }
  })
}
```

**Comment by mysterybear** [comment]
Thanks @dai-shi 

I added some TS and didn't see the need for prev to be an object with a `value` key, like so:

```ts
export const subscribeMapKey = <K extends unknown, V extends unknown>(
  proxyMapObject: Map<K, V>,
  key: K,
  callback: (v: V | undefined) => void
) => {
  let prev: V | undefined
  return subscribe(proxyMapObject, () => {
    const nextValue = proxyMapObject.get(key)
    if (!prev || prev !== nextValue) {
      prev = nextValue
      callback(nextValue)
    }
  })
}
```

Is this okay or is there a real reason for having prev be like `{ value: V }`?

Just going to try re-factoring a horribly nested proxy object to be a proxy map and hoping it'll perform just as well, as the Map API is really nice from for DX :crossed_fingers:

**Comment by dai-shi** [comment]
> Is this okay or is there a real reason for having prev be like `{ value: V }`?

It's okay as long as `V` never becomes `undefined`.
