### ISSUE TITLE
Accessing property from File object causes Illegal Invocation type error

### ISSUE THREAD

**Issue by LefanTan** [pmndrs/valtio#430]
[Codesandbox Link](https://codesandbox.io/s/laughing-pasteur-crmpw8?file=/pages/index.tsx)

As from title, when I try to access a File object and it's property through a snapshot, I receive a Illegal Invocation type error, with the error pointing at `file.name`.

I was only able to replicate the error with a snap shot, but in my own project, this happened with just a regular proxy state too

**Comment by dai-shi** [comment]
`File` is not proxy-able, so you need to wrap with `ref()`.

It's better to keep the state.files reference, so it should be something like this:
```jsx
onChange={(e) => {
  state.files.splice(
    0,
    state.files.length,
    Array.from(e.currentTarget.files).map(ref),
  )
}}

// but this works too
onChange={(e) => {
  state.files = Array.from(e.currentTarget.files).map(ref)
}}

// and maybe this too, but not recommended
onChange={(e) => {
  state.files = ref(Array.from(e.currentTarget.files))
}}
```

**Comment by LefanTan** [comment]
I see, what's the reason why File is not proxy-able?

**Comment by dai-shi** [comment]
Maybe, it has native code? I'm not sure the precise reason.
Basically, plain objects are safe to proxy.

The error can be reproduced with `Proxy` without valtio:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/490574/163293317-3b08c248-fea8-4f2f-98ce-01468d1338bc.png">


Possibly related:
- https://stackoverflow.com/questions/42496414/illegal-invocation-error-using-es6-proxy-and-node-js
