### ISSUE TITLE
Change proxy's value but proxyWithComputed's computed value  doesn't change 

### ISSUE THREAD

**Issue by ahaoboy** [pmndrs/valtio#435]
https://stackblitz.com/edit/vitejs-vite-1zhh5q?file=src/App.tsx&terminal=dev

For updates correctly, I need to read data.length
```
const state: { data: string[]; filter: string } = {
  data: [],
  filter: '',
};
const store = proxyWithComputed(state, {
  todos(s) {
    // If access data.length, it works
    // if (!s.filter && s.data.length) return s.data;
    if (!s.filter) return s.data;
    return s.data.filter((i) => !i.includes(s.filter));
  },
});
```

**Comment by dai-shi** [comment]
Thanks for reporting. Looks like a bug that only happens with useSnapshot and computed object value.

**Comment by dai-shi** [comment]
Hi, would you try #436?
https://ci.codesandbox.io/status/pmndrs/valtio/pr/436
Find "Local Install Instruction" ☝️

**Comment by ahaoboy** [comment]
> Hi, would you try #436? https://ci.codesandbox.io/status/pmndrs/valtio/pr/436 Find "Local Install Instruction" ☝️

LGTM
