### ISSUE TITLE
Setting initial state property to undefined causes resulting proxy to drop the property

### ISSUE THREAD

**Issue by JarvisPrestidge** [pmndrs/valtio#439]
Optional type properties seem like they would be a fairly common requirement, but setting inital state to `undefined` causes the proxy to drop the property from it's internal state.

```ts
interface Store {
    a?: string;
}

const state = proxy<IState>({ a: undefined });

console.log(JSON.stringify(state));

// {}
```

This seems like an issue because a native js Proxy doesn't behave this way, instead keeping the undefined key and value in the target object.

This behaviour is also conflicting with the wiki page on persisting state using `JSON.stringify(state)` ( i.e. [wiki link](https://github.com/pmndrs/valtio/wiki/How-to-persist-states) )

```ts
const state = proxy(JSON.parse(localStorage.getItem('foo')) || {
  count: 0,
  text: 'hello',
})

subscribe(state, () => {
  localStorage.setItem('foo', JSON.stringify(state))
})
```

When I attempt to persist / hydrate to and from storage, I commonly have missing properties, and instead have started to use `null` in place of `undefined` as that stays in the proxy, which feels like an unnecessary gotcha.

All in all, this seems like unintended behavio,ur and just wanted to raise it <3

**Comment by dai-shi** [comment]
https://codesandbox.io/s/zen-glitter-4e8wt5?file=/src/App.js

Looks like an issue with `in`.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/490574/164122593-e7026539-6968-424e-b8f5-5e02ae95a191.png">

**Comment by dai-shi** [comment]
Fixed by #440.
https://codesandbox.io/s/react-forked-owy91n?file=/src/App.js

**Comment by JarvisPrestidge** [comment]
> Fixed by #440. https://codesandbox.io/s/react-forked-owy91n?file=/src/App.js

Thanks for the quick turn around on this! I see that code sandbox shows that `JSON.stringify` isn't serializing any undefined props, that still seems like an issue (well at least that was the core of this issue)

**Comment by dai-shi** [comment]
What do you mean?
undefined props don't seem to be serialized even without proxies.
```
$ node
Welcome to Node.js v14.18.0.
Type ".help" for more information.
> JSON.stringify({a:undefined})
'{}'
```

**Comment by JarvisPrestidge** [comment]
You're completely right 😅 sorry about that, I somehow remember doing tests and seeing undefined printed but that's just not part of the js spec so couldn't have happened. Ignore me 🙇🏻‍♂️
