### ISSUE TITLE
Questions about `subscribe` and issue with `valtio/utils` in NextJS

### ISSUE THREAD

**Issue by jon301** [pmndrs/valtio#44]
Hi there,
I've tried Valtio and love it so far :) Thanks guys for the amazing work!

I'm still not sure about the patterns so I'm asking here just to be sure about how to use the `subscribe()` function.
Do you confirm it works for objects but only if you mutate it, and not replace it ?
- replace (not working): https://codesandbox.io/s/xenodochial-grass-lx6m1?file=/src/App.tsx
- update (working): https://codesandbox.io/s/zen-bhaskara-35bpl?file=/src/App.tsx

I manage to make Valtio detect the replacement by using `subscribeKey`:
- https://codesandbox.io/s/happy-yalow-bxlev?file=/src/App.tsx

However, I get an error regarding the `valtio/utils` import when using the same code on Next.JS app:
```
Server Error
SyntaxError: Unexpected token {
```
- https://codesandbox.io/s/eager-aryabhata-j4uwq?file=/pages/index.js

Thanks for your help ❤️

**Comment by dai-shi** [comment]
`subscribe` works for a proxy state.

```js
let state = proxy({ a: 1 })
subscribe(state, () => console.log("state is changed, meaning a property is changed")

state = proxy({ b: 2 })
// this is a new proxy state and the previous subscription no longer works
```

So, for your use case:

```js
const state = proxy({ obj: {} })
subscribe(state, ...) // you need to subscribe to the state itself...
state.obj = { hello: 'world' } // to get notified the property change
```

`subscribeKey` is meant for primitive values (not objects/arrays), and not recommended for your use case. It may not work for `state.obj.hello = 'valtio'`.

To import utils in nextjs, you need:

```js
import { subscribeKey } from 'valtio/utils.cjs'
```

This is a bit unfortunate, and I'd want some elegant solution, but for now this only works.

**Comment by jon301** [comment]
Thanks @dai-shi  for your answer!

> So, for your use case:
> 
> ```js
> const state = proxy({ obj: {} })
> subscribe(state, ...) // you need to subscribe to the state itself...
> state.obj = { hello: 'world' } // to get notified the property change
> ```

I tried to achieve the example we can see in the docs [here](https://github.com/pmndrs/valtio#subscribe-from-anywhere), or maybe it's not relevant anymore ?

```
// Subscribe to a portion of state
subscribe(state.obj, () => console.log('state.obj has changed to', state.obj))
```

**Comment by jon301** [comment]
Ok I've just see the unit test [here](https://github.com/pmndrs/valtio/blob/fdec8fa475e7ce26b02aed5b051ab5d5c40250c0/tests/subscribe.test.tsx#L29-L39)
It works if a property of the subscribed object has changed.

But when working with arrays (unfortunately my case) it's less convenient.
For example this won't work:
```
const state = proxy({ arr: ['hello', undefined, 'world'] });
subscribe(state.arr, ...);
state.arr = snapshot.arr.filter(value => value !== undefined);
```

**Comment by jon301** [comment]
Closing as `subscribe` works as expected.

**Comment by dai-shi** [comment]
> ```
> subscribe(state.arr, ...);
> state.arr = [];
> ```

Right, this doesn't work. Same as:

```js
let state = proxy({})
subscribe(state, ...)
state = proxy({}) // this is totally a new state
```

There might be a documentation issue. If anyone can had suggestion to readme (without making it too big), it would be nice.

**Comment by jon301** [comment]
> There might be a documentation issue. If anyone had suggestion to readme (without making it too big), it would be nice.

I've pushed a PR with some concise examples regarding `subscribe` usage.
https://github.com/pmndrs/valtio/pull/47
