### ISSUE TITLE
Can't use with stackblitz react-ts, Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ahaoboy** [pmndrs/valtio#448]
![image](https://user-images.githubusercontent.com/19884146/165508990-6ba60d2a-66ea-4f9c-994c-9bfeafadfee4.png)
![image](https://user-images.githubusercontent.com/19884146/165509562-a5b1fbbe-006e-41ae-ad39-85bc3e2ea54b.png)
```tsx
import React from 'react';
import { proxy, useSnapshot } from 'valtio';

const s = proxy({ c: 1 });
export default () => {
  const snap = useSnapshot(s);
  return <h1>c:{snap.c}</h1>;
};

```
demo:
https://stackblitz.com/edit/react-ts-fvyuom?file=Hello.tsx

**Comment by dai-shi** [comment]
Thanks for reporting!
This seems hard. zustand doesn't work as well. https://stackblitz.com/edit/react-ts-2nk5kt?file=Hello.tsx (The error message is `Unexpected token 'export'`.)

Wondering how Turbo works with ESM and "exports".
Assuming it doesn't read "exports", I did this: `import { proxy, useSnapshot } from 'valtio/esm/index.js';`
https://stackblitz.com/edit/react-ts-ghtvhh?file=Hello.tsx
Now, the error message is `Cannot use 'import.meta' outside a module`. So the error seems to tell that Turbo doesn't understand ESM.

cc @barelyhuman we have another beast.

**Comment by barelyhuman** [comment]
we jinxed it with the posts we made. I'll get on it tomorrow 👍🏼

**Comment by barelyhuman** [comment]
It can't handle any multi entry package, doesn't work with `@barelyhuman/useless` either and needs a definite path to the module and specifically a `.cjs` module 

attempted imports 
```js
import classnames from '@barelyhuman/useless/classnames'; // Failed
import {classnames} from '@barelyhuman/useless'; // Failed
import classnames from '@barelyhuman/useless/classnames.cjs'; // Works but can't find type defs
```

Let say they need a umd version to work with based on a few of the issues on their repo, 
the below code spins it forever, so I'm going to create an issue on their repo for this, so we can know if it's the package 
or the bundler being used internally.

```js
import React from 'react';
import { proxy, useSnapshot } from 'valtio/umd/index.production';

const s = proxy({ c: 1 });
export default () => {
  const snap = useSnapshot(s);
  return <h1>c:{snap.c}</h1>;
};

```

**Comment by barelyhuman** [comment]
backlick: https://github.com/stackblitz/core/issues/1852

**Comment by borakuldeep** [comment]
I switched to vite (react+ts) project in stackblitz and this seems to work.
