### ISSUE TITLE
Replacing object that you are subscribed to?

### ISSUE THREAD

**Issue by skokenes** [pmndrs/valtio#449]
Hi, I have a question about valtio usage.

I have an object that I want to watch for changes. I do this like so:
```javascript
const unsubscribe = subscribe(state.myObject, () => {
  // callback to run whenever object changes
})
```

Occasionally, in response to a change in myObject, I want to reset the object completely to a new state. At first I tried doing this like so:
```javascript
const unsubscribe = subscribe(state.myObject, () => {
  // callback to run whenever object changes
  if(needToReplace) {
    state.myObject = newObjectState
  }
})
```

However, this breaks my subscription as subsequent subscriptions aren't received.
Is there a better way to do this type of scenario with valtio's API?

**Comment by dai-shi** [comment]
In this scenario, you need to watch the parent `state` object
```js
const unsubscribe = subscribe(state, () => {
  ...
})
```

You can use `subscribeKey` if you want.
```js
const unsubscribe = subscribeKey(state, 'myObject', () => {
  ...
})
```

Alternatively, you can try to keep the `state.myObject` reference.
```js
const unsubscribe = subscribe(state.myObject, () => {
  // callback to run whenever object changes
  if(needToReplace) {
    for (const key in state.myObject) {
      delete state.myObject[key]
    }
    Object.assign(state.myObject, newObjectState)
  }
})
```

**Comment by dai-shi** [comment]
Closing as resolved.

**Comment by rubenapino** [comment]
> 

This is exactly what i was looking for , thanks! I didn't think to do Object.assign!
