### ISSUE TITLE
How can I use controlled Components with valtio?

### ISSUE THREAD

**Issue by thelinuxlich** [pmndrs/valtio#45]
With `useState` you can have a controlled component with no extra worries, but with valtio proxied variables, if I map the `state.variable` to the `value` property of the component and the `snapshot.variable` to the `onChange` event, weird behavior happens(textareas, for example, when you type the cursor drops to the end of the text on every change)

**Comment by dai-shi** [comment]
Right, just yesterday, I noticed this behavior in jotai and know valtio is the same. Jotai is more severe because it tries to replace useState usage, and will fix it soon.

For valtio, I'm not sure what to do. This is causing with (async) batching mutations. Maybe, add a new function to trigger updates in sync, but it's hardly a nice solution. Hm, that's almost the same as forceUpdate. (and it doesn't work, OK, I need to fix something. will work on it.)

**Comment by dai-shi** [comment]
OK, here's the workaround.
https://codesandbox.io/s/suspicious-darwin-dv99h?file=/src/App.js

I guess this is the best for now. It's unfortunate to have such a pitfall, though.

**Comment by thelinuxlich** [comment]
Might be worth looking how react-easy-state does this, it uses proxies too and they fixed the caret positioning issue https://github.com/RisingStack/react-easy-state/pull/144

**Comment by dai-shi** [comment]
Yeah, exporting batch is another option.
I'm a bit concerned about it though. In addition to exporting another function, we'd need almost always require `batch()` and it'd become looks like immer's `produce()`. I really think the default behavior should be batching automatically.

(which could lead, valtio is best fit with react-hook-form. 🤔 )

**Comment by dai-shi** [comment]
Just to mitigate the forceUpdate hack, we could provide a util. (This is still unfortunate.)
```js
import { proxy, useProxy } from 'valtio'
import { useSyncUpdate } from 'valtio/utils'

const state = proxy({ text: 'hello' })

const TextBox = () => {
  const snapshot = useProxy(state)
  const update = useSyncUpdate()
  const onChange = (e) => {
    update(() => {
      state.text = e.target.value
    })
  }
  return <input value={snapshot.text} onChange={onChange} />
}
```

but there might be another way if we create a new util.

**Comment by thelinuxlich** [comment]
at least developer experience wise this is better :)

**Comment by thelinuxlich** [comment]
By the way, I'm a newbie React developer, actually learning by adopting whatever modern stuff in the ecosystem. Looking at react-hook-form, omg, so much boilerplate to get a simple html form done "the react way". Thank god we have vue and svelte to recover sanity in frontend development :(

**Comment by dai-shi** [comment]
I see... (I wouldn't say react-hook-form is the traditional react way. It seems unique to me.)

**Comment by thelinuxlich** [comment]
Anyway, any library has to fit the react constraints, thus hurting developer experience. When I see how a simple textarea binding is done in svelte and vue and look back to React, I can't shake the feeling of "omg, how this become the industry favorite"

**Comment by dai-shi** [comment]
Back to the original issue, I will try another fix which might be a little better workaround.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/romantic-nobel-j7cp3?file=/src/App.js
So, this would be better in DX. Still a pitfall, though.

**Comment by thelinuxlich** [comment]
You made the best possible improvement! Thank you!
