### ISSUE TITLE
useSnapshot(state) not giving the updated state.

### ISSUE THREAD

**Issue by sankarkumar23** [pmndrs/valtio#454]
I've two independent components. I am updating the state through one component, say component 1, and state is getting updated successfully. In other component, say BottomPanel, I've a save button and I am getting the state using useSnapshot(state). I am doing some validation when I click on save  but "snap.<object[]>" does not reflect updated values that I added in component 1. When I click on save button again everything looks good. Why am I not getting the updated state in first save click itself? Am I missing something?

````
import { useSnapshot } from "valtio";
import state from "../store";
export default function BottomPanel(): JSX.Element {
    const snap = useSnapshot(state);
    //on save click validate(snap.<object[]>) not showing updated values. When I click on save button again the updated state is showing up.
   // if make a call snap.<some method defined in store> showing updated object array in state object correctly
}
````

**Comment by dai-shi** [comment]
In your click handler, you want to use `state` instead of `snap`. Related: #425 
(If you are not sure, would you create a minimal codesandbox repro?)

**Comment by sankarkumar23** [comment]
Oh I see.. I missed the basic. We can directly use state. I was in wrong assumption everything must be referred from snap.

**Comment by dai-shi** [comment]
Yes, that might not be super clear in readme. `useSnapshot` is to make state "reactive". for non-reactive cases, we can use `state` directly.
