### ISSUE TITLE
Nested component does not read the latest change in certain case

### ISSUE THREAD

**Issue by pzs** [pmndrs/valtio#460]
Hi,

I found a strange behavior (bug?) in valtio 1.6.0. It worked in 1.4.0, but does not work from 1.5.0.
I tried to create a minimal example to reproduce the issue, also left a few comments there: https://codesandbox.io/s/valtio-to-do-list-forked-e96xjb
Could you please have a look on that?

Thanks in advance!

**Comment by dai-shi** [comment]
Thanks for reporting. This looks like a bug. Related #234 
I thought we covered this case in tests. Will have a deeper look later.
