### ISSUE TITLE
batch mutations are calling listeners with inconsistent state

### ISSUE THREAD

**Issue by Eywek** [pmndrs/valtio#465]
Hello,

I'm trying to use the `derive` util but I've ran into an issue with the following code:

```ts
/* eslint-disable no-console */
import assert from 'assert'
import { derive } from 'valtio/utils'
import { proxy, subscribe } from 'valtio/vanilla'

const state = proxy({
  tree: {
    root: ['foo'],
    children: { foo: { type: 'bar' } } as Record<string, { type: string }>
  }
})

const derived = derive({
  list: (get) => {
    const tree = get(state.tree)
    return tree.root.map(r => tree.children[r].type)
  }
}, { sync: true })

const foo = JSON.parse(JSON.stringify(state.tree))
foo.children.bar = { type: 'foo' }
foo.root.unshift('bar') // this change his applied first, without the previous one, which cause the derived.list to crash
Object.assign(state.tree, foo)

// with sync:true, this assert is failing
assert.deepStrictEqual(derived.list, ['foo', 'bar'])
```

I need to use `sync: true` with derive; but with `sync` enabled, when applying mutations with `Object.assign`, Valtio is calling derived properties with inconsistent state (e.g. `root` updated, but `children` isn't) which cause the getter to crash.

Do you have any workaround to fix this issue? 

Thank you

**Comment by dai-shi** [comment]
Well, that's why `sync: false` is default and recommended.
If you need `sync: true` for some reason, you want to memoize the derive function to avoid crashing.

```js
const memo = (fn) => {
  let last
  return (...args) => {
    try {
      return (last = fn(...args))
    } catch {
      return last
    }
  }
}

const derived = derive({
  list: memo((get) => {
    const tree = get(state.tree)
    return tree.root.map(r => tree.children[r].type)
  })
}, { sync: true })
```
(untested)

Alternatively, you may want to try `proxyWithComputed` which is kind of "sync" by default.

**Comment by Eywek** [comment]
Seems to work fine with `memo` or `proxyWithComputed` thank you
