### ISSUE TITLE
cjs/esm issue with symbols

### ISSUE THREAD

**Issue by Eywek** [pmndrs/valtio#471]
Hello,

I'm encountering an issue with symbols, I'm building an SDK using Valtio for state management, the SDK is built using CJS and use CJS Valtio files.

But, our frontend which use the SDK, import the `useSnapshot` method, from ESM Valtio files.

The issue is, since our SDK use CJS files and our React frontend use ESM files, symbols mismatch since Valtio isn't using `Symbol.for`, which means that `useSnapshot` doesn't work and returns undefined since it can't find the snapshot on my proxy.

Do you have any workaround ?

(note: using ESM for our SDK isn't really an option since it break a lot of things)

Thank you

**Comment by dai-shi** [comment]
I wonder if you can configure vite to use CJS of valtio instead of ESM.

**Comment by Eywek** [comment]
I'll look into it but from first search I've made I don't really see how

I was wondering why you didn't used `Symbol.for` to avoid any of this? What's the downside of using it?

Thank you

**Comment by dai-shi** [comment]
I could use it for a workaround, but in general `Symbol.for()` can conflict, right? If some one use another library which happen to be same name.

**Comment by dai-shi** [comment]
In addition, Symbol is not the only issue. We have other module state like `refSet`. So, `Symbol.for` doesn't solve the fundamental problem.

**Comment by dai-shi** [comment]
Thanks for sharing your workaround.
It sounds like a fairly reasonable solution.

I know it's not ideal, but we have no actionable plans now. So, closing.
Note that it doesn't mean we are not interested in looking for better solution.

For anyone:
Reporting use cases and suggestions is welcome.
Please feel free to add comments here or open a new issue/discussion.
