### ISSUE TITLE
is support SSR,  react-native ?

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [pmndrs/valtio#475]
hi， there 

https://github.com/pmndrs/valtio/issues/141#issuecomment-816511885 
in there ，@[dai-shi](https://github.com/dai-shi)   says:
> Another point is valtio/zustand states become a bit tricky in ssr scenario.

and in `readme.md` , has no describe ,  is  the project support SSR,  react-native ?

can you add describe in `readme.md` ?

thank you very much

**Comment by dai-shi** [comment]
It should work with RN without issues. It's not just RN. It works with r3f or any other renderers.
SSR is basically fine, but can be tricky with shared module state. Might need to use context depending on requirements. We can just say valtio work on server (node.js, deno...).
What kind of description do you expect? Can provide some examples?

**Comment by hu-tu-yi-shi** [comment]
like this https://github.com/TanStack/query#quick-features

a list of quick-features

list all  quick-features

eg:
```
# quick-features
   react 18
   react native
   ssr
   typescirpt


```
