### ISSUE TITLE
[devtools] Redux UI is blank when clicked

### ISSUE THREAD

**Issue by nahin-web** [pmndrs/valtio#492]
I tried with different browsers, on incognito window. The redux devtool is blank when I try to open it. It seems it does so, when I try to select the object from the choices. I am using the latest Redux devtools version 3.0.11

**Comment by dai-shi** [comment]
@Aslemammad Can you take it?

**Comment by Aslemammad** [comment]
I downloaded the latest version of redux devtools, and opened it in incognito! It works with no problem!

which version of valtio you have?

**Comment by nosferatu500** [comment]
Same here. It works fine with Redux dev tools v2, but no longer works with v3. Valtio v1.6.3.

**Comment by Aslemammad** [comment]
Hey folks, I could not resolve this because the issue does not appear for me in Redux v3. And tried to reproduce it, but it still worked with no problem.

**Comment by lovetingyuan** [comment]
could you provide a repo ? @nahin-web

**Comment by dai-shi** [comment]
Closing as stale.
