### ISSUE TITLE
allowed store ReactElement in state

### ISSUE THREAD

**Issue by wenerme** [pmndrs/valtio#510]
currently store ReactElement in state will cause error

https://codesandbox.io/s/valtio-render-test-lzqhf7?file=/src/App.tsx:1864-2096

<img width="957" alt="image" src="https://user-images.githubusercontent.com/1777211/181914932-a2d175f7-96b7-498c-8ca7-32adccf2c290.png">

due to valtio support react, maybe valtio should check is it a react element like react-fast-compare.

**Comment by dai-shi** [comment]
Sorry, I think I missed this issue.

This is expected. `<Yes>` is simply not proxyable. We should use `ref`.

I would do something like this:
```js
const yesNode = ref(<Yes />)
const noNode = ref(<No />)

const state = proxy({
  node: yesNode,
});

const onClickYes = () => {
  state.node = yesNode;
};

const onClickNo = () => {
  state.node = noNode;
};
```
