### ISSUE TITLE
Unexpected behavior using proxyWithHistory

### ISSUE THREAD

**Issue by LukasSchwarz4202** [pmndrs/valtio#516]
Hello,

working with valtio's-proxyWithHistory I stumbled over a case with unexpected behavior.
It is quite hard to explain so I recreated the problem in codesandbox.io: https://codesandbox.io/s/valtio-proxywithhistory-undo-redo-l0360p

**Comment by dai-shi** [comment]
Hmm, it looks like a bug. I'm not sure how it can cause it. Can you investigate more in detail?

**Comment by LukasSchwarz4202** [comment]
Via https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/vanilla.ts#L188 we ultimately reach line https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/vanilla.ts#L208 where the assignment of the wrong value happens.
I think it has to do with assigning reference vs assigning deep copy of an object (I hope I could help; am still quite new to Javascript)

**Comment by dai-shi** [comment]
Hmm, but "deep copy" is by design in atomWithHistory. Assigning reference won't work.
Why wrong value can happen?

**Comment by LukasSchwarz4202** [comment]
Another try: could it be that there is a problem using proxyCache for an object being an array:
https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/vanilla.ts#L56

**Comment by dai-shi** [comment]
I think it will work with arrays, but you can try disabling it as it's just a cache:
```diff
- const found = proxyCache.get(initialObject) as T | undefined
+ const found = undefined
```

**Comment by LukasSchwarz4202** [comment]
> I think it will work with arrays, but you can try disabling it as it's just a cache:
> 
> ```diff
> - const found = proxyCache.get(initialObject) as T | undefined
> + const found = undefined
> ```

This fixes the bug. What do you think: how serious is the impact of disabling the proxyCache on performance?

**Comment by dai-shi** [comment]
We shouldn't disable it.
(Now, I'm confused what's the real problem. Do we modify the original array? I thought it's frozen. Hmm.)

**Comment by LukasSchwarz4202** [comment]
Could the problem be that the lowest level array is just an array of numbers and not an array of proxies of numbers?
![Screenshot from 2022-08-11 10-22-58](https://user-images.githubusercontent.com/6068270/184238027-9dd9e2f6-fe6e-43fe-b719-22880fb1d6fd.png)

**Comment by dai-shi** [comment]
Not sure... Would you be able to reproduce the bug without using proxyWithHistory?

**Comment by LukasSchwarz4202** [comment]
> Not sure... Would you be able to reproduce the bug without using proxyWithHistory?

Hey, sorry for the week waiting time. Just came back from vacation. Here you go:
https://codesandbox.io/s/bug-valtio-references-ztgzuz

**Comment by dai-shi** [comment]
Oh, I see. There's a misconception I found.
```js
proxyState.values = myValues // internally this create a new proxy.
proxyState.values = proxy(myValues) // so, it's same as this.
```
`proxy(myValues)` means create a new proxy object _copying_ values from `myValues`.

This is by design. We use `Object.is` to compare if anything is changed.

---

Now, where do we have a bug in `proxyWithHistory` then...

**Comment by LukasSchwarz4202** [comment]
> This is by design. We use Object.is to compare if anything is changed.

But in the case of undo and redo this is the problem, at least in my opinion.

Snapshots also use references and when applying an snapshot to the current value in
https://github.com/pmndrs/valtio/blob/0801405f618d36c86af6af7e572561627c5ebf78/src/utils/proxyWithHistory.ts#L37-L38
and
https://github.com/pmndrs/valtio/blob/0801405f618d36c86af6af7e572561627c5ebf78/src/utils/proxyWithHistory.ts#L49-L50
because of the shallow compare in 
https://github.com/pmndrs/valtio/blob/0801405f618d36c86af6af7e572561627c5ebf78/src/vanilla.ts#L56-L59
incorrect old values of 
https://github.com/pmndrs/valtio/blob/0801405f618d36c86af6af7e572561627c5ebf78/src/vanilla.ts#L36
are used.

The workaround for me now is to call a cloneDeep in the lines
https://github.com/pmndrs/valtio/blob/0801405f618d36c86af6af7e572561627c5ebf78/src/utils/proxyWithHistory.ts#L37-L38
and
https://github.com/pmndrs/valtio/blob/0801405f618d36c86af6af7e572561627c5ebf78/src/utils/proxyWithHistory.ts#L49-L50
e.g.
`proxyObject.value = proxyObject.history.wip = cloneDeep(proxyObject.history.snapshots[--proxyObject.history.index] as V)`

Definitely not the best for the performance but works like a charm.

**Comment by dai-shi** [comment]
> But in the case of undo and redo this is the problem, at least in my opinion.

I agree. And, the problem is **in** `proxyWithHistory`, either in its design or in its implementation.

Snapshots are frozen objects and can't be mutated.
I'm still struggling to understand how
```js
proxyObject.value = proxyObject.history.wip = proxyObject.history.snapshots[--proxyObject.history.index]
```
causes a problem. Maybe the double assignment is bad?

Hmm, can this change any situation? (maybe not)
```js
proxyObject.value = proxyObject.history.wip = proxy(proxyObject.history.snapshots[--proxyObject.history.index])
```

Would you be able to create a test in `./history.test.tsx`?

> The workaround for me now is to call a cloneDeep

Maybe it's a right solution in the end, but I hope not.

**Comment by dai-shi** [comment]
> Maybe it's a right solution in the end, but I hope not.

I got a better understanding of the issue and it's the right solution...
