### ISSUE TITLE
Bottleneck on large objects

### ISSUE THREAD

**Issue by joelbqz** [pmndrs/valtio#519]
Hello @dai-shi I made an experiment of having 5000 form fields with different state managers and found out that Valtio isn't performing well:

Jotai
https://codesandbox.io/s/form-test-jotai-05chcf?file=/src/App.tsx

Zustand
https://codesandbox.io/s/form-test-zustand-u53m0s

Valtio(increase SIZE to 5000)
https://codesandbox.io/s/form-test-valtio-b61ldg

**Comment by dai-shi** [comment]
Thanks for reporting!
There seems nothing wrong in the usage. Something must be wrong on the library end.
(A bit surprising that nobody has reported this in the past. 😅 )

**Comment by dai-shi** [comment]
Looks like `createProxyToCompare` is slow.
https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/react.ts#L156

And, it probably happens with valtio only (not with react-tracked) because valtio snapshot is always frozen.

**Comment by dai-shi** [comment]
Fixed! https://codesandbox.io/s/form-test-valtio-fgz47b

**Comment by joelbqz** [comment]
Oh my god, that was fast ⚡  Great work

**Comment by dai-shi** [comment]
This issue is back again in v1.10.1 by #656.
