### ISSUE TITLE
Consider creating an eslint rule/plugin 

### ISSUE THREAD

**Issue by smeijer** [pmndrs/valtio#52]
As [mentioned on Twitter](https://twitter.com/dai_shi/status/1340067015176769536?s=19), the fact that one has to read from another variable than they are writing to, is quite confusing.

I understand the reasoning behind it. But that reasoning doesn't change the developer experience.

Hence I suggest to consider creating an eslint plugin. So that the developer will be protected from accidental mistakes.

This would be similar to what the react eslint plugin does for misused hooks (think dependency array / conditionally calling of hooks).

**Comment by dai-shi** [comment]
This is a very nice suggestion. Hadn't thought about it, but yes it should be able to do like react-hooks rule.

I wish someone would volunteer for developing this.

**Comment by dai-shi** [comment]
@Aslemammad made it! https://github.com/pmndrs/eslint-plugin-valtio

This is just the first version and there might be some unknown issues and obvious improvements, but it's a very good start.

Closing this issue, if someone finds any issues with it, please open a new issue here or there.

**Comment by Aslemammad** [comment]
Congrats!
