### ISSUE TITLE
custom snapshot method

### ISSUE THREAD

**Issue by BrianHung** [pmndrs/valtio#522]
Similar to #511, developers should be able to override the default [`createSnapshot` method](https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/vanilla.ts#L135-L137) used internally by valtio that's accessed by `SNAPSHOT`. 

This in effect would also allow developers to decide when to re-render since `useSnapshot` internally [depends on this method](https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/react.ts#L122).

---

For context, I'm integrating immer into valtio since immer provides a nice API for producing patches via `createDraft` and `finishDraft`. 

However, because the object given by `createDraft` is deeply _mutable_, a snapshot of it via `createSnapshot` will always reflect recent mutations. The result is [`lastSnapshot` will equal `nextSnapshot`](https://github.com/pmndrs/valtio/blob/7c85c1413992a02e7a65e698b803fdef500d008e/src/react.ts#L128-L133) and never re-render.

To get around this, immer provides a method called [`current` which provides a snapshot that doesn't reflect future mutations](https://immerjs.github.io/immer/current). In valtio, this would be used when a draft is detected.

```ts
      if (prop === SNAPSHOT) {
        return isDraft(target) ? current(target) : createSnapshot(target, receiver)
      }
```

https://codesandbox.io/s/cool-fire-fol6zz?file=/src/App.js

Notice how "edit" mutates the proxy but doesn't re-render. This is because no difference in snapshots is detected.

**Comment by dai-shi** [comment]
Thanks for suggestion.

In general, valtio API is designed to be very opinionated, and provide just one way.
For library developers and expert users, we provide a way to customize its internals. `unstable_getHandler` is one solution for it.

Exposing `createSnapshot` would probably easy, but let me take this moment and think about exposing more. I will work on it and open a PR eventually.

**Comment by dai-shi** [comment]
#528 is ready to play with.
