### ISSUE TITLE
Docs should include suspend async example

### ISSUE THREAD

**Issue by RPisRyan** [pmndrs/valtio#534]
The [async example from the readme](https://github.com/pmndrs/valtio#suspend-your-components) should be included and highlighted in the docs. 
I read through all of the docs twice, and concluded I had to roll my own async utility.

**Comment by RikuVan** [comment]
Yeah I could probably find time to add that,

**Comment by RikuVan** [comment]
async docs in https://github.com/pmndrs/valtio/pull/546
