### ISSUE TITLE
Link docs from main docs site

### ISSUE THREAD

**Issue by basarat** [pmndrs/valtio#551]
From : https://docs.pmnd.rs/
Add a link to: https://valtio.pmnd.rs/

Thanks for an amazing library :rose: :heart:

**Comment by dai-shi** [comment]
Hi, thanks for reporting. Nice idea.

Would you like to open a PR?
It's in https://github.com/pmndrs/website/tree/docs. (Notice the branch)

You can refer how it's configured for Jotai.

**Comment by wzulfikar** [comment]
Hey, I'll try create the PR

**Comment by dai-shi** [comment]
@wzulfikar Thanks!!
