### ISSUE TITLE
Countdown bug in codesandbox example

### ISSUE THREAD

**Issue by kws1207** [pmndrs/valtio#556]
https://codesandbox.io/s/valtio-countdown-to-do-list-xkgmri?from-embed

Above is codesandbox demo from https://valtio.pmnd.rs/docs/introduction/getting-started.

If you add a todo and click it several times rapidly, then the timer ticks multiple times in a second.

Is this an expected behaviour?

https://user-images.githubusercontent.com/60031762/193423096-46b83b1b-d306-4dff-b9c3-c9cf388bfdb1.mov

**Comment by dai-shi** [comment]
@RikuVan ?

**Comment by RikuVan** [comment]
@dai-shi , @kws1207 ok, added a fix. Seems we need to keep a handle on for the timeout to make sure there is not more than one at a time. Added this to the example and it seems to fix that edge case.

**Comment by RikuVan** [comment]
Your interested is appreciate but I am not sure this seems that big of a deal to me. You cross out the TODO and the timer stops. You uncross the TODO and it starts. If you rapidly click it will be canceled constantly and you will lose some milliseconds...but does this matter 🤔. It could be refactored to eg. use requestAnimationFrame for more granular control. If you would like to have a go, please do.
