### ISSUE TITLE
Poor performance when using context API to isolate component state

### ISSUE THREAD

**Issue by observerw** [pmndrs/valtio#566]
According to the [document](https://valtio.pmnd.rs/docs/guides/component-state), if I want to isolate component state, I can use Context API. But when I really did that, the whole page was very laggy. I checked out the React Profiler, from which it can be seen that the `Context.Provider` takes up most of the time:

![图片](https://user-images.githubusercontent.com/20661574/194761789-890ac29a-655e-4d9f-ac7a-e9912fb9d288.png)

Here's my custom hook for replacing `useSnapshot`:

```typescript
export const useStore = () => {
    const store = useContext(context)
    if (!store) { throw new Error("Store not initialized") }
    return useSnapshot(store)
}
```

I checked out the official React documentation, it seems that when the value of the context is updated, all of the components that use the context are updated, so `useSnapshot`'s render optimization is not working anymore. Is there any way to deal with this situation?

**Comment by dai-shi** [comment]
The `store` shouldn't be updated when value changes. Are you sure to use `useRef` or something to make it stable?

**Comment by observerw** [comment]
> The `store` shouldn't be updated when value changes. Are you sure to use `useRef` or something to make it stable?

Oh I get it. the `store` value is a proxy object, I use `useConstant` to initialized it, so the `store` itself will never change, thus the `useContext` won't cause any problem. It seems that the page lagging was caused by other problem. Thank you for your patient reply!:smile:
