### ISSUE TITLE
Next.js app fails to compile due to strict named exports (missing `experimental_use`)

### ISSUE THREAD

**Issue by jaredLunde** [pmndrs/valtio#572]
This error is thrown during Next.js compilation with the latest version of Valtio.

```
file:///Users/jared/Code/apps/potent/node_modules/.pnpm/valtio@1.7.3_react@18.2.0/node_modules/valtio/esm/index.mjs:1
import { useRef, useCallback, experimental_use, useEffect, useMemo, useDebugValue } from 'react';
                              ^^^^^^^^^^^^^^^^
SyntaxError: Named export 'experimental_use' not found. The requested module 'react' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react';
const { useRef, useCallback, experimental_use, useEffect, useMemo, useDebugValue } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15) {
  page: '/'
}
```

The normal mitigation for this in Webpack is to use the following config:
```ts
    config.module = {
      ...config.module,
      parser: {
        ...config.module.parser,
        javascript: {
          ...config.module.parser.javascript,
          exportsPresence: false,
        },
      },
    };
```

However this doesn't seem to work with Next. Maybe they use a version of Webpack that doesn't support it yet.

Love that you stay on the bleeding edge with React features! Was wondering if you would consider refactoring your import code to support Next e.g.

```ts
import pkg from 'react';
const { useRef, useCallback, experimental_use, useEffect, useMemo, useDebugValue } = pkg;
```

Otherwise, I'm happy to use `patch-package` as a last resort :)

**Comment by dai-shi** [comment]
Oh, good point. I knew this would happen when React provides ESM. But, I wasn't aware it's happening already. I don't know what would be the solution when ESM comes, but for now let's see if we have a workaround for CJS.

**Comment by dai-shi** [comment]
Does #573 fix??
https://ci.codesandbox.io/status/pmndrs/valtio/pr/573
Find "Local Install Instructions" ☝️

**Comment by jaredLunde** [comment]
That does fix it 👍🏻

**Comment by basarat** [comment]
Received the error in 1.7.3. 

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/874898/195981490-5e5f818d-95ef-4a38-b3ed-dc69ebb297cd.png">

Indeed local install https://ci.codesandbox.io/status/pmndrs/valtio/pr/573 does fix it :rose:

**Comment by dai-shi** [comment]
Thanks for reporting, folks.
Let's release a patch version.
