### ISSUE TITLE
Website looks wrong with Opera browser

### ISSUE THREAD

**Issue by roman-koshchei** [pmndrs/valtio#577]
Just look! There is no issue with Chrome. But in Opera browser:
![image](https://user-images.githubusercontent.com/103932583/197345675-5b3d5cd7-267a-4311-8017-764f54256552.png)

**Comment by dai-shi** [comment]
@RikuVan @roguesherlock?

**Comment by roguesherlock** [comment]
@roman-koshchei Can you elaborate a bit on what exactly doesn't look right?

**Comment by roman-koshchei** [comment]
The block with the code example is too wide. It's how it should look:
![image](https://user-images.githubusercontent.com/103932583/197373822-d5c06e5c-d35f-4cc6-8b86-f956c96b077f.png)

**Comment by roguesherlock** [comment]
@roman-koshchei ah neat. I've updated the breakpoints to consider relatively larger screens. This should fix the playground appearing full width.

**Comment by roman-koshchei** [comment]
still the same problem

**Comment by roguesherlock** [comment]
@roman-koshchei did you check it on the PR preview link?

**Comment by roman-koshchei** [comment]
@roguesherlock oh sorry. Now it works, thanks a lot. I very like this state management solution.
