### ISSUE TITLE
Is there any right way on how to persist to storage?

### ISSUE THREAD

**Issue by rifaldhiaw** [pmndrs/valtio#58]
Is there any right way on how to persist the state to the storage, and set it back on the initial app render?
Thanks 

EDIT:
Sorry, my bad. I thought there is a weird behavior in the library that reset the state after I set my persisted state. Turns out, it is caused by useEffect inside component.

**Comment by gustavopch** [comment]
@rifaldhiaw Can you share snippets showing how you implemented persistence?
