### ISSUE TITLE
Unrelated changes to state cause component to re-render

### ISSUE THREAD

**Issue by jluxenberg** [pmndrs/valtio#594]
I've created a test to illustrate the issue:
https://github.com/pmndrs/valtio/pull/593/files#diff-c21e24854115b390eccde717da83f91feb2d5927a76c1485e5f0fdd0135c2afa

In this test, there is a component "App" which calls "useSnapshot" but does not reference any fields in the snapshot.

Steps to reproduce:
1. update "text" in state

Expected result:
"App" should not re-render when "text" field is updated in state

Actual result:
"App" re-renders on any change to "text" field in state

**Comment by MD2990** [comment]
Any import of snapshot will do that, there should be a good reason for that

**Comment by dai-shi** [comment]
Yes, it's intentional. It means, it "uses" the entire snap object.
I understand the confusion as I had the same feeling originally, but this behavior is more consistent.

```js
const state = proxy({ obj: {} })

  const { obj: _unused } = useSnapshot(state); // this should re-render if `state.obj = {}`
  const _unused = useSnasptho(state.obj); // so should this.
```

**Comment by dai-shi** [comment]
If you think this should never re-render, then it's consistent. But, I think this should re-render.

```js
const { obj: _unused } = useSnapshot(state);
```

**Comment by jluxenberg** [comment]
Ah, I understand now; thanks for that example.

Accessing a field will subscribe to any changes in that field. If you access sub-fields of an object to which you are subscribed, those accesses will refine your subscription.
