### ISSUE TITLE
web components and esm

### ISSUE THREAD

**Issue by chase-moskal** [pmndrs/valtio#6]
hey hey! i've been looking for a mobx replacement because it's so bloated: and valtio looks really elegant and promising!

unfortunately, i can't consider valtio because my apps are esm-only and use true web components — no react — i'm currently using `lit-element`

are there any plans to decouple valtio from react, so it can be used in any application, like mobx?

to alleviate the incompatibility, in addition to the react-decoupling work, the esm distribution would need to be modified to include `.js` extensions on all non-bare-specifier esm imports (so that library can work natively in browsers), eg:
- `import { createMutableSource, useMutableSource } from './useMutableSource'`  
    &nbsp; &nbsp; *becomes*
- `import { createMutableSource, useMutableSource } from './useMutableSource.js'`

:wave: chase

**Comment by dai-shi** [comment]
Hi, honestly I didn't expect this is even useful without React. Most of effort is to combine with React. So, there was no such plan.
That said, as you express strong interest, let me try decoupling and see how it goes.
