### ISSUE TITLE
Component cannot unsuspend if it suspended by infinite promise

### ISSUE THREAD

**Issue by dvlkv** [pmndrs/valtio#632]
## Summary
Infinite promise suspends component without ability to unsuspend.
```
import { Suspense } from 'react'
import { proxy, useSnapshot } from 'valtio';
import { isLoading } from '../../engine/base/loading'


const suspender = proxy<{ suspended: boolean | Promise<boolean> }>({
    suspended: false,
});

const Suspender = () => {
    useSnapshot(suspender).suspended;

    return (
        <div>
            <h1>Suspender</h1>
        </div>
    )
}

export default () => {
    return (
        <>
            <Suspense fallback={<span>Suspended</span>}>
                <Suspender />
            </Suspense>
            <button onClick={() => {
                if (isLoading(suspender.suspended)) {
                    suspender.suspended = false;
                    console.log('unsuspend');
                } else {
                    console.log('suspend');
                    suspender.suspended = new Promise(() => {});
                }
            }}>Suspend</button>
        </>
    )
}
```

## Link to reproduction
https://codesandbox.io/s/hardcore-nightingale-9xvl1m?file=/src/App.tsx

**Comment by dvlkv** [comment]
After a small investigation I've found out that the problem hides in `createProxy` from `proxy-compare`

**Comment by dai-shi** [comment]
This is an unsupported usage. React can't do that either. You should resolve the promise on your end.

A bit of background:
Jotai can do it with a careful design. It's tricky implementation-wise.
Valtio implementation is pretty simple as just throwing a promise.
When the `use` hook from React lands, this technique might not be possible, and we may need to re-design the API then. So, we shouldn't do something new at this point.
