### ISSUE TITLE
Docs site favicon is not updated

### ISSUE THREAD

**Issue by thara003** [pmndrs/valtio#659]
## Summary

I think the favicon of valtio's doc site has not been updated, it still shows up the one in the starter template of Next.js (i.e. vercel's favicon)

## Link to reproduction

1. Visit [valtio.pmnd.rs/](https://valtio.pmnd.rs/)
2. Check the favicon of the site.

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/valtio/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [ ] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
But, we don't have any logos.

@roguesherlock what do you think?

**Comment by roguesherlock** [comment]
@dai-shi My bad. I was supposed to ask you about those and then change it but completely forgot about it.
How about the 💊 symbol as favicon or should we make a new one? If we want a new one, we can ask the community or maybe I can take a stab at it. let me know what you think

**Comment by dai-shi** [comment]
For now, we can put 💊 . (tbh, I don't know what it is.)

**Comment by roguesherlock** [comment]
@dai-shi I also created a basic favicon. let me know which you like best and I'll update it,
![android-chrome-512x512](https://user-images.githubusercontent.com/5683543/217500905-cabab197-8b02-4025-b7aa-a3617a27c6c3.png)
![mstile-150x150](https://user-images.githubusercontent.com/5683543/217500998-8ab43d34-8978-4bb6-9977-96b9530225d4.png)

**Comment by dai-shi** [comment]
we may replace it in the future, but let's go with the first one, yours.
