### ISSUE TITLE
Thoughts on middleware?

### ISSUE THREAD

**Issue by JamesGelok** [pmndrs/valtio#67]
Learned about this from [Jack Herrington's youtube video from about a month ago](https://www.youtube.com/watch?v=XnlECbwcJZ0). 

This looks really cool! From what I gathered in your docs and the aforementioned video, valtio satisfies all these conditions

- [x] Manage shared state 
- [x] Allow for subscriptions from React 
- [x] Allow for mutation from React 
- [x] Allow for subscriptions from non—React 
- [x] Allow for mutation from non—React 
- [x] Allow for methods on the global state 
- [x] Allow for derived data on the global state 
- [x] Optimized re—renders

Wondering if there are plans for middleware for this to enable add-ons that could cover 

- [ ] State/Mutation logging
- [ ] Time travel debugging

I imagine it'd be great for tools like or custom solutions log rocket to be able to record sessions state mutations
Thoughts on supporting middleware? or if you do including that in the readme?

**Comment by dai-shi** [comment]
Hi, thanks for the attention.

> logging

https://github.com/pmndrs/valtio#subscribe-from-anywhere

```js
const unsubscribe = subscribe(state, () => console.log('state has changed to', state))
```

Seems good?

> time traveling

https://github.com/pmndrs/valtio#dev-tools

It should work as long as state (snapshot) is serializable.

> I imagine it'd be great for tools like or custom solutions log rocket to be able to record sessions state mutations

Ah, this, I'm not sure. But, wouldn't it be like the same?

> supporting middleware

Not sure what middleware specifically means. I don't think we need to add anything to support 3rd party add-ons. For official ones, we have some in `valtio/utils`. In terms of eco system, we have `eslint-plugin-valtio` too!

**Comment by JustFly1984** [comment]
Please no middleware in 2021! it forces to use mixin patterns, which is not safe in many ways starting with types, continue with leaking references and memory.

**Comment by thelinuxlich** [comment]
Until some solid composition idea comes in, I think this should be closed

**Comment by dai-shi** [comment]
Yep. For anyone, please open a new discussion for specific use case.
