### ISSUE TITLE
allow `useProxy` to pass `useSnapshot` options

### ISSUE THREAD

**Issue by steve-py96** [pmndrs/valtio#683]
## Summary

`useProxy` only takes the store yet as argument, in case of input-elements a sync pass-through would also be required (ref https://github.com/pmndrs/valtio/#update-synchronously)

## Link to reproduction

https://stackblitz.com/edit/vitejs-vite-6d3nla?file=src%2FApp.jsx&terminal=dev

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/valtio/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Great point. Would you like to open a PR? Use `Parameters<typeof useSnapshot>[1]` to get options type.

**Comment by steve-py96** [comment]
Will gladly do 👍🏿
