### ISSUE TITLE
synchronous partial state update Interface

### ISSUE THREAD

**Issue by Juyeong-Byeon** [pmndrs/valtio#700]
## Summary

just like described below link there is no synchronous partial state update Interface in valtio 
https://github.com/pmndrs/valtio/discussions/699

So there is some limits. for achieve the goal to use batched updates for some parts of the state while still having the ability to perform synchronous updates for other parts.

## Link to reproduction
https://codesandbox.io/s/valtio-sandbox-forked-ij76sz?file=/src/App.js

## Check List

- [x] I've already opened a [discussion](https://github.com/pmndrs/valtio/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by dai-shi** [comment]
Let's re-open when we have some ideas in #699.
