### ISSUE TITLE
One more change for computeds

### ISSUE THREAD

**Issue by thelinuxlich** [pmndrs/valtio#72]
the computed properties should accept two signatures: a function if it's just a getter and a object with get/set if it needs the setter.

**Comment by thelinuxlich** [comment]
#71

**Comment by dai-shi** [comment]
I thought about it, but is it too troublesome?
Having `get` seems clear.
I don't any TS issues, so the change is acceptable, though. documentation needs a little effort.

**Comment by thelinuxlich** [comment]
DX wise I think the shortcut is better. Computed setter is a small niche, although useful, it's how it's done in Vue.js, for example: https://vuejs.org/v2/guide/computed.html

**Comment by dai-shi** [comment]
Fair enough.
