### ISSUE TITLE
Vanilla `subscribe` does not trigger when a computed getter is updated

### ISSUE THREAD

**Issue by sharathprabhal** [pmndrs/valtio#743]
### Discussed in https://github.com/pmndrs/valtio/discussions/742

<div type='discussions-op-text'>

<sup>Originally posted by **sharathprabhal** June 29, 2023</sup>
I use Valtio as a store for in a project that uses both React and vanilla. I have a keyed object of items in a store. Based on user action, I set a "derived" currentObject and use a getter to select "current object" and perform operations on it. When the "current object" is updated, `useSnapshot` triggers but subscribe does not.

See repro code at https://codesandbox.io/s/valtio-subscribe-57p4st

Please let me know if this is a bug or if there is a alternate/better way to do this. Thanks!</div>

**Comment by dai-shi** [comment]
Please keep discussing in #742.

**Comment by sharathprabhal** [comment]
Thanks @dai-shi , any guidance is greatly appreciated!
