### ISSUE TITLE
Snapshots can be mutated by adding or removing properties

### ISSUE THREAD

**Issue by pastelmind** [pmndrs/valtio#749]
## Summary

Adding or removing properties from a snapshot object or array does not throw, even in strict mode.

```js
'use strict' // Must be enabled in browser scripts / Node CommonJS

const state = proxy([5, 10, 15])
const snap = snapshot(state)

// snap[0] = 100 // Throws
snap[10] = 100 // Does not throw
snap.push(100) // Does not throw
snap.pop() // Does not throw

const state2 = proxy({ foo: 1 })
const snap2 = snapshot(state2)

// snap2.foo = 100 // Throws
snap2.bar = 2 // Does not throw
```

Although it appears that such invalid operations do not affect the proxy store itself, ~~silently swallowing~~ <ins>allowing</ins> these errors is undesirable, since the snapshot (correctly) errors on other types of mutations.

<ins>Edit: The snapshot _can_ be mutated:</ins>

```js
const p = proxy({ foo: 1 });
const s = snapshot(p);
console.log(s); // { foo: 1 }
s.bar = 2;
console.log(s); // { foo: 1, bar: 2 }
delete s.foo;
console.log(s); // { bar: 2 }
```

This seems to be a correctness issue.

## Link to reproduction

https://codesandbox.io/s/sad-gauss-w364gf

## Check List

Please do not ask questions in issues.

- [ ] I've already opened a [discussion](https://github.com/pmndrs/valtio/discussions) before opening this issue, or already discussed in other media.

Please include a minimal reproduction.

- [x] I've added a link to a [typescript playground](https://www.typescriptlang.org/play) or [codesandbox](https://codesandbox.io) with a minimal reproduction.

**Comment by pastelmind** [comment]
Preventing the addition of new properties should be trivial. We can call `Object.preventExtensions()` on the snapshot object here, just before returning it [here](https://github.com/pmndrs/valtio/blob/5d0eca7edc25aa7f17fb8082ef14244a35fc12b2/src/vanilla.ts#L149):

```diff
diff --git a/src/vanilla.ts b/src/vanilla.ts
index 7844994..1e169a0 100644
--- a/src/vanilla.ts
+++ b/src/vanilla.ts
@@ -146,6 +146,7 @@ const buildProxyFunction = (
       }
       Object.defineProperty(snap, key, desc)
     })
+    Object.preventExtensions(snap)
     return snap
   },
```

I tested this locally and found no breaking tests. I can submit a PR if you want.

However, preventing deletion would be a bit more involved. It's hard to grok the details, but I believe snapshot properties were made configurable in ba53bf6fec891ec82a6fca211c562e49dbc38aae (#664) due to performance issues. Would it be too difficult to revert it?

If we want to avoid reverting the above, I suppose we might be able to wrap the snapshot object in its own `Proxy` with a `deleteProperty` handler that throws a `TypeError`. This sounds too complicated and risky, though.

**Comment by dai-shi** [comment]
We used to deep-freeze snapshot object. But, there's performance downside, because we had to deep-copy the object in `proxy-compare`. So, it means we took performance over correctness.

`Object.preventExtensions()` sounds good. If it doesn't break existing tests **and** it doesn't drop performance (but, we don't have tests for it), we can merge it.
