### ISSUE TITLE
useLocalProxyWithComputed

### ISSUE THREAD

**Issue by thelinuxlich** [pmndrs/valtio#75]
Since we have now two separate proxy methods, we will need a new useLocalProxyWithComputed method too for local state/snapshot

**Comment by dai-shi** [comment]
That's technically true... I just don't see enough use cases to move this on, because both are already special. I'm less confident to have `useLocalProxy`...

**Comment by thelinuxlich** [comment]
well I don't use useLocalProxy in my projects but let's see if more people ask about the same thing

**Comment by dai-shi** [comment]
I feel like I want to drop `useLocalProxy` before v1 and possibly move it to something like recipe.

**Comment by thelinuxlich** [comment]
I found that useLocalProxy is actually very useful when you have a component that will be rendered in a list, so each one with its own state/snapshot. It's a one-liner, can't get wrong with one-liners

**Comment by dai-shi** [comment]
I decided to remove useLocalProxy for various reasons. #101 
You can define it in your local project, but it's not well designed for local state. (Internally it uses uMS, which would be for mutable source, which is not often necessary in local state.)
