### ISSUE TITLE
compiles fails after upgrade to 0.7.0

### ISSUE THREAD

**Issue by jmsunseri** [pmndrs/valtio#78]
node_modules/valtio/utils.d.ts
TypeScript error in node_modules/valtio/utils.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { NonPromise } from './vanilla';
      |             ^
    2 | /**
    3 |  * useLocalProxy
    4 |  *

error Command failed with exit code 1.

**Comment by stephencorwin** [comment]
I believe `import type` is the syntax for importing a Flow Type, not TypeScript. For typescript you can omit the `type` from the import statement

**Comment by dai-shi** [comment]
Ah, we intentionally use type-only import there.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
Is it possible for you to upgrade TypeScript version?

**Comment by jmsunseri** [comment]
if I do I feel like that's going to be a cascading set of changes that's going to be really annoying to deal with.

**Comment by dai-shi** [comment]
what's your ts version?

we may try this: https://github.com/sandersn/downlevel-dts
not sure if it works for `utils`.

**Comment by jmsunseri** [comment]
3.7.5

Sincerely,
Justin Sunseri
