### ISSUE TITLE
Component re-rendered, but it shouldn't be...

### ISSUE THREAD

**Issue by volkanunsal** [pmndrs/valtio#80]
I'm noticing an issue where the last component to have been affected by a mutation is rendered again for the next mutation (even if that mutation did not affect the properties used within that component.) 

I made a gif showing what is happening:

![Screen Recording 2021-02-06 at 3 23 38 PM](https://user-images.githubusercontent.com/151600/107128993-0bf33680-6890-11eb-9452-ce816c1c4660.gif)

Switching from "count" to "ticks" also renders the component for "count." When we press the button again, only the "count" component is rendered. Switching in the other direction, we observe the same effect.

This is the code I'm using:

```jsx
import React from 'react'
import { proxy, useProxy } from 'valtio'

const state = proxy({
  count: 0,
  nested: { ticks: 0 },
})

function Counter() {
  const snapshot = useProxy(state)
  console.log('render Counter')
  return <h1>{snapshot.count}</h1>
}

function Controls() {
  const incCounter = () => {
    state.count++
  }
  const incTicks = () => {
    state.nested.ticks++
  }
  console.log('render Controls')
  return (
    <div>
      <button onClick={incCounter}>one up count</button>
      <button onClick={incTicks}>one up nested ticks</button>
    </div>
  )
}

function Ticks() {
  const snapshot = useProxy(state)
  console.log('render Ticks')
  return <h1>{snapshot.nested.ticks}</h1>
}

export default function App() {
  return (
    <>
      <Counter />
      <Ticks />
      <Controls />
    </>
  )
}

```

**Comment by dai-shi** [comment]
I understand this behavior. Would you try checking the render count with useEffect and is expected?

```js
  useEffect(() => {
    console.log('render Counter')
  })
```

---

The reason behind this is to support Concurrent Mode at best effort.
Valtio is developed to support CM from the ground up.
Technically, render functions are pure and running them extra time is fine as long as it's not committed.
In the future version of Valtio, when React releases useMutableSource hook officially, this behavior would be improved.

**Comment by volkanunsal** [comment]
Very interesting. I'd never heard of `useMutableSource` hook. How would that improve this behavior?

**Comment by volkanunsal** [comment]
The double logging doesn't happen in `useEffect`, btw. It works as expected.

**Comment by dai-shi** [comment]
> How would that improve this behavior?

I would expect it would avoid double invoking the render function.

It's currently my best-effort emulation of it with double invoking (same as `use-subscription`)

**Comment by volkanunsal** [comment]
Sounds good. Thanks for the explanation.
