### ISSUE TITLE
Computed fields can't be added to nested objects

### ISSUE THREAD

**Issue by thelinuxlich** [pmndrs/valtio#85]
This would enable a computed to belong to the same namespace(i.e object) of a reactive property, for better organization

https://codesandbox.io/s/valtio-simple-counter-forked-z9mzx?file=/src/App.js

**Comment by dai-shi** [comment]
Interesting. That might be a nice feature addition (and this would solve "unsupported externals" issue). I'm afraid the code becomes 2-3 times bigger and complicated, though.

One small issue I noticed is, if we change `doubled` to `get`, it behaves totally wrongly.

```js
const state = proxyWithComputed(
  { math: { number: 1 } },
  {
    math: {
      get(snap) {
        return snap.math.number * 2;
      }
    }
  }
);
```

**Comment by dai-shi** [comment]
On second thought, merging two `math` objects seems extremely hard. `externals` might be easier...
Let's see if some new ideas would click me...

**Comment by dai-shi** [comment]
> So, the question is how should we handle the get shorthand.

Any idea for this? especially to make it typescript friendly.

**Comment by thelinuxlich** [comment]
The example you added should error because it's trying to overwrite a reactive field, so it's just a matter of updating the docs with this caveat:

```js
const state = proxyWithComputed(
  { math: { number: 1 } },
  {
    math: { // maybe verify this with eslint-plugin-valtio, cause it's trying to overwrite the reactive property math<Object>
      get(snap) {
        return snap.math.number * 2;
      }
    }
  }
);
```

**Comment by thelinuxlich** [comment]
I mean, in the context of computed fields, get and set are reserved

**Comment by dai-shi** [comment]
> I mean, in the context of computed fields, get and set are reserved

If you are ok with it, then fine. That example is actually not an error, it's a valid `get`.

The remaining concern is typescript...

**Comment by dai-shi** [comment]
I thought I made it (incl. typescript) but it doesn't work...
https://github.com/pmndrs/valtio/tree/feat/nested-computed

Not sure why this happens... (`undefined`. the order issue again.)

**Comment by thelinuxlich** [comment]
BTW when a computed field has something wrong the state is still silently created with a subset of fields, it should throw an error

**Comment by thelinuxlich** [comment]
Added a issue to eslint-plugin-valtio to check on computed fields overwriting reactive fields, but that might change a little bit when we support the nested behavior https://github.com/pmndrs/eslint-plugin-valtio/issues/5

**Comment by dai-shi** [comment]
I didn't have time since the first trial. It would be really nice if that impl worked.

overwrite checking should be easy. typing would be hard. we could try it separately before supporting nesting.

**Comment by thelinuxlich** [comment]
Typing can be added later

**Comment by dai-shi** [comment]
> Typing can be added later

Well, it's controversial. In my recent TS projects, I avoid designing APIs that are not type friendly.

That said, detecting overwrites is just nice to have, and I'd just give up if it's not possible.

**Comment by thelinuxlich** [comment]
Theoretically Typescript should never get in the way of a feature
