### ISSUE TITLE
A util method to add computed to state

### ISSUE THREAD

**Issue by thelinuxlich** [pmndrs/valtio#86]
Right now it's natural to add a reactive property to a proxified state object, what's missing is a util method for doing the same with computed:

```js
import { addComputed } from 'valtio/utils'
import state from './store/root' 

addComputed(state, { double(snap) { return snap.counter * 2 } })
```

**Comment by dai-shi** [comment]
Hey, this is interesting. Can we drop proxyWithComputed if we support chaining addComputed?

**Comment by dai-shi** [comment]
Maybe not. I don’t have an idea yet to support nested computeds with addComputed.

**Comment by thelinuxlich** [comment]
If it's possible to add multiple computeds in a single call, I'd say yes

**Comment by dai-shi** [comment]
OK, I might need to change a signature a bit. Let's see how you like it.

**Comment by dai-shi** [comment]
Hmm, my challenges are not very successful.

https://github.com/pmndrs/valtio/tree/feat/add-computed
The result doesn't seem to be very handy as it still requires `proxyWithComputed`.

https://github.com/pmndrs/valtio/tree/feat/add-computed-2
This one can't support computed setters.

In either case, nested computed is tricky with typescript.

Is there a real use case to add computed afterward?

**Comment by thelinuxlich** [comment]
@dai-shi IMO the first branch accomplishes the feature, although not as you'd like (deprecating proxyWithComputed)

Real use cases:

- Augmenting a state tree with reactive/computed fields through plugins(or mixins)
- Dynamic reactive/computed field generation(through a CMS, smart form generator, etc)
