### ISSUE TITLE
Rename Op type and export it

### ISSUE THREAD

**Issue by overthemike** [pmndrs/valtio#972]
### Discussed in https://github.com/pmndrs/valtio/discussions/971

<div type='discussions-op-text'>

<sup>Originally posted by **teetotum** October 14, 2024</sup>
The import of `type Op` is not recognized: `Module '"valtio"' has no exported member 'Op'.ts(2305)`
What would be the correct import for valtio types?
I'm on valtio 1.13.0

```ts
import { subscribe, proxy, type Op } from 'valtio'

// ...
// const state = ...
// ...

subscribe(proxy(state), (ops: Op[]) => {
  // ...
})
```
</div>

Since ops are passed into a callback for the user during a subscribe, it would be helpful to export the type that the user can expect. Might be a good idea to rename it to something that explains what it is a bit better as well.

**Comment by dai-shi** [comment]
Op is an internal type and not considered a public API. Let me rename it to clarify it.

**Comment by overthemike** [comment]
https://github.com/pmndrs/valtio/blob/main/src/vanilla.ts#L272 - In that case, should it be passed to the user in the callback?

**Comment by dai-shi** [comment]
It's used by third-party libraries.
